/*
Plex Developer API

Testing SupplyItemSuppliersAPIAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_SupplyItemSuppliersAPIAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SupplyItemSuppliersAPIAPIService SupplyItemSuppliersApiGetSupplyItemSupplier", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.SupplyItemSuppliersAPIAPI.SupplyItemSuppliersApiGetSupplyItemSupplier(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SupplyItemSuppliersAPIAPIService SupplyItemSuppliersApiListPrices", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.SupplyItemSuppliersAPIAPI.SupplyItemSuppliersApiListPrices(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SupplyItemSuppliersAPIAPIService SupplyItemSuppliersApiListSupplierItemSuppliers", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SupplyItemSuppliersAPIAPI.SupplyItemSuppliersApiListSupplierItemSuppliers(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
