/*
Plex Developer API

Testing PlexAPMAPIAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_PlexAPMAPIAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PlexAPMAPIAPIService PlexApmApiGetAssetList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PlexAPMAPIAPI.PlexApmApiGetAssetList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PlexAPMAPIAPIService PlexApmApiGetAssetNumericalData", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PlexAPMAPIAPI.PlexApmApiGetAssetNumericalData(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PlexAPMAPIAPIService PlexApmApiGetAssetStatuses", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PlexAPMAPIAPI.PlexApmApiGetAssetStatuses(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PlexAPMAPIAPIService PlexApmApiGetElapsedTimeByAssets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PlexAPMAPIAPI.PlexApmApiGetElapsedTimeByAssets(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PlexAPMAPIAPIService PlexApmApiGetElapsedTimeByTags", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PlexAPMAPIAPI.PlexApmApiGetElapsedTimeByTags(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PlexAPMAPIAPIService PlexApmApiGetLatestTagValue", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.PlexAPMAPIAPI.PlexApmApiGetLatestTagValue(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PlexAPMAPIAPIService PlexApmApiGetTagValueAtSpecifiedTime", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var specificTime time.Time

		resp, httpRes, err := apiClient.PlexAPMAPIAPI.PlexApmApiGetTagValueAtSpecifiedTime(context.Background(), specificTime).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
