/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response{}

// SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response The Order Lines Ship To model exposed.
type SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response struct {
	// The ID of the sales order.
	Id *string `json:"id,omitempty"`
	// The ID of the order line.
	LineId *string `json:"lineId,omitempty"`
	// The ID of the ship to customer address record assigned to an order line.
	ShipToAddressId *string `json:"shipToAddressId,omitempty"`
	// The ID of the carrier assigned to an order line approved Ship To record.
	DefaultCarrierId *string `json:"defaultCarrierId,omitempty"`
	// The carrier assigned to an order line approved Ship To record.
	DefaultCarrier *string `json:"defaultCarrier,omitempty"`
	// The ID of the default building from which shipments will be sent.
	DefaultShipFromId *string `json:"defaultShipFromId,omitempty"`
	// The building code from which the shipment will be shipped from by default.
	DefaultShipFromCode *string `json:"defaultShipFromCode,omitempty"`
}

// NewSalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response instantiates a new SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response() *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response {
	this := SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response{}
	return &this
}

// NewSalesOrdersApiCreateSalesOrderLineApprovedShipTo201ResponseWithDefaults instantiates a new SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSalesOrdersApiCreateSalesOrderLineApprovedShipTo201ResponseWithDefaults() *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response {
	this := SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) SetId(v string) {
	o.Id = &v
}

// GetLineId returns the LineId field value if set, zero value otherwise.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) GetLineId() string {
	if o == nil || IsNil(o.LineId) {
		var ret string
		return ret
	}
	return *o.LineId
}

// GetLineIdOk returns a tuple with the LineId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) GetLineIdOk() (*string, bool) {
	if o == nil || IsNil(o.LineId) {
		return nil, false
	}
	return o.LineId, true
}

// HasLineId returns a boolean if a field has been set.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) HasLineId() bool {
	if o != nil && !IsNil(o.LineId) {
		return true
	}

	return false
}

// SetLineId gets a reference to the given string and assigns it to the LineId field.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) SetLineId(v string) {
	o.LineId = &v
}

// GetShipToAddressId returns the ShipToAddressId field value if set, zero value otherwise.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) GetShipToAddressId() string {
	if o == nil || IsNil(o.ShipToAddressId) {
		var ret string
		return ret
	}
	return *o.ShipToAddressId
}

// GetShipToAddressIdOk returns a tuple with the ShipToAddressId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) GetShipToAddressIdOk() (*string, bool) {
	if o == nil || IsNil(o.ShipToAddressId) {
		return nil, false
	}
	return o.ShipToAddressId, true
}

// HasShipToAddressId returns a boolean if a field has been set.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) HasShipToAddressId() bool {
	if o != nil && !IsNil(o.ShipToAddressId) {
		return true
	}

	return false
}

// SetShipToAddressId gets a reference to the given string and assigns it to the ShipToAddressId field.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) SetShipToAddressId(v string) {
	o.ShipToAddressId = &v
}

// GetDefaultCarrierId returns the DefaultCarrierId field value if set, zero value otherwise.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) GetDefaultCarrierId() string {
	if o == nil || IsNil(o.DefaultCarrierId) {
		var ret string
		return ret
	}
	return *o.DefaultCarrierId
}

// GetDefaultCarrierIdOk returns a tuple with the DefaultCarrierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) GetDefaultCarrierIdOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultCarrierId) {
		return nil, false
	}
	return o.DefaultCarrierId, true
}

// HasDefaultCarrierId returns a boolean if a field has been set.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) HasDefaultCarrierId() bool {
	if o != nil && !IsNil(o.DefaultCarrierId) {
		return true
	}

	return false
}

// SetDefaultCarrierId gets a reference to the given string and assigns it to the DefaultCarrierId field.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) SetDefaultCarrierId(v string) {
	o.DefaultCarrierId = &v
}

// GetDefaultCarrier returns the DefaultCarrier field value if set, zero value otherwise.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) GetDefaultCarrier() string {
	if o == nil || IsNil(o.DefaultCarrier) {
		var ret string
		return ret
	}
	return *o.DefaultCarrier
}

// GetDefaultCarrierOk returns a tuple with the DefaultCarrier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) GetDefaultCarrierOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultCarrier) {
		return nil, false
	}
	return o.DefaultCarrier, true
}

// HasDefaultCarrier returns a boolean if a field has been set.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) HasDefaultCarrier() bool {
	if o != nil && !IsNil(o.DefaultCarrier) {
		return true
	}

	return false
}

// SetDefaultCarrier gets a reference to the given string and assigns it to the DefaultCarrier field.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) SetDefaultCarrier(v string) {
	o.DefaultCarrier = &v
}

// GetDefaultShipFromId returns the DefaultShipFromId field value if set, zero value otherwise.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) GetDefaultShipFromId() string {
	if o == nil || IsNil(o.DefaultShipFromId) {
		var ret string
		return ret
	}
	return *o.DefaultShipFromId
}

// GetDefaultShipFromIdOk returns a tuple with the DefaultShipFromId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) GetDefaultShipFromIdOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultShipFromId) {
		return nil, false
	}
	return o.DefaultShipFromId, true
}

// HasDefaultShipFromId returns a boolean if a field has been set.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) HasDefaultShipFromId() bool {
	if o != nil && !IsNil(o.DefaultShipFromId) {
		return true
	}

	return false
}

// SetDefaultShipFromId gets a reference to the given string and assigns it to the DefaultShipFromId field.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) SetDefaultShipFromId(v string) {
	o.DefaultShipFromId = &v
}

// GetDefaultShipFromCode returns the DefaultShipFromCode field value if set, zero value otherwise.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) GetDefaultShipFromCode() string {
	if o == nil || IsNil(o.DefaultShipFromCode) {
		var ret string
		return ret
	}
	return *o.DefaultShipFromCode
}

// GetDefaultShipFromCodeOk returns a tuple with the DefaultShipFromCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) GetDefaultShipFromCodeOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultShipFromCode) {
		return nil, false
	}
	return o.DefaultShipFromCode, true
}

// HasDefaultShipFromCode returns a boolean if a field has been set.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) HasDefaultShipFromCode() bool {
	if o != nil && !IsNil(o.DefaultShipFromCode) {
		return true
	}

	return false
}

// SetDefaultShipFromCode gets a reference to the given string and assigns it to the DefaultShipFromCode field.
func (o *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) SetDefaultShipFromCode(v string) {
	o.DefaultShipFromCode = &v
}

func (o SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LineId) {
		toSerialize["lineId"] = o.LineId
	}
	if !IsNil(o.ShipToAddressId) {
		toSerialize["shipToAddressId"] = o.ShipToAddressId
	}
	if !IsNil(o.DefaultCarrierId) {
		toSerialize["defaultCarrierId"] = o.DefaultCarrierId
	}
	if !IsNil(o.DefaultCarrier) {
		toSerialize["defaultCarrier"] = o.DefaultCarrier
	}
	if !IsNil(o.DefaultShipFromId) {
		toSerialize["defaultShipFromId"] = o.DefaultShipFromId
	}
	if !IsNil(o.DefaultShipFromCode) {
		toSerialize["defaultShipFromCode"] = o.DefaultShipFromCode
	}
	return toSerialize, nil
}

type NullableSalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response struct {
	value *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response
	isSet bool
}

func (v NullableSalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) Get() *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response {
	return v.value
}

func (v *NullableSalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) Set(val *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response(val *SalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) *NullableSalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response {
	return &NullableSalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response{value: val, isSet: true}
}

func (v NullableSalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSalesOrdersApiCreateSalesOrderLineApprovedShipTo201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


