/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plex

import (
	"encoding/json"
)

// checks if the AccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest{}

// AccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest struct for AccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest
type AccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest struct {
	// The list of Receipt IDs.
	ReceiptIds []string `json:"receiptIds,omitempty"`
}

// NewAccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest instantiates a new AccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest() *AccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest {
	this := AccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest{}
	return &this
}

// NewAccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequestWithDefaults instantiates a new AccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequestWithDefaults() *AccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest {
	this := AccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest{}
	return &this
}

// GetReceiptIds returns the ReceiptIds field value if set, zero value otherwise.
func (o *AccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest) GetReceiptIds() []string {
	if o == nil || IsNil(o.ReceiptIds) {
		var ret []string
		return ret
	}
	return o.ReceiptIds
}

// GetReceiptIdsOk returns a tuple with the ReceiptIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest) GetReceiptIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.ReceiptIds) {
		return nil, false
	}
	return o.ReceiptIds, true
}

// HasReceiptIds returns a boolean if a field has been set.
func (o *AccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest) HasReceiptIds() bool {
	if o != nil && !IsNil(o.ReceiptIds) {
		return true
	}

	return false
}

// SetReceiptIds gets a reference to the given []string and assigns it to the ReceiptIds field.
func (o *AccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest) SetReceiptIds(v []string) {
	o.ReceiptIds = v
}

func (o AccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ReceiptIds) {
		toSerialize["receiptIds"] = o.ReceiptIds
	}
	return toSerialize, nil
}

type NullableAccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest struct {
	value *AccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest
	isSet bool
}

func (v NullableAccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest) Get() *AccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest {
	return v.value
}

func (v *NullableAccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest) Set(val *AccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest(val *AccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest) *NullableAccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest {
	return &NullableAccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest{value: val, isSet: true}
}

func (v NullableAccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountsPayableInvoicesApiUnlinkReceiptsFromAPInvoiceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


