/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plex

import (
	"encoding/json"
	"time"
)

// checks if the ProductionOperationsManagementApiGetBatchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductionOperationsManagementApiGetBatchResponse{}

// ProductionOperationsManagementApiGetBatchResponse Batch Response
type ProductionOperationsManagementApiGetBatchResponse struct {
	// A unique identifier of the batch.
	Id *string `json:"id,omitempty"`
	// Identifier of the batch for the current job operation.
	Number *int32 `json:"number,omitempty"`
	// The status of the batch.
	BatchStatus *string `json:"batchStatus,omitempty"`
	// The quantity to be produced in the batch.
	Size *float64 `json:"size,omitempty"`
	// A unique identifier of the workcenter.
	WorkcenterId *string `json:"workcenterId,omitempty"`
	// A short name associated with the workcenter ID, and a unique code to reference the workcenter. This code displays throughout the system, primarily on the Control Panel. 50 characters max.
	WorkcenterCode *string `json:"workcenterCode,omitempty"`
	// A unique identifier of the part.
	PartId *string `json:"partId,omitempty"`
	// The part number associated with the part ID.
	PartNumber *string `json:"partNumber,omitempty"`
	// The part revision associated with the part ID.
	PartRevision *string `json:"partRevision,omitempty"`
	// A combination of the part number and revision associated with the part ID, separated with the value from the Part Rev Separator setting.
	PartNumberRevision *string `json:"partNumberRevision,omitempty"`
	// A unique identifier of the production job.
	JobId *string `json:"jobId,omitempty"`
	// The job number, including prefix and suffix, associated with the job ID.
	JobNumber *string `json:"jobNumber,omitempty"`
	// The job status.
	JobStatus *string `json:"jobStatus,omitempty"`
	// A unique identifier for the job operation.
	JobOperationId *string `json:"jobOperationId,omitempty"`
	// The job operation status.
	JobOperationStatus *string `json:"jobOperationStatus,omitempty"`
	// The operation number of the part operation.
	OperationNumber *float64 `json:"operationNumber,omitempty"`
	// The operation code of the part operation. 30 characters max.
	OperationCode *string `json:"operationCode,omitempty"`
	// The quantity to be produced across all batches in this job operation.
	JobOperationQuantity *float64 `json:"jobOperationQuantity,omitempty"`
	// A list of all batch component parts from the job BOM.
	BatchComponents []BatchComponentsItem `json:"batchComponents,omitempty"`
	// The due date of the batch.
	DueDate *time.Time `json:"dueDate,omitempty"`
	// The scheduled start date of the batch.
	StartDate *time.Time `json:"startDate,omitempty"`
}

// NewProductionOperationsManagementApiGetBatchResponse instantiates a new ProductionOperationsManagementApiGetBatchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductionOperationsManagementApiGetBatchResponse() *ProductionOperationsManagementApiGetBatchResponse {
	this := ProductionOperationsManagementApiGetBatchResponse{}
	return &this
}

// NewProductionOperationsManagementApiGetBatchResponseWithDefaults instantiates a new ProductionOperationsManagementApiGetBatchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductionOperationsManagementApiGetBatchResponseWithDefaults() *ProductionOperationsManagementApiGetBatchResponse {
	this := ProductionOperationsManagementApiGetBatchResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ProductionOperationsManagementApiGetBatchResponse) SetId(v string) {
	o.Id = &v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetNumber() int32 {
	if o == nil || IsNil(o.Number) {
		var ret int32
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.Number) {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) HasNumber() bool {
	if o != nil && !IsNil(o.Number) {
		return true
	}

	return false
}

// SetNumber gets a reference to the given int32 and assigns it to the Number field.
func (o *ProductionOperationsManagementApiGetBatchResponse) SetNumber(v int32) {
	o.Number = &v
}

// GetBatchStatus returns the BatchStatus field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetBatchStatus() string {
	if o == nil || IsNil(o.BatchStatus) {
		var ret string
		return ret
	}
	return *o.BatchStatus
}

// GetBatchStatusOk returns a tuple with the BatchStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetBatchStatusOk() (*string, bool) {
	if o == nil || IsNil(o.BatchStatus) {
		return nil, false
	}
	return o.BatchStatus, true
}

// HasBatchStatus returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) HasBatchStatus() bool {
	if o != nil && !IsNil(o.BatchStatus) {
		return true
	}

	return false
}

// SetBatchStatus gets a reference to the given string and assigns it to the BatchStatus field.
func (o *ProductionOperationsManagementApiGetBatchResponse) SetBatchStatus(v string) {
	o.BatchStatus = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetSize() float64 {
	if o == nil || IsNil(o.Size) {
		var ret float64
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetSizeOk() (*float64, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given float64 and assigns it to the Size field.
func (o *ProductionOperationsManagementApiGetBatchResponse) SetSize(v float64) {
	o.Size = &v
}

// GetWorkcenterId returns the WorkcenterId field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetWorkcenterId() string {
	if o == nil || IsNil(o.WorkcenterId) {
		var ret string
		return ret
	}
	return *o.WorkcenterId
}

// GetWorkcenterIdOk returns a tuple with the WorkcenterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetWorkcenterIdOk() (*string, bool) {
	if o == nil || IsNil(o.WorkcenterId) {
		return nil, false
	}
	return o.WorkcenterId, true
}

// HasWorkcenterId returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) HasWorkcenterId() bool {
	if o != nil && !IsNil(o.WorkcenterId) {
		return true
	}

	return false
}

// SetWorkcenterId gets a reference to the given string and assigns it to the WorkcenterId field.
func (o *ProductionOperationsManagementApiGetBatchResponse) SetWorkcenterId(v string) {
	o.WorkcenterId = &v
}

// GetWorkcenterCode returns the WorkcenterCode field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetWorkcenterCode() string {
	if o == nil || IsNil(o.WorkcenterCode) {
		var ret string
		return ret
	}
	return *o.WorkcenterCode
}

// GetWorkcenterCodeOk returns a tuple with the WorkcenterCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetWorkcenterCodeOk() (*string, bool) {
	if o == nil || IsNil(o.WorkcenterCode) {
		return nil, false
	}
	return o.WorkcenterCode, true
}

// HasWorkcenterCode returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) HasWorkcenterCode() bool {
	if o != nil && !IsNil(o.WorkcenterCode) {
		return true
	}

	return false
}

// SetWorkcenterCode gets a reference to the given string and assigns it to the WorkcenterCode field.
func (o *ProductionOperationsManagementApiGetBatchResponse) SetWorkcenterCode(v string) {
	o.WorkcenterCode = &v
}

// GetPartId returns the PartId field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetPartId() string {
	if o == nil || IsNil(o.PartId) {
		var ret string
		return ret
	}
	return *o.PartId
}

// GetPartIdOk returns a tuple with the PartId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetPartIdOk() (*string, bool) {
	if o == nil || IsNil(o.PartId) {
		return nil, false
	}
	return o.PartId, true
}

// HasPartId returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) HasPartId() bool {
	if o != nil && !IsNil(o.PartId) {
		return true
	}

	return false
}

// SetPartId gets a reference to the given string and assigns it to the PartId field.
func (o *ProductionOperationsManagementApiGetBatchResponse) SetPartId(v string) {
	o.PartId = &v
}

// GetPartNumber returns the PartNumber field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetPartNumber() string {
	if o == nil || IsNil(o.PartNumber) {
		var ret string
		return ret
	}
	return *o.PartNumber
}

// GetPartNumberOk returns a tuple with the PartNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetPartNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PartNumber) {
		return nil, false
	}
	return o.PartNumber, true
}

// HasPartNumber returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) HasPartNumber() bool {
	if o != nil && !IsNil(o.PartNumber) {
		return true
	}

	return false
}

// SetPartNumber gets a reference to the given string and assigns it to the PartNumber field.
func (o *ProductionOperationsManagementApiGetBatchResponse) SetPartNumber(v string) {
	o.PartNumber = &v
}

// GetPartRevision returns the PartRevision field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetPartRevision() string {
	if o == nil || IsNil(o.PartRevision) {
		var ret string
		return ret
	}
	return *o.PartRevision
}

// GetPartRevisionOk returns a tuple with the PartRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetPartRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.PartRevision) {
		return nil, false
	}
	return o.PartRevision, true
}

// HasPartRevision returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) HasPartRevision() bool {
	if o != nil && !IsNil(o.PartRevision) {
		return true
	}

	return false
}

// SetPartRevision gets a reference to the given string and assigns it to the PartRevision field.
func (o *ProductionOperationsManagementApiGetBatchResponse) SetPartRevision(v string) {
	o.PartRevision = &v
}

// GetPartNumberRevision returns the PartNumberRevision field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetPartNumberRevision() string {
	if o == nil || IsNil(o.PartNumberRevision) {
		var ret string
		return ret
	}
	return *o.PartNumberRevision
}

// GetPartNumberRevisionOk returns a tuple with the PartNumberRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetPartNumberRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.PartNumberRevision) {
		return nil, false
	}
	return o.PartNumberRevision, true
}

// HasPartNumberRevision returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) HasPartNumberRevision() bool {
	if o != nil && !IsNil(o.PartNumberRevision) {
		return true
	}

	return false
}

// SetPartNumberRevision gets a reference to the given string and assigns it to the PartNumberRevision field.
func (o *ProductionOperationsManagementApiGetBatchResponse) SetPartNumberRevision(v string) {
	o.PartNumberRevision = &v
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetJobId() string {
	if o == nil || IsNil(o.JobId) {
		var ret string
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobId) {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) HasJobId() bool {
	if o != nil && !IsNil(o.JobId) {
		return true
	}

	return false
}

// SetJobId gets a reference to the given string and assigns it to the JobId field.
func (o *ProductionOperationsManagementApiGetBatchResponse) SetJobId(v string) {
	o.JobId = &v
}

// GetJobNumber returns the JobNumber field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetJobNumber() string {
	if o == nil || IsNil(o.JobNumber) {
		var ret string
		return ret
	}
	return *o.JobNumber
}

// GetJobNumberOk returns a tuple with the JobNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetJobNumberOk() (*string, bool) {
	if o == nil || IsNil(o.JobNumber) {
		return nil, false
	}
	return o.JobNumber, true
}

// HasJobNumber returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) HasJobNumber() bool {
	if o != nil && !IsNil(o.JobNumber) {
		return true
	}

	return false
}

// SetJobNumber gets a reference to the given string and assigns it to the JobNumber field.
func (o *ProductionOperationsManagementApiGetBatchResponse) SetJobNumber(v string) {
	o.JobNumber = &v
}

// GetJobStatus returns the JobStatus field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetJobStatus() string {
	if o == nil || IsNil(o.JobStatus) {
		var ret string
		return ret
	}
	return *o.JobStatus
}

// GetJobStatusOk returns a tuple with the JobStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetJobStatusOk() (*string, bool) {
	if o == nil || IsNil(o.JobStatus) {
		return nil, false
	}
	return o.JobStatus, true
}

// HasJobStatus returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) HasJobStatus() bool {
	if o != nil && !IsNil(o.JobStatus) {
		return true
	}

	return false
}

// SetJobStatus gets a reference to the given string and assigns it to the JobStatus field.
func (o *ProductionOperationsManagementApiGetBatchResponse) SetJobStatus(v string) {
	o.JobStatus = &v
}

// GetJobOperationId returns the JobOperationId field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetJobOperationId() string {
	if o == nil || IsNil(o.JobOperationId) {
		var ret string
		return ret
	}
	return *o.JobOperationId
}

// GetJobOperationIdOk returns a tuple with the JobOperationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetJobOperationIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobOperationId) {
		return nil, false
	}
	return o.JobOperationId, true
}

// HasJobOperationId returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) HasJobOperationId() bool {
	if o != nil && !IsNil(o.JobOperationId) {
		return true
	}

	return false
}

// SetJobOperationId gets a reference to the given string and assigns it to the JobOperationId field.
func (o *ProductionOperationsManagementApiGetBatchResponse) SetJobOperationId(v string) {
	o.JobOperationId = &v
}

// GetJobOperationStatus returns the JobOperationStatus field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetJobOperationStatus() string {
	if o == nil || IsNil(o.JobOperationStatus) {
		var ret string
		return ret
	}
	return *o.JobOperationStatus
}

// GetJobOperationStatusOk returns a tuple with the JobOperationStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetJobOperationStatusOk() (*string, bool) {
	if o == nil || IsNil(o.JobOperationStatus) {
		return nil, false
	}
	return o.JobOperationStatus, true
}

// HasJobOperationStatus returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) HasJobOperationStatus() bool {
	if o != nil && !IsNil(o.JobOperationStatus) {
		return true
	}

	return false
}

// SetJobOperationStatus gets a reference to the given string and assigns it to the JobOperationStatus field.
func (o *ProductionOperationsManagementApiGetBatchResponse) SetJobOperationStatus(v string) {
	o.JobOperationStatus = &v
}

// GetOperationNumber returns the OperationNumber field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetOperationNumber() float64 {
	if o == nil || IsNil(o.OperationNumber) {
		var ret float64
		return ret
	}
	return *o.OperationNumber
}

// GetOperationNumberOk returns a tuple with the OperationNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetOperationNumberOk() (*float64, bool) {
	if o == nil || IsNil(o.OperationNumber) {
		return nil, false
	}
	return o.OperationNumber, true
}

// HasOperationNumber returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) HasOperationNumber() bool {
	if o != nil && !IsNil(o.OperationNumber) {
		return true
	}

	return false
}

// SetOperationNumber gets a reference to the given float64 and assigns it to the OperationNumber field.
func (o *ProductionOperationsManagementApiGetBatchResponse) SetOperationNumber(v float64) {
	o.OperationNumber = &v
}

// GetOperationCode returns the OperationCode field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetOperationCode() string {
	if o == nil || IsNil(o.OperationCode) {
		var ret string
		return ret
	}
	return *o.OperationCode
}

// GetOperationCodeOk returns a tuple with the OperationCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetOperationCodeOk() (*string, bool) {
	if o == nil || IsNil(o.OperationCode) {
		return nil, false
	}
	return o.OperationCode, true
}

// HasOperationCode returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) HasOperationCode() bool {
	if o != nil && !IsNil(o.OperationCode) {
		return true
	}

	return false
}

// SetOperationCode gets a reference to the given string and assigns it to the OperationCode field.
func (o *ProductionOperationsManagementApiGetBatchResponse) SetOperationCode(v string) {
	o.OperationCode = &v
}

// GetJobOperationQuantity returns the JobOperationQuantity field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetJobOperationQuantity() float64 {
	if o == nil || IsNil(o.JobOperationQuantity) {
		var ret float64
		return ret
	}
	return *o.JobOperationQuantity
}

// GetJobOperationQuantityOk returns a tuple with the JobOperationQuantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetJobOperationQuantityOk() (*float64, bool) {
	if o == nil || IsNil(o.JobOperationQuantity) {
		return nil, false
	}
	return o.JobOperationQuantity, true
}

// HasJobOperationQuantity returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) HasJobOperationQuantity() bool {
	if o != nil && !IsNil(o.JobOperationQuantity) {
		return true
	}

	return false
}

// SetJobOperationQuantity gets a reference to the given float64 and assigns it to the JobOperationQuantity field.
func (o *ProductionOperationsManagementApiGetBatchResponse) SetJobOperationQuantity(v float64) {
	o.JobOperationQuantity = &v
}

// GetBatchComponents returns the BatchComponents field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetBatchComponents() []BatchComponentsItem {
	if o == nil || IsNil(o.BatchComponents) {
		var ret []BatchComponentsItem
		return ret
	}
	return o.BatchComponents
}

// GetBatchComponentsOk returns a tuple with the BatchComponents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetBatchComponentsOk() ([]BatchComponentsItem, bool) {
	if o == nil || IsNil(o.BatchComponents) {
		return nil, false
	}
	return o.BatchComponents, true
}

// HasBatchComponents returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) HasBatchComponents() bool {
	if o != nil && !IsNil(o.BatchComponents) {
		return true
	}

	return false
}

// SetBatchComponents gets a reference to the given []BatchComponentsItem and assigns it to the BatchComponents field.
func (o *ProductionOperationsManagementApiGetBatchResponse) SetBatchComponents(v []BatchComponentsItem) {
	o.BatchComponents = v
}

// GetDueDate returns the DueDate field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetDueDate() time.Time {
	if o == nil || IsNil(o.DueDate) {
		var ret time.Time
		return ret
	}
	return *o.DueDate
}

// GetDueDateOk returns a tuple with the DueDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetDueDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DueDate) {
		return nil, false
	}
	return o.DueDate, true
}

// HasDueDate returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) HasDueDate() bool {
	if o != nil && !IsNil(o.DueDate) {
		return true
	}

	return false
}

// SetDueDate gets a reference to the given time.Time and assigns it to the DueDate field.
func (o *ProductionOperationsManagementApiGetBatchResponse) SetDueDate(v time.Time) {
	o.DueDate = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetStartDate() time.Time {
	if o == nil || IsNil(o.StartDate) {
		var ret time.Time
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) GetStartDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetBatchResponse) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given time.Time and assigns it to the StartDate field.
func (o *ProductionOperationsManagementApiGetBatchResponse) SetStartDate(v time.Time) {
	o.StartDate = &v
}

func (o ProductionOperationsManagementApiGetBatchResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductionOperationsManagementApiGetBatchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Number) {
		toSerialize["number"] = o.Number
	}
	if !IsNil(o.BatchStatus) {
		toSerialize["batchStatus"] = o.BatchStatus
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.WorkcenterId) {
		toSerialize["workcenterId"] = o.WorkcenterId
	}
	if !IsNil(o.WorkcenterCode) {
		toSerialize["workcenterCode"] = o.WorkcenterCode
	}
	if !IsNil(o.PartId) {
		toSerialize["partId"] = o.PartId
	}
	if !IsNil(o.PartNumber) {
		toSerialize["partNumber"] = o.PartNumber
	}
	if !IsNil(o.PartRevision) {
		toSerialize["partRevision"] = o.PartRevision
	}
	if !IsNil(o.PartNumberRevision) {
		toSerialize["partNumberRevision"] = o.PartNumberRevision
	}
	if !IsNil(o.JobId) {
		toSerialize["jobId"] = o.JobId
	}
	if !IsNil(o.JobNumber) {
		toSerialize["jobNumber"] = o.JobNumber
	}
	if !IsNil(o.JobStatus) {
		toSerialize["jobStatus"] = o.JobStatus
	}
	if !IsNil(o.JobOperationId) {
		toSerialize["jobOperationId"] = o.JobOperationId
	}
	if !IsNil(o.JobOperationStatus) {
		toSerialize["jobOperationStatus"] = o.JobOperationStatus
	}
	if !IsNil(o.OperationNumber) {
		toSerialize["operationNumber"] = o.OperationNumber
	}
	if !IsNil(o.OperationCode) {
		toSerialize["operationCode"] = o.OperationCode
	}
	if !IsNil(o.JobOperationQuantity) {
		toSerialize["jobOperationQuantity"] = o.JobOperationQuantity
	}
	if !IsNil(o.BatchComponents) {
		toSerialize["batchComponents"] = o.BatchComponents
	}
	if !IsNil(o.DueDate) {
		toSerialize["dueDate"] = o.DueDate
	}
	if !IsNil(o.StartDate) {
		toSerialize["startDate"] = o.StartDate
	}
	return toSerialize, nil
}

type NullableProductionOperationsManagementApiGetBatchResponse struct {
	value *ProductionOperationsManagementApiGetBatchResponse
	isSet bool
}

func (v NullableProductionOperationsManagementApiGetBatchResponse) Get() *ProductionOperationsManagementApiGetBatchResponse {
	return v.value
}

func (v *NullableProductionOperationsManagementApiGetBatchResponse) Set(val *ProductionOperationsManagementApiGetBatchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProductionOperationsManagementApiGetBatchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProductionOperationsManagementApiGetBatchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductionOperationsManagementApiGetBatchResponse(val *ProductionOperationsManagementApiGetBatchResponse) *NullableProductionOperationsManagementApiGetBatchResponse {
	return &NullableProductionOperationsManagementApiGetBatchResponse{value: val, isSet: true}
}

func (v NullableProductionOperationsManagementApiGetBatchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductionOperationsManagementApiGetBatchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


