/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plex

import (
	"encoding/json"
)

// checks if the ProductionOperationsManagementApiGetLocationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductionOperationsManagementApiGetLocationResponse{}

// ProductionOperationsManagementApiGetLocationResponse A location is a physical location where a production can be run.  This could be a machine, a work cell, a work area, etc.
type ProductionOperationsManagementApiGetLocationResponse struct {
	// A unique identifier for the location.
	Id *string `json:"id,omitempty"`
	// The name of the location.
	LocationName *string `json:"locationName,omitempty"`
	// The type of location, this could be a machine, a work cell, a work area, etc.
	LocationType *string `json:"locationType,omitempty"`
	// The code of the building where the location is located.
	BuildingCode *string `json:"buildingCode,omitempty"`
	// The identifier of the building where the location is located.
	BuildingId *string `json:"buildingId,omitempty"`
}

// NewProductionOperationsManagementApiGetLocationResponse instantiates a new ProductionOperationsManagementApiGetLocationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductionOperationsManagementApiGetLocationResponse() *ProductionOperationsManagementApiGetLocationResponse {
	this := ProductionOperationsManagementApiGetLocationResponse{}
	return &this
}

// NewProductionOperationsManagementApiGetLocationResponseWithDefaults instantiates a new ProductionOperationsManagementApiGetLocationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductionOperationsManagementApiGetLocationResponseWithDefaults() *ProductionOperationsManagementApiGetLocationResponse {
	this := ProductionOperationsManagementApiGetLocationResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetLocationResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetLocationResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetLocationResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ProductionOperationsManagementApiGetLocationResponse) SetId(v string) {
	o.Id = &v
}

// GetLocationName returns the LocationName field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetLocationResponse) GetLocationName() string {
	if o == nil || IsNil(o.LocationName) {
		var ret string
		return ret
	}
	return *o.LocationName
}

// GetLocationNameOk returns a tuple with the LocationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetLocationResponse) GetLocationNameOk() (*string, bool) {
	if o == nil || IsNil(o.LocationName) {
		return nil, false
	}
	return o.LocationName, true
}

// HasLocationName returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetLocationResponse) HasLocationName() bool {
	if o != nil && !IsNil(o.LocationName) {
		return true
	}

	return false
}

// SetLocationName gets a reference to the given string and assigns it to the LocationName field.
func (o *ProductionOperationsManagementApiGetLocationResponse) SetLocationName(v string) {
	o.LocationName = &v
}

// GetLocationType returns the LocationType field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetLocationResponse) GetLocationType() string {
	if o == nil || IsNil(o.LocationType) {
		var ret string
		return ret
	}
	return *o.LocationType
}

// GetLocationTypeOk returns a tuple with the LocationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetLocationResponse) GetLocationTypeOk() (*string, bool) {
	if o == nil || IsNil(o.LocationType) {
		return nil, false
	}
	return o.LocationType, true
}

// HasLocationType returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetLocationResponse) HasLocationType() bool {
	if o != nil && !IsNil(o.LocationType) {
		return true
	}

	return false
}

// SetLocationType gets a reference to the given string and assigns it to the LocationType field.
func (o *ProductionOperationsManagementApiGetLocationResponse) SetLocationType(v string) {
	o.LocationType = &v
}

// GetBuildingCode returns the BuildingCode field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetLocationResponse) GetBuildingCode() string {
	if o == nil || IsNil(o.BuildingCode) {
		var ret string
		return ret
	}
	return *o.BuildingCode
}

// GetBuildingCodeOk returns a tuple with the BuildingCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetLocationResponse) GetBuildingCodeOk() (*string, bool) {
	if o == nil || IsNil(o.BuildingCode) {
		return nil, false
	}
	return o.BuildingCode, true
}

// HasBuildingCode returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetLocationResponse) HasBuildingCode() bool {
	if o != nil && !IsNil(o.BuildingCode) {
		return true
	}

	return false
}

// SetBuildingCode gets a reference to the given string and assigns it to the BuildingCode field.
func (o *ProductionOperationsManagementApiGetLocationResponse) SetBuildingCode(v string) {
	o.BuildingCode = &v
}

// GetBuildingId returns the BuildingId field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiGetLocationResponse) GetBuildingId() string {
	if o == nil || IsNil(o.BuildingId) {
		var ret string
		return ret
	}
	return *o.BuildingId
}

// GetBuildingIdOk returns a tuple with the BuildingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiGetLocationResponse) GetBuildingIdOk() (*string, bool) {
	if o == nil || IsNil(o.BuildingId) {
		return nil, false
	}
	return o.BuildingId, true
}

// HasBuildingId returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiGetLocationResponse) HasBuildingId() bool {
	if o != nil && !IsNil(o.BuildingId) {
		return true
	}

	return false
}

// SetBuildingId gets a reference to the given string and assigns it to the BuildingId field.
func (o *ProductionOperationsManagementApiGetLocationResponse) SetBuildingId(v string) {
	o.BuildingId = &v
}

func (o ProductionOperationsManagementApiGetLocationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductionOperationsManagementApiGetLocationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.LocationName) {
		toSerialize["locationName"] = o.LocationName
	}
	if !IsNil(o.LocationType) {
		toSerialize["locationType"] = o.LocationType
	}
	if !IsNil(o.BuildingCode) {
		toSerialize["buildingCode"] = o.BuildingCode
	}
	if !IsNil(o.BuildingId) {
		toSerialize["buildingId"] = o.BuildingId
	}
	return toSerialize, nil
}

type NullableProductionOperationsManagementApiGetLocationResponse struct {
	value *ProductionOperationsManagementApiGetLocationResponse
	isSet bool
}

func (v NullableProductionOperationsManagementApiGetLocationResponse) Get() *ProductionOperationsManagementApiGetLocationResponse {
	return v.value
}

func (v *NullableProductionOperationsManagementApiGetLocationResponse) Set(val *ProductionOperationsManagementApiGetLocationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProductionOperationsManagementApiGetLocationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProductionOperationsManagementApiGetLocationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductionOperationsManagementApiGetLocationResponse(val *ProductionOperationsManagementApiGetLocationResponse) *NullableProductionOperationsManagementApiGetLocationResponse {
	return &NullableProductionOperationsManagementApiGetLocationResponse{value: val, isSet: true}
}

func (v NullableProductionOperationsManagementApiGetLocationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductionOperationsManagementApiGetLocationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


