/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plex

import (
	"encoding/json"
)

// checks if the LinesItem5 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LinesItem5{}

// LinesItem5 The Accounts Receivable Invoice Line model.
type LinesItem5 struct {
	// The distribution line ID.
	LineId *string `json:"lineId,omitempty"`
	// The AR invoice line account number.
	AccountNumber *string `json:"accountNumber,omitempty"`
	// A unique identifier for the AR invoice line account.
	AccountId *string `json:"accountId,omitempty"`
	// The AR invoice line base account segment.
	BaseSegment *string `json:"baseSegment,omitempty"`
	// The AR invoice line account cost center segment.
	CostCenterSegment *string `json:"costCenterSegment,omitempty"`
	// The AR invoice line account location segment.
	SubAccountSegment *string `json:"subAccountSegment,omitempty"`
	// A description of the AR invoice line.
	Description *string `json:"description,omitempty"`
	// The AR invoice distribution line is calculated as a credit.
	Credit *float64 `json:"credit,omitempty"`
	// The AR invoice distribution line is calculated as a debit.
	Debit *float64 `json:"debit,omitempty"`
	// The AR invoice distribution line amount is a foreign currency credit.
	CurrencyCredit *float64 `json:"currencyCredit,omitempty"`
	// The AR invoice distribution line amount is a foreign currency debit.
	CurrencyDebit *float64 `json:"currencyDebit,omitempty"`
	// The AR invoice line unit price.
	UnitPrice *float64 `json:"unitPrice,omitempty"`
	// The AR invoice line quantity.
	Quantity *float64 `json:"quantity,omitempty"`
	// The accounting job that the AR invoice line is a part of if applicable.
	AccountingJobNumber *string `json:"accountingJobNumber,omitempty"`
	// The AR invoice line reference number.
	ReferenceNo *string `json:"referenceNo,omitempty"`
	// The AR invoice item tax code.
	ItemTaxCode *string `json:"itemTaxCode,omitempty"`
	// The AR invoice line voucher description.
	VoucherDescription *string `json:"voucherDescription,omitempty"`
	// The AR invoice line customer order number.
	CustomerOrderNo *string `json:"customerOrderNo,omitempty"`
	// The AR invoice line purchase order ID.
	PoId *string `json:"poId,omitempty"`
	// The AR invoice line purchase order line ID.
	PoLineId *string `json:"poLineId,omitempty"`
	// The AR invoice line shipper number.
	ShipperNo *string `json:"shipperNo,omitempty"`
	// The AR invoice line shipper line ID.
	ShipperLineId *string `json:"shipperLineId,omitempty"`
	// The AR invoice line shipper ID.
	ShipperId *string `json:"shipperId,omitempty"`
	// The AR invoice line unit of measure.
	UoM *string `json:"uoM,omitempty"`
	// The AR invoice line end unit number.
	EndUnitNumber *string `json:"endUnitNumber,omitempty"`
	// The AR invoice line offset.
	Offset *int32 `json:"offset,omitempty"`
	// The AR invoice line part ID.
	PartId *string `json:"partId,omitempty"`
	// The AR invoice line part number.
	PartNo *string `json:"partNo,omitempty"`
	// The list of AR taxes.
	Taxes []TaxesItem1 `json:"taxes,omitempty"`
}

// NewLinesItem5 instantiates a new LinesItem5 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinesItem5() *LinesItem5 {
	this := LinesItem5{}
	return &this
}

// NewLinesItem5WithDefaults instantiates a new LinesItem5 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinesItem5WithDefaults() *LinesItem5 {
	this := LinesItem5{}
	return &this
}

// GetLineId returns the LineId field value if set, zero value otherwise.
func (o *LinesItem5) GetLineId() string {
	if o == nil || IsNil(o.LineId) {
		var ret string
		return ret
	}
	return *o.LineId
}

// GetLineIdOk returns a tuple with the LineId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetLineIdOk() (*string, bool) {
	if o == nil || IsNil(o.LineId) {
		return nil, false
	}
	return o.LineId, true
}

// HasLineId returns a boolean if a field has been set.
func (o *LinesItem5) HasLineId() bool {
	if o != nil && !IsNil(o.LineId) {
		return true
	}

	return false
}

// SetLineId gets a reference to the given string and assigns it to the LineId field.
func (o *LinesItem5) SetLineId(v string) {
	o.LineId = &v
}

// GetAccountNumber returns the AccountNumber field value if set, zero value otherwise.
func (o *LinesItem5) GetAccountNumber() string {
	if o == nil || IsNil(o.AccountNumber) {
		var ret string
		return ret
	}
	return *o.AccountNumber
}

// GetAccountNumberOk returns a tuple with the AccountNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetAccountNumberOk() (*string, bool) {
	if o == nil || IsNil(o.AccountNumber) {
		return nil, false
	}
	return o.AccountNumber, true
}

// HasAccountNumber returns a boolean if a field has been set.
func (o *LinesItem5) HasAccountNumber() bool {
	if o != nil && !IsNil(o.AccountNumber) {
		return true
	}

	return false
}

// SetAccountNumber gets a reference to the given string and assigns it to the AccountNumber field.
func (o *LinesItem5) SetAccountNumber(v string) {
	o.AccountNumber = &v
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *LinesItem5) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *LinesItem5) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *LinesItem5) SetAccountId(v string) {
	o.AccountId = &v
}

// GetBaseSegment returns the BaseSegment field value if set, zero value otherwise.
func (o *LinesItem5) GetBaseSegment() string {
	if o == nil || IsNil(o.BaseSegment) {
		var ret string
		return ret
	}
	return *o.BaseSegment
}

// GetBaseSegmentOk returns a tuple with the BaseSegment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetBaseSegmentOk() (*string, bool) {
	if o == nil || IsNil(o.BaseSegment) {
		return nil, false
	}
	return o.BaseSegment, true
}

// HasBaseSegment returns a boolean if a field has been set.
func (o *LinesItem5) HasBaseSegment() bool {
	if o != nil && !IsNil(o.BaseSegment) {
		return true
	}

	return false
}

// SetBaseSegment gets a reference to the given string and assigns it to the BaseSegment field.
func (o *LinesItem5) SetBaseSegment(v string) {
	o.BaseSegment = &v
}

// GetCostCenterSegment returns the CostCenterSegment field value if set, zero value otherwise.
func (o *LinesItem5) GetCostCenterSegment() string {
	if o == nil || IsNil(o.CostCenterSegment) {
		var ret string
		return ret
	}
	return *o.CostCenterSegment
}

// GetCostCenterSegmentOk returns a tuple with the CostCenterSegment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetCostCenterSegmentOk() (*string, bool) {
	if o == nil || IsNil(o.CostCenterSegment) {
		return nil, false
	}
	return o.CostCenterSegment, true
}

// HasCostCenterSegment returns a boolean if a field has been set.
func (o *LinesItem5) HasCostCenterSegment() bool {
	if o != nil && !IsNil(o.CostCenterSegment) {
		return true
	}

	return false
}

// SetCostCenterSegment gets a reference to the given string and assigns it to the CostCenterSegment field.
func (o *LinesItem5) SetCostCenterSegment(v string) {
	o.CostCenterSegment = &v
}

// GetSubAccountSegment returns the SubAccountSegment field value if set, zero value otherwise.
func (o *LinesItem5) GetSubAccountSegment() string {
	if o == nil || IsNil(o.SubAccountSegment) {
		var ret string
		return ret
	}
	return *o.SubAccountSegment
}

// GetSubAccountSegmentOk returns a tuple with the SubAccountSegment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetSubAccountSegmentOk() (*string, bool) {
	if o == nil || IsNil(o.SubAccountSegment) {
		return nil, false
	}
	return o.SubAccountSegment, true
}

// HasSubAccountSegment returns a boolean if a field has been set.
func (o *LinesItem5) HasSubAccountSegment() bool {
	if o != nil && !IsNil(o.SubAccountSegment) {
		return true
	}

	return false
}

// SetSubAccountSegment gets a reference to the given string and assigns it to the SubAccountSegment field.
func (o *LinesItem5) SetSubAccountSegment(v string) {
	o.SubAccountSegment = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *LinesItem5) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *LinesItem5) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *LinesItem5) SetDescription(v string) {
	o.Description = &v
}

// GetCredit returns the Credit field value if set, zero value otherwise.
func (o *LinesItem5) GetCredit() float64 {
	if o == nil || IsNil(o.Credit) {
		var ret float64
		return ret
	}
	return *o.Credit
}

// GetCreditOk returns a tuple with the Credit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetCreditOk() (*float64, bool) {
	if o == nil || IsNil(o.Credit) {
		return nil, false
	}
	return o.Credit, true
}

// HasCredit returns a boolean if a field has been set.
func (o *LinesItem5) HasCredit() bool {
	if o != nil && !IsNil(o.Credit) {
		return true
	}

	return false
}

// SetCredit gets a reference to the given float64 and assigns it to the Credit field.
func (o *LinesItem5) SetCredit(v float64) {
	o.Credit = &v
}

// GetDebit returns the Debit field value if set, zero value otherwise.
func (o *LinesItem5) GetDebit() float64 {
	if o == nil || IsNil(o.Debit) {
		var ret float64
		return ret
	}
	return *o.Debit
}

// GetDebitOk returns a tuple with the Debit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetDebitOk() (*float64, bool) {
	if o == nil || IsNil(o.Debit) {
		return nil, false
	}
	return o.Debit, true
}

// HasDebit returns a boolean if a field has been set.
func (o *LinesItem5) HasDebit() bool {
	if o != nil && !IsNil(o.Debit) {
		return true
	}

	return false
}

// SetDebit gets a reference to the given float64 and assigns it to the Debit field.
func (o *LinesItem5) SetDebit(v float64) {
	o.Debit = &v
}

// GetCurrencyCredit returns the CurrencyCredit field value if set, zero value otherwise.
func (o *LinesItem5) GetCurrencyCredit() float64 {
	if o == nil || IsNil(o.CurrencyCredit) {
		var ret float64
		return ret
	}
	return *o.CurrencyCredit
}

// GetCurrencyCreditOk returns a tuple with the CurrencyCredit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetCurrencyCreditOk() (*float64, bool) {
	if o == nil || IsNil(o.CurrencyCredit) {
		return nil, false
	}
	return o.CurrencyCredit, true
}

// HasCurrencyCredit returns a boolean if a field has been set.
func (o *LinesItem5) HasCurrencyCredit() bool {
	if o != nil && !IsNil(o.CurrencyCredit) {
		return true
	}

	return false
}

// SetCurrencyCredit gets a reference to the given float64 and assigns it to the CurrencyCredit field.
func (o *LinesItem5) SetCurrencyCredit(v float64) {
	o.CurrencyCredit = &v
}

// GetCurrencyDebit returns the CurrencyDebit field value if set, zero value otherwise.
func (o *LinesItem5) GetCurrencyDebit() float64 {
	if o == nil || IsNil(o.CurrencyDebit) {
		var ret float64
		return ret
	}
	return *o.CurrencyDebit
}

// GetCurrencyDebitOk returns a tuple with the CurrencyDebit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetCurrencyDebitOk() (*float64, bool) {
	if o == nil || IsNil(o.CurrencyDebit) {
		return nil, false
	}
	return o.CurrencyDebit, true
}

// HasCurrencyDebit returns a boolean if a field has been set.
func (o *LinesItem5) HasCurrencyDebit() bool {
	if o != nil && !IsNil(o.CurrencyDebit) {
		return true
	}

	return false
}

// SetCurrencyDebit gets a reference to the given float64 and assigns it to the CurrencyDebit field.
func (o *LinesItem5) SetCurrencyDebit(v float64) {
	o.CurrencyDebit = &v
}

// GetUnitPrice returns the UnitPrice field value if set, zero value otherwise.
func (o *LinesItem5) GetUnitPrice() float64 {
	if o == nil || IsNil(o.UnitPrice) {
		var ret float64
		return ret
	}
	return *o.UnitPrice
}

// GetUnitPriceOk returns a tuple with the UnitPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetUnitPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.UnitPrice) {
		return nil, false
	}
	return o.UnitPrice, true
}

// HasUnitPrice returns a boolean if a field has been set.
func (o *LinesItem5) HasUnitPrice() bool {
	if o != nil && !IsNil(o.UnitPrice) {
		return true
	}

	return false
}

// SetUnitPrice gets a reference to the given float64 and assigns it to the UnitPrice field.
func (o *LinesItem5) SetUnitPrice(v float64) {
	o.UnitPrice = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *LinesItem5) GetQuantity() float64 {
	if o == nil || IsNil(o.Quantity) {
		var ret float64
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetQuantityOk() (*float64, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *LinesItem5) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given float64 and assigns it to the Quantity field.
func (o *LinesItem5) SetQuantity(v float64) {
	o.Quantity = &v
}

// GetAccountingJobNumber returns the AccountingJobNumber field value if set, zero value otherwise.
func (o *LinesItem5) GetAccountingJobNumber() string {
	if o == nil || IsNil(o.AccountingJobNumber) {
		var ret string
		return ret
	}
	return *o.AccountingJobNumber
}

// GetAccountingJobNumberOk returns a tuple with the AccountingJobNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetAccountingJobNumberOk() (*string, bool) {
	if o == nil || IsNil(o.AccountingJobNumber) {
		return nil, false
	}
	return o.AccountingJobNumber, true
}

// HasAccountingJobNumber returns a boolean if a field has been set.
func (o *LinesItem5) HasAccountingJobNumber() bool {
	if o != nil && !IsNil(o.AccountingJobNumber) {
		return true
	}

	return false
}

// SetAccountingJobNumber gets a reference to the given string and assigns it to the AccountingJobNumber field.
func (o *LinesItem5) SetAccountingJobNumber(v string) {
	o.AccountingJobNumber = &v
}

// GetReferenceNo returns the ReferenceNo field value if set, zero value otherwise.
func (o *LinesItem5) GetReferenceNo() string {
	if o == nil || IsNil(o.ReferenceNo) {
		var ret string
		return ret
	}
	return *o.ReferenceNo
}

// GetReferenceNoOk returns a tuple with the ReferenceNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetReferenceNoOk() (*string, bool) {
	if o == nil || IsNil(o.ReferenceNo) {
		return nil, false
	}
	return o.ReferenceNo, true
}

// HasReferenceNo returns a boolean if a field has been set.
func (o *LinesItem5) HasReferenceNo() bool {
	if o != nil && !IsNil(o.ReferenceNo) {
		return true
	}

	return false
}

// SetReferenceNo gets a reference to the given string and assigns it to the ReferenceNo field.
func (o *LinesItem5) SetReferenceNo(v string) {
	o.ReferenceNo = &v
}

// GetItemTaxCode returns the ItemTaxCode field value if set, zero value otherwise.
func (o *LinesItem5) GetItemTaxCode() string {
	if o == nil || IsNil(o.ItemTaxCode) {
		var ret string
		return ret
	}
	return *o.ItemTaxCode
}

// GetItemTaxCodeOk returns a tuple with the ItemTaxCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetItemTaxCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ItemTaxCode) {
		return nil, false
	}
	return o.ItemTaxCode, true
}

// HasItemTaxCode returns a boolean if a field has been set.
func (o *LinesItem5) HasItemTaxCode() bool {
	if o != nil && !IsNil(o.ItemTaxCode) {
		return true
	}

	return false
}

// SetItemTaxCode gets a reference to the given string and assigns it to the ItemTaxCode field.
func (o *LinesItem5) SetItemTaxCode(v string) {
	o.ItemTaxCode = &v
}

// GetVoucherDescription returns the VoucherDescription field value if set, zero value otherwise.
func (o *LinesItem5) GetVoucherDescription() string {
	if o == nil || IsNil(o.VoucherDescription) {
		var ret string
		return ret
	}
	return *o.VoucherDescription
}

// GetVoucherDescriptionOk returns a tuple with the VoucherDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetVoucherDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.VoucherDescription) {
		return nil, false
	}
	return o.VoucherDescription, true
}

// HasVoucherDescription returns a boolean if a field has been set.
func (o *LinesItem5) HasVoucherDescription() bool {
	if o != nil && !IsNil(o.VoucherDescription) {
		return true
	}

	return false
}

// SetVoucherDescription gets a reference to the given string and assigns it to the VoucherDescription field.
func (o *LinesItem5) SetVoucherDescription(v string) {
	o.VoucherDescription = &v
}

// GetCustomerOrderNo returns the CustomerOrderNo field value if set, zero value otherwise.
func (o *LinesItem5) GetCustomerOrderNo() string {
	if o == nil || IsNil(o.CustomerOrderNo) {
		var ret string
		return ret
	}
	return *o.CustomerOrderNo
}

// GetCustomerOrderNoOk returns a tuple with the CustomerOrderNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetCustomerOrderNoOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerOrderNo) {
		return nil, false
	}
	return o.CustomerOrderNo, true
}

// HasCustomerOrderNo returns a boolean if a field has been set.
func (o *LinesItem5) HasCustomerOrderNo() bool {
	if o != nil && !IsNil(o.CustomerOrderNo) {
		return true
	}

	return false
}

// SetCustomerOrderNo gets a reference to the given string and assigns it to the CustomerOrderNo field.
func (o *LinesItem5) SetCustomerOrderNo(v string) {
	o.CustomerOrderNo = &v
}

// GetPoId returns the PoId field value if set, zero value otherwise.
func (o *LinesItem5) GetPoId() string {
	if o == nil || IsNil(o.PoId) {
		var ret string
		return ret
	}
	return *o.PoId
}

// GetPoIdOk returns a tuple with the PoId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetPoIdOk() (*string, bool) {
	if o == nil || IsNil(o.PoId) {
		return nil, false
	}
	return o.PoId, true
}

// HasPoId returns a boolean if a field has been set.
func (o *LinesItem5) HasPoId() bool {
	if o != nil && !IsNil(o.PoId) {
		return true
	}

	return false
}

// SetPoId gets a reference to the given string and assigns it to the PoId field.
func (o *LinesItem5) SetPoId(v string) {
	o.PoId = &v
}

// GetPoLineId returns the PoLineId field value if set, zero value otherwise.
func (o *LinesItem5) GetPoLineId() string {
	if o == nil || IsNil(o.PoLineId) {
		var ret string
		return ret
	}
	return *o.PoLineId
}

// GetPoLineIdOk returns a tuple with the PoLineId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetPoLineIdOk() (*string, bool) {
	if o == nil || IsNil(o.PoLineId) {
		return nil, false
	}
	return o.PoLineId, true
}

// HasPoLineId returns a boolean if a field has been set.
func (o *LinesItem5) HasPoLineId() bool {
	if o != nil && !IsNil(o.PoLineId) {
		return true
	}

	return false
}

// SetPoLineId gets a reference to the given string and assigns it to the PoLineId field.
func (o *LinesItem5) SetPoLineId(v string) {
	o.PoLineId = &v
}

// GetShipperNo returns the ShipperNo field value if set, zero value otherwise.
func (o *LinesItem5) GetShipperNo() string {
	if o == nil || IsNil(o.ShipperNo) {
		var ret string
		return ret
	}
	return *o.ShipperNo
}

// GetShipperNoOk returns a tuple with the ShipperNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetShipperNoOk() (*string, bool) {
	if o == nil || IsNil(o.ShipperNo) {
		return nil, false
	}
	return o.ShipperNo, true
}

// HasShipperNo returns a boolean if a field has been set.
func (o *LinesItem5) HasShipperNo() bool {
	if o != nil && !IsNil(o.ShipperNo) {
		return true
	}

	return false
}

// SetShipperNo gets a reference to the given string and assigns it to the ShipperNo field.
func (o *LinesItem5) SetShipperNo(v string) {
	o.ShipperNo = &v
}

// GetShipperLineId returns the ShipperLineId field value if set, zero value otherwise.
func (o *LinesItem5) GetShipperLineId() string {
	if o == nil || IsNil(o.ShipperLineId) {
		var ret string
		return ret
	}
	return *o.ShipperLineId
}

// GetShipperLineIdOk returns a tuple with the ShipperLineId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetShipperLineIdOk() (*string, bool) {
	if o == nil || IsNil(o.ShipperLineId) {
		return nil, false
	}
	return o.ShipperLineId, true
}

// HasShipperLineId returns a boolean if a field has been set.
func (o *LinesItem5) HasShipperLineId() bool {
	if o != nil && !IsNil(o.ShipperLineId) {
		return true
	}

	return false
}

// SetShipperLineId gets a reference to the given string and assigns it to the ShipperLineId field.
func (o *LinesItem5) SetShipperLineId(v string) {
	o.ShipperLineId = &v
}

// GetShipperId returns the ShipperId field value if set, zero value otherwise.
func (o *LinesItem5) GetShipperId() string {
	if o == nil || IsNil(o.ShipperId) {
		var ret string
		return ret
	}
	return *o.ShipperId
}

// GetShipperIdOk returns a tuple with the ShipperId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetShipperIdOk() (*string, bool) {
	if o == nil || IsNil(o.ShipperId) {
		return nil, false
	}
	return o.ShipperId, true
}

// HasShipperId returns a boolean if a field has been set.
func (o *LinesItem5) HasShipperId() bool {
	if o != nil && !IsNil(o.ShipperId) {
		return true
	}

	return false
}

// SetShipperId gets a reference to the given string and assigns it to the ShipperId field.
func (o *LinesItem5) SetShipperId(v string) {
	o.ShipperId = &v
}

// GetUoM returns the UoM field value if set, zero value otherwise.
func (o *LinesItem5) GetUoM() string {
	if o == nil || IsNil(o.UoM) {
		var ret string
		return ret
	}
	return *o.UoM
}

// GetUoMOk returns a tuple with the UoM field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetUoMOk() (*string, bool) {
	if o == nil || IsNil(o.UoM) {
		return nil, false
	}
	return o.UoM, true
}

// HasUoM returns a boolean if a field has been set.
func (o *LinesItem5) HasUoM() bool {
	if o != nil && !IsNil(o.UoM) {
		return true
	}

	return false
}

// SetUoM gets a reference to the given string and assigns it to the UoM field.
func (o *LinesItem5) SetUoM(v string) {
	o.UoM = &v
}

// GetEndUnitNumber returns the EndUnitNumber field value if set, zero value otherwise.
func (o *LinesItem5) GetEndUnitNumber() string {
	if o == nil || IsNil(o.EndUnitNumber) {
		var ret string
		return ret
	}
	return *o.EndUnitNumber
}

// GetEndUnitNumberOk returns a tuple with the EndUnitNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetEndUnitNumberOk() (*string, bool) {
	if o == nil || IsNil(o.EndUnitNumber) {
		return nil, false
	}
	return o.EndUnitNumber, true
}

// HasEndUnitNumber returns a boolean if a field has been set.
func (o *LinesItem5) HasEndUnitNumber() bool {
	if o != nil && !IsNil(o.EndUnitNumber) {
		return true
	}

	return false
}

// SetEndUnitNumber gets a reference to the given string and assigns it to the EndUnitNumber field.
func (o *LinesItem5) SetEndUnitNumber(v string) {
	o.EndUnitNumber = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *LinesItem5) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *LinesItem5) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *LinesItem5) SetOffset(v int32) {
	o.Offset = &v
}

// GetPartId returns the PartId field value if set, zero value otherwise.
func (o *LinesItem5) GetPartId() string {
	if o == nil || IsNil(o.PartId) {
		var ret string
		return ret
	}
	return *o.PartId
}

// GetPartIdOk returns a tuple with the PartId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetPartIdOk() (*string, bool) {
	if o == nil || IsNil(o.PartId) {
		return nil, false
	}
	return o.PartId, true
}

// HasPartId returns a boolean if a field has been set.
func (o *LinesItem5) HasPartId() bool {
	if o != nil && !IsNil(o.PartId) {
		return true
	}

	return false
}

// SetPartId gets a reference to the given string and assigns it to the PartId field.
func (o *LinesItem5) SetPartId(v string) {
	o.PartId = &v
}

// GetPartNo returns the PartNo field value if set, zero value otherwise.
func (o *LinesItem5) GetPartNo() string {
	if o == nil || IsNil(o.PartNo) {
		var ret string
		return ret
	}
	return *o.PartNo
}

// GetPartNoOk returns a tuple with the PartNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetPartNoOk() (*string, bool) {
	if o == nil || IsNil(o.PartNo) {
		return nil, false
	}
	return o.PartNo, true
}

// HasPartNo returns a boolean if a field has been set.
func (o *LinesItem5) HasPartNo() bool {
	if o != nil && !IsNil(o.PartNo) {
		return true
	}

	return false
}

// SetPartNo gets a reference to the given string and assigns it to the PartNo field.
func (o *LinesItem5) SetPartNo(v string) {
	o.PartNo = &v
}

// GetTaxes returns the Taxes field value if set, zero value otherwise.
func (o *LinesItem5) GetTaxes() []TaxesItem1 {
	if o == nil || IsNil(o.Taxes) {
		var ret []TaxesItem1
		return ret
	}
	return o.Taxes
}

// GetTaxesOk returns a tuple with the Taxes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinesItem5) GetTaxesOk() ([]TaxesItem1, bool) {
	if o == nil || IsNil(o.Taxes) {
		return nil, false
	}
	return o.Taxes, true
}

// HasTaxes returns a boolean if a field has been set.
func (o *LinesItem5) HasTaxes() bool {
	if o != nil && !IsNil(o.Taxes) {
		return true
	}

	return false
}

// SetTaxes gets a reference to the given []TaxesItem1 and assigns it to the Taxes field.
func (o *LinesItem5) SetTaxes(v []TaxesItem1) {
	o.Taxes = v
}

func (o LinesItem5) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LinesItem5) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LineId) {
		toSerialize["lineId"] = o.LineId
	}
	if !IsNil(o.AccountNumber) {
		toSerialize["accountNumber"] = o.AccountNumber
	}
	if !IsNil(o.AccountId) {
		toSerialize["accountId"] = o.AccountId
	}
	if !IsNil(o.BaseSegment) {
		toSerialize["baseSegment"] = o.BaseSegment
	}
	if !IsNil(o.CostCenterSegment) {
		toSerialize["costCenterSegment"] = o.CostCenterSegment
	}
	if !IsNil(o.SubAccountSegment) {
		toSerialize["subAccountSegment"] = o.SubAccountSegment
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Credit) {
		toSerialize["credit"] = o.Credit
	}
	if !IsNil(o.Debit) {
		toSerialize["debit"] = o.Debit
	}
	if !IsNil(o.CurrencyCredit) {
		toSerialize["currencyCredit"] = o.CurrencyCredit
	}
	if !IsNil(o.CurrencyDebit) {
		toSerialize["currencyDebit"] = o.CurrencyDebit
	}
	if !IsNil(o.UnitPrice) {
		toSerialize["unitPrice"] = o.UnitPrice
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.AccountingJobNumber) {
		toSerialize["accountingJobNumber"] = o.AccountingJobNumber
	}
	if !IsNil(o.ReferenceNo) {
		toSerialize["referenceNo"] = o.ReferenceNo
	}
	if !IsNil(o.ItemTaxCode) {
		toSerialize["itemTaxCode"] = o.ItemTaxCode
	}
	if !IsNil(o.VoucherDescription) {
		toSerialize["voucherDescription"] = o.VoucherDescription
	}
	if !IsNil(o.CustomerOrderNo) {
		toSerialize["customerOrderNo"] = o.CustomerOrderNo
	}
	if !IsNil(o.PoId) {
		toSerialize["poId"] = o.PoId
	}
	if !IsNil(o.PoLineId) {
		toSerialize["poLineId"] = o.PoLineId
	}
	if !IsNil(o.ShipperNo) {
		toSerialize["shipperNo"] = o.ShipperNo
	}
	if !IsNil(o.ShipperLineId) {
		toSerialize["shipperLineId"] = o.ShipperLineId
	}
	if !IsNil(o.ShipperId) {
		toSerialize["shipperId"] = o.ShipperId
	}
	if !IsNil(o.UoM) {
		toSerialize["uoM"] = o.UoM
	}
	if !IsNil(o.EndUnitNumber) {
		toSerialize["endUnitNumber"] = o.EndUnitNumber
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.PartId) {
		toSerialize["partId"] = o.PartId
	}
	if !IsNil(o.PartNo) {
		toSerialize["partNo"] = o.PartNo
	}
	if !IsNil(o.Taxes) {
		toSerialize["taxes"] = o.Taxes
	}
	return toSerialize, nil
}

type NullableLinesItem5 struct {
	value *LinesItem5
	isSet bool
}

func (v NullableLinesItem5) Get() *LinesItem5 {
	return v.value
}

func (v *NullableLinesItem5) Set(val *LinesItem5) {
	v.value = val
	v.isSet = true
}

func (v NullableLinesItem5) IsSet() bool {
	return v.isSet
}

func (v *NullableLinesItem5) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinesItem5(val *LinesItem5) *NullableLinesItem5 {
	return &NullableLinesItem5{value: val, isSet: true}
}

func (v NullableLinesItem5) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinesItem5) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


