/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plex

import (
	"encoding/json"
)

// checks if the InventoryOperationsManagementApiCreateInventoryReceipt201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InventoryOperationsManagementApiCreateInventoryReceipt201Response{}

// InventoryOperationsManagementApiCreateInventoryReceipt201Response The Inventory Receipt.
type InventoryOperationsManagementApiCreateInventoryReceipt201Response struct {
	// The ID of the inventory receipt.
	Id *string `json:"id,omitempty"`
	// The Tracking Number for the Inventory Receipt.
	ExternalReceiptCode *string `json:"externalReceiptCode,omitempty"`
	// List of received containers associated to the receipt.
	ReceivedContainers []ReceivedContainersItem `json:"receivedContainers,omitempty"`
	// The ID of the supplier.
	SupplierId *string `json:"supplierId,omitempty"`
	// The supplier code of the supplier. 25 characters max.
	SupplierCode *string `json:"supplierCode,omitempty"`
}

// NewInventoryOperationsManagementApiCreateInventoryReceipt201Response instantiates a new InventoryOperationsManagementApiCreateInventoryReceipt201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInventoryOperationsManagementApiCreateInventoryReceipt201Response() *InventoryOperationsManagementApiCreateInventoryReceipt201Response {
	this := InventoryOperationsManagementApiCreateInventoryReceipt201Response{}
	return &this
}

// NewInventoryOperationsManagementApiCreateInventoryReceipt201ResponseWithDefaults instantiates a new InventoryOperationsManagementApiCreateInventoryReceipt201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInventoryOperationsManagementApiCreateInventoryReceipt201ResponseWithDefaults() *InventoryOperationsManagementApiCreateInventoryReceipt201Response {
	this := InventoryOperationsManagementApiCreateInventoryReceipt201Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InventoryOperationsManagementApiCreateInventoryReceipt201Response) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryOperationsManagementApiCreateInventoryReceipt201Response) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *InventoryOperationsManagementApiCreateInventoryReceipt201Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *InventoryOperationsManagementApiCreateInventoryReceipt201Response) SetId(v string) {
	o.Id = &v
}

// GetExternalReceiptCode returns the ExternalReceiptCode field value if set, zero value otherwise.
func (o *InventoryOperationsManagementApiCreateInventoryReceipt201Response) GetExternalReceiptCode() string {
	if o == nil || IsNil(o.ExternalReceiptCode) {
		var ret string
		return ret
	}
	return *o.ExternalReceiptCode
}

// GetExternalReceiptCodeOk returns a tuple with the ExternalReceiptCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryOperationsManagementApiCreateInventoryReceipt201Response) GetExternalReceiptCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalReceiptCode) {
		return nil, false
	}
	return o.ExternalReceiptCode, true
}

// HasExternalReceiptCode returns a boolean if a field has been set.
func (o *InventoryOperationsManagementApiCreateInventoryReceipt201Response) HasExternalReceiptCode() bool {
	if o != nil && !IsNil(o.ExternalReceiptCode) {
		return true
	}

	return false
}

// SetExternalReceiptCode gets a reference to the given string and assigns it to the ExternalReceiptCode field.
func (o *InventoryOperationsManagementApiCreateInventoryReceipt201Response) SetExternalReceiptCode(v string) {
	o.ExternalReceiptCode = &v
}

// GetReceivedContainers returns the ReceivedContainers field value if set, zero value otherwise.
func (o *InventoryOperationsManagementApiCreateInventoryReceipt201Response) GetReceivedContainers() []ReceivedContainersItem {
	if o == nil || IsNil(o.ReceivedContainers) {
		var ret []ReceivedContainersItem
		return ret
	}
	return o.ReceivedContainers
}

// GetReceivedContainersOk returns a tuple with the ReceivedContainers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryOperationsManagementApiCreateInventoryReceipt201Response) GetReceivedContainersOk() ([]ReceivedContainersItem, bool) {
	if o == nil || IsNil(o.ReceivedContainers) {
		return nil, false
	}
	return o.ReceivedContainers, true
}

// HasReceivedContainers returns a boolean if a field has been set.
func (o *InventoryOperationsManagementApiCreateInventoryReceipt201Response) HasReceivedContainers() bool {
	if o != nil && !IsNil(o.ReceivedContainers) {
		return true
	}

	return false
}

// SetReceivedContainers gets a reference to the given []ReceivedContainersItem and assigns it to the ReceivedContainers field.
func (o *InventoryOperationsManagementApiCreateInventoryReceipt201Response) SetReceivedContainers(v []ReceivedContainersItem) {
	o.ReceivedContainers = v
}

// GetSupplierId returns the SupplierId field value if set, zero value otherwise.
func (o *InventoryOperationsManagementApiCreateInventoryReceipt201Response) GetSupplierId() string {
	if o == nil || IsNil(o.SupplierId) {
		var ret string
		return ret
	}
	return *o.SupplierId
}

// GetSupplierIdOk returns a tuple with the SupplierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryOperationsManagementApiCreateInventoryReceipt201Response) GetSupplierIdOk() (*string, bool) {
	if o == nil || IsNil(o.SupplierId) {
		return nil, false
	}
	return o.SupplierId, true
}

// HasSupplierId returns a boolean if a field has been set.
func (o *InventoryOperationsManagementApiCreateInventoryReceipt201Response) HasSupplierId() bool {
	if o != nil && !IsNil(o.SupplierId) {
		return true
	}

	return false
}

// SetSupplierId gets a reference to the given string and assigns it to the SupplierId field.
func (o *InventoryOperationsManagementApiCreateInventoryReceipt201Response) SetSupplierId(v string) {
	o.SupplierId = &v
}

// GetSupplierCode returns the SupplierCode field value if set, zero value otherwise.
func (o *InventoryOperationsManagementApiCreateInventoryReceipt201Response) GetSupplierCode() string {
	if o == nil || IsNil(o.SupplierCode) {
		var ret string
		return ret
	}
	return *o.SupplierCode
}

// GetSupplierCodeOk returns a tuple with the SupplierCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryOperationsManagementApiCreateInventoryReceipt201Response) GetSupplierCodeOk() (*string, bool) {
	if o == nil || IsNil(o.SupplierCode) {
		return nil, false
	}
	return o.SupplierCode, true
}

// HasSupplierCode returns a boolean if a field has been set.
func (o *InventoryOperationsManagementApiCreateInventoryReceipt201Response) HasSupplierCode() bool {
	if o != nil && !IsNil(o.SupplierCode) {
		return true
	}

	return false
}

// SetSupplierCode gets a reference to the given string and assigns it to the SupplierCode field.
func (o *InventoryOperationsManagementApiCreateInventoryReceipt201Response) SetSupplierCode(v string) {
	o.SupplierCode = &v
}

func (o InventoryOperationsManagementApiCreateInventoryReceipt201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InventoryOperationsManagementApiCreateInventoryReceipt201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ExternalReceiptCode) {
		toSerialize["externalReceiptCode"] = o.ExternalReceiptCode
	}
	if !IsNil(o.ReceivedContainers) {
		toSerialize["receivedContainers"] = o.ReceivedContainers
	}
	if !IsNil(o.SupplierId) {
		toSerialize["supplierId"] = o.SupplierId
	}
	if !IsNil(o.SupplierCode) {
		toSerialize["supplierCode"] = o.SupplierCode
	}
	return toSerialize, nil
}

type NullableInventoryOperationsManagementApiCreateInventoryReceipt201Response struct {
	value *InventoryOperationsManagementApiCreateInventoryReceipt201Response
	isSet bool
}

func (v NullableInventoryOperationsManagementApiCreateInventoryReceipt201Response) Get() *InventoryOperationsManagementApiCreateInventoryReceipt201Response {
	return v.value
}

func (v *NullableInventoryOperationsManagementApiCreateInventoryReceipt201Response) Set(val *InventoryOperationsManagementApiCreateInventoryReceipt201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableInventoryOperationsManagementApiCreateInventoryReceipt201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableInventoryOperationsManagementApiCreateInventoryReceipt201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInventoryOperationsManagementApiCreateInventoryReceipt201Response(val *InventoryOperationsManagementApiCreateInventoryReceipt201Response) *NullableInventoryOperationsManagementApiCreateInventoryReceipt201Response {
	return &NullableInventoryOperationsManagementApiCreateInventoryReceipt201Response{value: val, isSet: true}
}

func (v NullableInventoryOperationsManagementApiCreateInventoryReceipt201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInventoryOperationsManagementApiCreateInventoryReceipt201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


