/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plex

import (
	"encoding/json"
)

// checks if the ProductionOperationsManagementApiCreateApprovedWorkcenter400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductionOperationsManagementApiCreateApprovedWorkcenter400Response{}

// ProductionOperationsManagementApiCreateApprovedWorkcenter400Response Data Structure to represent Approved Workcenter response model.
type ProductionOperationsManagementApiCreateApprovedWorkcenter400Response struct {
	// The ID of the workcenter.
	WorkcenterId *string `json:"workcenterId,omitempty"`
	// A short name associated to the &quot;workcenterID&quot; and a unique code to reference the workcenter. This code shows up throughout the system, primarily on the Control Panel. 50 characters max.
	WorkcenterCode *string `json:"workcenterCode,omitempty"`
	// The name associated to the &quot;workcenterID&quot;.
	WorkcenterName *string `json:"workcenterName,omitempty"`
	// The ID of the part that is produced.
	PartId *string `json:"partId,omitempty"`
	// The part number associated to the &quot;partId&quot; that is produced. Acceptable part number characters include uppercase and lowercase letters (A-Z), numbers (0-9), and special characters such as dashes (-), underscores ( _ ), and spaces. Part numbers cannot use question marks or ampersands. Other characters may cause issues.
	PartNo *string `json:"partNo,omitempty"`
	// The part revision of the &quot;partId&quot;. A revision represents a change or modification to a part or part drawing that is usually initiated through an engineering change request (ECR).
	PartRevision *string `json:"partRevision,omitempty"`
	// The part number and revision formatted with separator. If a part number has a revision, Plex will return the part number and the revision separated by the Part Rev Separator setting. A Part Rev Separator can be up to 5 characters long. Format {partNumber}{part rev separator}{revision}.
	PartNoRevision *string `json:"partNoRevision,omitempty"`
	// The ID of the part operation.
	PartOperationId *string `json:"partOperationId,omitempty"`
	// The operation associated with the Part Operation.
	OperationId *string `json:"operationId,omitempty"`
	// The operation number of the part operation.
	OperationNo *int32 `json:"operationNo,omitempty"`
	// The operation code associated to the &quot;partOperationId&quot;. 30 characters max.
	OperationCode *string `json:"operationCode,omitempty"`
	// The crew size associated with the workcenter.
	CrewSize *float64 `json:"crewSize,omitempty"`
	// The standard production rate associated with the workcenter.
	StandardProductionRate *float64 `json:"standardProductionRate,omitempty"`
	// The note associated with the workcenter.
	Note *string `json:"note,omitempty"`
	// The setup time associated with the workcenter.
	SetupTime *float64 `json:"setupTime,omitempty"`
	// The ideal rate associated with the workcenter.
	IdealRate *float64 `json:"idealRate,omitempty"`
	// The target rate associated with the workcenter.
	TargetRate *float64 `json:"targetRate,omitempty"`
	// The setup crew size associated with the workcenter.
	SetupCrewSize *float64 `json:"setupCrewSize,omitempty"`
	// The sequence rate associated with the workcenter.
	SequenceRate *float64 `json:"sequenceRate,omitempty"`
}

// NewProductionOperationsManagementApiCreateApprovedWorkcenter400Response instantiates a new ProductionOperationsManagementApiCreateApprovedWorkcenter400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductionOperationsManagementApiCreateApprovedWorkcenter400Response() *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response {
	this := ProductionOperationsManagementApiCreateApprovedWorkcenter400Response{}
	return &this
}

// NewProductionOperationsManagementApiCreateApprovedWorkcenter400ResponseWithDefaults instantiates a new ProductionOperationsManagementApiCreateApprovedWorkcenter400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductionOperationsManagementApiCreateApprovedWorkcenter400ResponseWithDefaults() *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response {
	this := ProductionOperationsManagementApiCreateApprovedWorkcenter400Response{}
	return &this
}

// GetWorkcenterId returns the WorkcenterId field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetWorkcenterId() string {
	if o == nil || IsNil(o.WorkcenterId) {
		var ret string
		return ret
	}
	return *o.WorkcenterId
}

// GetWorkcenterIdOk returns a tuple with the WorkcenterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetWorkcenterIdOk() (*string, bool) {
	if o == nil || IsNil(o.WorkcenterId) {
		return nil, false
	}
	return o.WorkcenterId, true
}

// HasWorkcenterId returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) HasWorkcenterId() bool {
	if o != nil && !IsNil(o.WorkcenterId) {
		return true
	}

	return false
}

// SetWorkcenterId gets a reference to the given string and assigns it to the WorkcenterId field.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) SetWorkcenterId(v string) {
	o.WorkcenterId = &v
}

// GetWorkcenterCode returns the WorkcenterCode field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetWorkcenterCode() string {
	if o == nil || IsNil(o.WorkcenterCode) {
		var ret string
		return ret
	}
	return *o.WorkcenterCode
}

// GetWorkcenterCodeOk returns a tuple with the WorkcenterCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetWorkcenterCodeOk() (*string, bool) {
	if o == nil || IsNil(o.WorkcenterCode) {
		return nil, false
	}
	return o.WorkcenterCode, true
}

// HasWorkcenterCode returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) HasWorkcenterCode() bool {
	if o != nil && !IsNil(o.WorkcenterCode) {
		return true
	}

	return false
}

// SetWorkcenterCode gets a reference to the given string and assigns it to the WorkcenterCode field.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) SetWorkcenterCode(v string) {
	o.WorkcenterCode = &v
}

// GetWorkcenterName returns the WorkcenterName field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetWorkcenterName() string {
	if o == nil || IsNil(o.WorkcenterName) {
		var ret string
		return ret
	}
	return *o.WorkcenterName
}

// GetWorkcenterNameOk returns a tuple with the WorkcenterName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetWorkcenterNameOk() (*string, bool) {
	if o == nil || IsNil(o.WorkcenterName) {
		return nil, false
	}
	return o.WorkcenterName, true
}

// HasWorkcenterName returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) HasWorkcenterName() bool {
	if o != nil && !IsNil(o.WorkcenterName) {
		return true
	}

	return false
}

// SetWorkcenterName gets a reference to the given string and assigns it to the WorkcenterName field.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) SetWorkcenterName(v string) {
	o.WorkcenterName = &v
}

// GetPartId returns the PartId field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetPartId() string {
	if o == nil || IsNil(o.PartId) {
		var ret string
		return ret
	}
	return *o.PartId
}

// GetPartIdOk returns a tuple with the PartId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetPartIdOk() (*string, bool) {
	if o == nil || IsNil(o.PartId) {
		return nil, false
	}
	return o.PartId, true
}

// HasPartId returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) HasPartId() bool {
	if o != nil && !IsNil(o.PartId) {
		return true
	}

	return false
}

// SetPartId gets a reference to the given string and assigns it to the PartId field.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) SetPartId(v string) {
	o.PartId = &v
}

// GetPartNo returns the PartNo field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetPartNo() string {
	if o == nil || IsNil(o.PartNo) {
		var ret string
		return ret
	}
	return *o.PartNo
}

// GetPartNoOk returns a tuple with the PartNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetPartNoOk() (*string, bool) {
	if o == nil || IsNil(o.PartNo) {
		return nil, false
	}
	return o.PartNo, true
}

// HasPartNo returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) HasPartNo() bool {
	if o != nil && !IsNil(o.PartNo) {
		return true
	}

	return false
}

// SetPartNo gets a reference to the given string and assigns it to the PartNo field.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) SetPartNo(v string) {
	o.PartNo = &v
}

// GetPartRevision returns the PartRevision field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetPartRevision() string {
	if o == nil || IsNil(o.PartRevision) {
		var ret string
		return ret
	}
	return *o.PartRevision
}

// GetPartRevisionOk returns a tuple with the PartRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetPartRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.PartRevision) {
		return nil, false
	}
	return o.PartRevision, true
}

// HasPartRevision returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) HasPartRevision() bool {
	if o != nil && !IsNil(o.PartRevision) {
		return true
	}

	return false
}

// SetPartRevision gets a reference to the given string and assigns it to the PartRevision field.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) SetPartRevision(v string) {
	o.PartRevision = &v
}

// GetPartNoRevision returns the PartNoRevision field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetPartNoRevision() string {
	if o == nil || IsNil(o.PartNoRevision) {
		var ret string
		return ret
	}
	return *o.PartNoRevision
}

// GetPartNoRevisionOk returns a tuple with the PartNoRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetPartNoRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.PartNoRevision) {
		return nil, false
	}
	return o.PartNoRevision, true
}

// HasPartNoRevision returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) HasPartNoRevision() bool {
	if o != nil && !IsNil(o.PartNoRevision) {
		return true
	}

	return false
}

// SetPartNoRevision gets a reference to the given string and assigns it to the PartNoRevision field.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) SetPartNoRevision(v string) {
	o.PartNoRevision = &v
}

// GetPartOperationId returns the PartOperationId field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetPartOperationId() string {
	if o == nil || IsNil(o.PartOperationId) {
		var ret string
		return ret
	}
	return *o.PartOperationId
}

// GetPartOperationIdOk returns a tuple with the PartOperationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetPartOperationIdOk() (*string, bool) {
	if o == nil || IsNil(o.PartOperationId) {
		return nil, false
	}
	return o.PartOperationId, true
}

// HasPartOperationId returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) HasPartOperationId() bool {
	if o != nil && !IsNil(o.PartOperationId) {
		return true
	}

	return false
}

// SetPartOperationId gets a reference to the given string and assigns it to the PartOperationId field.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) SetPartOperationId(v string) {
	o.PartOperationId = &v
}

// GetOperationId returns the OperationId field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetOperationId() string {
	if o == nil || IsNil(o.OperationId) {
		var ret string
		return ret
	}
	return *o.OperationId
}

// GetOperationIdOk returns a tuple with the OperationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetOperationIdOk() (*string, bool) {
	if o == nil || IsNil(o.OperationId) {
		return nil, false
	}
	return o.OperationId, true
}

// HasOperationId returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) HasOperationId() bool {
	if o != nil && !IsNil(o.OperationId) {
		return true
	}

	return false
}

// SetOperationId gets a reference to the given string and assigns it to the OperationId field.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) SetOperationId(v string) {
	o.OperationId = &v
}

// GetOperationNo returns the OperationNo field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetOperationNo() int32 {
	if o == nil || IsNil(o.OperationNo) {
		var ret int32
		return ret
	}
	return *o.OperationNo
}

// GetOperationNoOk returns a tuple with the OperationNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetOperationNoOk() (*int32, bool) {
	if o == nil || IsNil(o.OperationNo) {
		return nil, false
	}
	return o.OperationNo, true
}

// HasOperationNo returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) HasOperationNo() bool {
	if o != nil && !IsNil(o.OperationNo) {
		return true
	}

	return false
}

// SetOperationNo gets a reference to the given int32 and assigns it to the OperationNo field.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) SetOperationNo(v int32) {
	o.OperationNo = &v
}

// GetOperationCode returns the OperationCode field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetOperationCode() string {
	if o == nil || IsNil(o.OperationCode) {
		var ret string
		return ret
	}
	return *o.OperationCode
}

// GetOperationCodeOk returns a tuple with the OperationCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetOperationCodeOk() (*string, bool) {
	if o == nil || IsNil(o.OperationCode) {
		return nil, false
	}
	return o.OperationCode, true
}

// HasOperationCode returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) HasOperationCode() bool {
	if o != nil && !IsNil(o.OperationCode) {
		return true
	}

	return false
}

// SetOperationCode gets a reference to the given string and assigns it to the OperationCode field.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) SetOperationCode(v string) {
	o.OperationCode = &v
}

// GetCrewSize returns the CrewSize field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetCrewSize() float64 {
	if o == nil || IsNil(o.CrewSize) {
		var ret float64
		return ret
	}
	return *o.CrewSize
}

// GetCrewSizeOk returns a tuple with the CrewSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetCrewSizeOk() (*float64, bool) {
	if o == nil || IsNil(o.CrewSize) {
		return nil, false
	}
	return o.CrewSize, true
}

// HasCrewSize returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) HasCrewSize() bool {
	if o != nil && !IsNil(o.CrewSize) {
		return true
	}

	return false
}

// SetCrewSize gets a reference to the given float64 and assigns it to the CrewSize field.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) SetCrewSize(v float64) {
	o.CrewSize = &v
}

// GetStandardProductionRate returns the StandardProductionRate field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetStandardProductionRate() float64 {
	if o == nil || IsNil(o.StandardProductionRate) {
		var ret float64
		return ret
	}
	return *o.StandardProductionRate
}

// GetStandardProductionRateOk returns a tuple with the StandardProductionRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetStandardProductionRateOk() (*float64, bool) {
	if o == nil || IsNil(o.StandardProductionRate) {
		return nil, false
	}
	return o.StandardProductionRate, true
}

// HasStandardProductionRate returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) HasStandardProductionRate() bool {
	if o != nil && !IsNil(o.StandardProductionRate) {
		return true
	}

	return false
}

// SetStandardProductionRate gets a reference to the given float64 and assigns it to the StandardProductionRate field.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) SetStandardProductionRate(v float64) {
	o.StandardProductionRate = &v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetNote() string {
	if o == nil || IsNil(o.Note) {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetNoteOk() (*string, bool) {
	if o == nil || IsNil(o.Note) {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) HasNote() bool {
	if o != nil && !IsNil(o.Note) {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) SetNote(v string) {
	o.Note = &v
}

// GetSetupTime returns the SetupTime field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetSetupTime() float64 {
	if o == nil || IsNil(o.SetupTime) {
		var ret float64
		return ret
	}
	return *o.SetupTime
}

// GetSetupTimeOk returns a tuple with the SetupTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetSetupTimeOk() (*float64, bool) {
	if o == nil || IsNil(o.SetupTime) {
		return nil, false
	}
	return o.SetupTime, true
}

// HasSetupTime returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) HasSetupTime() bool {
	if o != nil && !IsNil(o.SetupTime) {
		return true
	}

	return false
}

// SetSetupTime gets a reference to the given float64 and assigns it to the SetupTime field.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) SetSetupTime(v float64) {
	o.SetupTime = &v
}

// GetIdealRate returns the IdealRate field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetIdealRate() float64 {
	if o == nil || IsNil(o.IdealRate) {
		var ret float64
		return ret
	}
	return *o.IdealRate
}

// GetIdealRateOk returns a tuple with the IdealRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetIdealRateOk() (*float64, bool) {
	if o == nil || IsNil(o.IdealRate) {
		return nil, false
	}
	return o.IdealRate, true
}

// HasIdealRate returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) HasIdealRate() bool {
	if o != nil && !IsNil(o.IdealRate) {
		return true
	}

	return false
}

// SetIdealRate gets a reference to the given float64 and assigns it to the IdealRate field.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) SetIdealRate(v float64) {
	o.IdealRate = &v
}

// GetTargetRate returns the TargetRate field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetTargetRate() float64 {
	if o == nil || IsNil(o.TargetRate) {
		var ret float64
		return ret
	}
	return *o.TargetRate
}

// GetTargetRateOk returns a tuple with the TargetRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetTargetRateOk() (*float64, bool) {
	if o == nil || IsNil(o.TargetRate) {
		return nil, false
	}
	return o.TargetRate, true
}

// HasTargetRate returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) HasTargetRate() bool {
	if o != nil && !IsNil(o.TargetRate) {
		return true
	}

	return false
}

// SetTargetRate gets a reference to the given float64 and assigns it to the TargetRate field.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) SetTargetRate(v float64) {
	o.TargetRate = &v
}

// GetSetupCrewSize returns the SetupCrewSize field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetSetupCrewSize() float64 {
	if o == nil || IsNil(o.SetupCrewSize) {
		var ret float64
		return ret
	}
	return *o.SetupCrewSize
}

// GetSetupCrewSizeOk returns a tuple with the SetupCrewSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetSetupCrewSizeOk() (*float64, bool) {
	if o == nil || IsNil(o.SetupCrewSize) {
		return nil, false
	}
	return o.SetupCrewSize, true
}

// HasSetupCrewSize returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) HasSetupCrewSize() bool {
	if o != nil && !IsNil(o.SetupCrewSize) {
		return true
	}

	return false
}

// SetSetupCrewSize gets a reference to the given float64 and assigns it to the SetupCrewSize field.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) SetSetupCrewSize(v float64) {
	o.SetupCrewSize = &v
}

// GetSequenceRate returns the SequenceRate field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetSequenceRate() float64 {
	if o == nil || IsNil(o.SequenceRate) {
		var ret float64
		return ret
	}
	return *o.SequenceRate
}

// GetSequenceRateOk returns a tuple with the SequenceRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) GetSequenceRateOk() (*float64, bool) {
	if o == nil || IsNil(o.SequenceRate) {
		return nil, false
	}
	return o.SequenceRate, true
}

// HasSequenceRate returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) HasSequenceRate() bool {
	if o != nil && !IsNil(o.SequenceRate) {
		return true
	}

	return false
}

// SetSequenceRate gets a reference to the given float64 and assigns it to the SequenceRate field.
func (o *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) SetSequenceRate(v float64) {
	o.SequenceRate = &v
}

func (o ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.WorkcenterId) {
		toSerialize["workcenterId"] = o.WorkcenterId
	}
	if !IsNil(o.WorkcenterCode) {
		toSerialize["workcenterCode"] = o.WorkcenterCode
	}
	if !IsNil(o.WorkcenterName) {
		toSerialize["workcenterName"] = o.WorkcenterName
	}
	if !IsNil(o.PartId) {
		toSerialize["partId"] = o.PartId
	}
	if !IsNil(o.PartNo) {
		toSerialize["partNo"] = o.PartNo
	}
	if !IsNil(o.PartRevision) {
		toSerialize["partRevision"] = o.PartRevision
	}
	if !IsNil(o.PartNoRevision) {
		toSerialize["partNoRevision"] = o.PartNoRevision
	}
	if !IsNil(o.PartOperationId) {
		toSerialize["partOperationId"] = o.PartOperationId
	}
	if !IsNil(o.OperationId) {
		toSerialize["operationId"] = o.OperationId
	}
	if !IsNil(o.OperationNo) {
		toSerialize["operationNo"] = o.OperationNo
	}
	if !IsNil(o.OperationCode) {
		toSerialize["operationCode"] = o.OperationCode
	}
	if !IsNil(o.CrewSize) {
		toSerialize["crewSize"] = o.CrewSize
	}
	if !IsNil(o.StandardProductionRate) {
		toSerialize["standardProductionRate"] = o.StandardProductionRate
	}
	if !IsNil(o.Note) {
		toSerialize["note"] = o.Note
	}
	if !IsNil(o.SetupTime) {
		toSerialize["setupTime"] = o.SetupTime
	}
	if !IsNil(o.IdealRate) {
		toSerialize["idealRate"] = o.IdealRate
	}
	if !IsNil(o.TargetRate) {
		toSerialize["targetRate"] = o.TargetRate
	}
	if !IsNil(o.SetupCrewSize) {
		toSerialize["setupCrewSize"] = o.SetupCrewSize
	}
	if !IsNil(o.SequenceRate) {
		toSerialize["sequenceRate"] = o.SequenceRate
	}
	return toSerialize, nil
}

type NullableProductionOperationsManagementApiCreateApprovedWorkcenter400Response struct {
	value *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response
	isSet bool
}

func (v NullableProductionOperationsManagementApiCreateApprovedWorkcenter400Response) Get() *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response {
	return v.value
}

func (v *NullableProductionOperationsManagementApiCreateApprovedWorkcenter400Response) Set(val *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableProductionOperationsManagementApiCreateApprovedWorkcenter400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableProductionOperationsManagementApiCreateApprovedWorkcenter400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductionOperationsManagementApiCreateApprovedWorkcenter400Response(val *ProductionOperationsManagementApiCreateApprovedWorkcenter400Response) *NullableProductionOperationsManagementApiCreateApprovedWorkcenter400Response {
	return &NullableProductionOperationsManagementApiCreateApprovedWorkcenter400Response{value: val, isSet: true}
}

func (v NullableProductionOperationsManagementApiCreateApprovedWorkcenter400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductionOperationsManagementApiCreateApprovedWorkcenter400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


