/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ShippingInventoryApiGetPartShippingDetailsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShippingInventoryApiGetPartShippingDetailsResponse{}

// ShippingInventoryApiGetPartShippingDetailsResponse The part model exposed for retrieving details.
type ShippingInventoryApiGetPartShippingDetailsResponse struct {
	// A unique identifier for the part.
	PartId *string `json:"partId,omitempty"`
	// The part's number.
	PartNumber *string `json:"partNumber,omitempty"`
	// The part's revision.
	PartRevision *string `json:"partRevision,omitempty"`
	// The part's number and revision number, including the revision separator.
	PartNumberRevision *string `json:"partNumberRevision,omitempty"`
	// The container type.
	ContainerType *string `json:"containerType,omitempty"`
	// The piece weight of the part.
	PartPieceWeight *float64 `json:"partPieceWeight,omitempty"`
	// The weight unit of the container.
	WeightUnit *string `json:"weightUnit,omitempty"`
	// The cube height of the container.
	CubeHeight *float64 `json:"cubeHeight,omitempty"`
	// The cube length of the container.
	CubeLength *float64 `json:"cubeLength,omitempty"`
	// The cube width of the container.
	CubeWidth *float64 `json:"cubeWidth,omitempty"`
	// The commodity code associated with the container.
	CommodityCode *string `json:"commodityCode,omitempty"`
	// The harmonized tariff code associated with the container.
	HarmonizedTariffCode *string `json:"harmonizedTariffCode,omitempty"`
	// Indicates whether the container contents are hazardous or not.
	Hazardous *bool `json:"hazardous,omitempty"`
	// The freight classification associated with the container.
	FreightClassification *string `json:"freightClassification,omitempty"`
	// The weight classification associated with the container.
	WeightClassification *string `json:"weightClassification,omitempty"`
}

// NewShippingInventoryApiGetPartShippingDetailsResponse instantiates a new ShippingInventoryApiGetPartShippingDetailsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShippingInventoryApiGetPartShippingDetailsResponse() *ShippingInventoryApiGetPartShippingDetailsResponse {
	this := ShippingInventoryApiGetPartShippingDetailsResponse{}
	return &this
}

// NewShippingInventoryApiGetPartShippingDetailsResponseWithDefaults instantiates a new ShippingInventoryApiGetPartShippingDetailsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShippingInventoryApiGetPartShippingDetailsResponseWithDefaults() *ShippingInventoryApiGetPartShippingDetailsResponse {
	this := ShippingInventoryApiGetPartShippingDetailsResponse{}
	return &this
}

// GetPartId returns the PartId field value if set, zero value otherwise.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetPartId() string {
	if o == nil || IsNil(o.PartId) {
		var ret string
		return ret
	}
	return *o.PartId
}

// GetPartIdOk returns a tuple with the PartId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetPartIdOk() (*string, bool) {
	if o == nil || IsNil(o.PartId) {
		return nil, false
	}
	return o.PartId, true
}

// HasPartId returns a boolean if a field has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) HasPartId() bool {
	if o != nil && !IsNil(o.PartId) {
		return true
	}

	return false
}

// SetPartId gets a reference to the given string and assigns it to the PartId field.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) SetPartId(v string) {
	o.PartId = &v
}

// GetPartNumber returns the PartNumber field value if set, zero value otherwise.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetPartNumber() string {
	if o == nil || IsNil(o.PartNumber) {
		var ret string
		return ret
	}
	return *o.PartNumber
}

// GetPartNumberOk returns a tuple with the PartNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetPartNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PartNumber) {
		return nil, false
	}
	return o.PartNumber, true
}

// HasPartNumber returns a boolean if a field has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) HasPartNumber() bool {
	if o != nil && !IsNil(o.PartNumber) {
		return true
	}

	return false
}

// SetPartNumber gets a reference to the given string and assigns it to the PartNumber field.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) SetPartNumber(v string) {
	o.PartNumber = &v
}

// GetPartRevision returns the PartRevision field value if set, zero value otherwise.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetPartRevision() string {
	if o == nil || IsNil(o.PartRevision) {
		var ret string
		return ret
	}
	return *o.PartRevision
}

// GetPartRevisionOk returns a tuple with the PartRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetPartRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.PartRevision) {
		return nil, false
	}
	return o.PartRevision, true
}

// HasPartRevision returns a boolean if a field has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) HasPartRevision() bool {
	if o != nil && !IsNil(o.PartRevision) {
		return true
	}

	return false
}

// SetPartRevision gets a reference to the given string and assigns it to the PartRevision field.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) SetPartRevision(v string) {
	o.PartRevision = &v
}

// GetPartNumberRevision returns the PartNumberRevision field value if set, zero value otherwise.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetPartNumberRevision() string {
	if o == nil || IsNil(o.PartNumberRevision) {
		var ret string
		return ret
	}
	return *o.PartNumberRevision
}

// GetPartNumberRevisionOk returns a tuple with the PartNumberRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetPartNumberRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.PartNumberRevision) {
		return nil, false
	}
	return o.PartNumberRevision, true
}

// HasPartNumberRevision returns a boolean if a field has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) HasPartNumberRevision() bool {
	if o != nil && !IsNil(o.PartNumberRevision) {
		return true
	}

	return false
}

// SetPartNumberRevision gets a reference to the given string and assigns it to the PartNumberRevision field.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) SetPartNumberRevision(v string) {
	o.PartNumberRevision = &v
}

// GetContainerType returns the ContainerType field value if set, zero value otherwise.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetContainerType() string {
	if o == nil || IsNil(o.ContainerType) {
		var ret string
		return ret
	}
	return *o.ContainerType
}

// GetContainerTypeOk returns a tuple with the ContainerType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetContainerTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ContainerType) {
		return nil, false
	}
	return o.ContainerType, true
}

// HasContainerType returns a boolean if a field has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) HasContainerType() bool {
	if o != nil && !IsNil(o.ContainerType) {
		return true
	}

	return false
}

// SetContainerType gets a reference to the given string and assigns it to the ContainerType field.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) SetContainerType(v string) {
	o.ContainerType = &v
}

// GetPartPieceWeight returns the PartPieceWeight field value if set, zero value otherwise.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetPartPieceWeight() float64 {
	if o == nil || IsNil(o.PartPieceWeight) {
		var ret float64
		return ret
	}
	return *o.PartPieceWeight
}

// GetPartPieceWeightOk returns a tuple with the PartPieceWeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetPartPieceWeightOk() (*float64, bool) {
	if o == nil || IsNil(o.PartPieceWeight) {
		return nil, false
	}
	return o.PartPieceWeight, true
}

// HasPartPieceWeight returns a boolean if a field has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) HasPartPieceWeight() bool {
	if o != nil && !IsNil(o.PartPieceWeight) {
		return true
	}

	return false
}

// SetPartPieceWeight gets a reference to the given float64 and assigns it to the PartPieceWeight field.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) SetPartPieceWeight(v float64) {
	o.PartPieceWeight = &v
}

// GetWeightUnit returns the WeightUnit field value if set, zero value otherwise.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetWeightUnit() string {
	if o == nil || IsNil(o.WeightUnit) {
		var ret string
		return ret
	}
	return *o.WeightUnit
}

// GetWeightUnitOk returns a tuple with the WeightUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetWeightUnitOk() (*string, bool) {
	if o == nil || IsNil(o.WeightUnit) {
		return nil, false
	}
	return o.WeightUnit, true
}

// HasWeightUnit returns a boolean if a field has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) HasWeightUnit() bool {
	if o != nil && !IsNil(o.WeightUnit) {
		return true
	}

	return false
}

// SetWeightUnit gets a reference to the given string and assigns it to the WeightUnit field.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) SetWeightUnit(v string) {
	o.WeightUnit = &v
}

// GetCubeHeight returns the CubeHeight field value if set, zero value otherwise.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetCubeHeight() float64 {
	if o == nil || IsNil(o.CubeHeight) {
		var ret float64
		return ret
	}
	return *o.CubeHeight
}

// GetCubeHeightOk returns a tuple with the CubeHeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetCubeHeightOk() (*float64, bool) {
	if o == nil || IsNil(o.CubeHeight) {
		return nil, false
	}
	return o.CubeHeight, true
}

// HasCubeHeight returns a boolean if a field has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) HasCubeHeight() bool {
	if o != nil && !IsNil(o.CubeHeight) {
		return true
	}

	return false
}

// SetCubeHeight gets a reference to the given float64 and assigns it to the CubeHeight field.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) SetCubeHeight(v float64) {
	o.CubeHeight = &v
}

// GetCubeLength returns the CubeLength field value if set, zero value otherwise.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetCubeLength() float64 {
	if o == nil || IsNil(o.CubeLength) {
		var ret float64
		return ret
	}
	return *o.CubeLength
}

// GetCubeLengthOk returns a tuple with the CubeLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetCubeLengthOk() (*float64, bool) {
	if o == nil || IsNil(o.CubeLength) {
		return nil, false
	}
	return o.CubeLength, true
}

// HasCubeLength returns a boolean if a field has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) HasCubeLength() bool {
	if o != nil && !IsNil(o.CubeLength) {
		return true
	}

	return false
}

// SetCubeLength gets a reference to the given float64 and assigns it to the CubeLength field.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) SetCubeLength(v float64) {
	o.CubeLength = &v
}

// GetCubeWidth returns the CubeWidth field value if set, zero value otherwise.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetCubeWidth() float64 {
	if o == nil || IsNil(o.CubeWidth) {
		var ret float64
		return ret
	}
	return *o.CubeWidth
}

// GetCubeWidthOk returns a tuple with the CubeWidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetCubeWidthOk() (*float64, bool) {
	if o == nil || IsNil(o.CubeWidth) {
		return nil, false
	}
	return o.CubeWidth, true
}

// HasCubeWidth returns a boolean if a field has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) HasCubeWidth() bool {
	if o != nil && !IsNil(o.CubeWidth) {
		return true
	}

	return false
}

// SetCubeWidth gets a reference to the given float64 and assigns it to the CubeWidth field.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) SetCubeWidth(v float64) {
	o.CubeWidth = &v
}

// GetCommodityCode returns the CommodityCode field value if set, zero value otherwise.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetCommodityCode() string {
	if o == nil || IsNil(o.CommodityCode) {
		var ret string
		return ret
	}
	return *o.CommodityCode
}

// GetCommodityCodeOk returns a tuple with the CommodityCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetCommodityCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CommodityCode) {
		return nil, false
	}
	return o.CommodityCode, true
}

// HasCommodityCode returns a boolean if a field has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) HasCommodityCode() bool {
	if o != nil && !IsNil(o.CommodityCode) {
		return true
	}

	return false
}

// SetCommodityCode gets a reference to the given string and assigns it to the CommodityCode field.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) SetCommodityCode(v string) {
	o.CommodityCode = &v
}

// GetHarmonizedTariffCode returns the HarmonizedTariffCode field value if set, zero value otherwise.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetHarmonizedTariffCode() string {
	if o == nil || IsNil(o.HarmonizedTariffCode) {
		var ret string
		return ret
	}
	return *o.HarmonizedTariffCode
}

// GetHarmonizedTariffCodeOk returns a tuple with the HarmonizedTariffCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetHarmonizedTariffCodeOk() (*string, bool) {
	if o == nil || IsNil(o.HarmonizedTariffCode) {
		return nil, false
	}
	return o.HarmonizedTariffCode, true
}

// HasHarmonizedTariffCode returns a boolean if a field has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) HasHarmonizedTariffCode() bool {
	if o != nil && !IsNil(o.HarmonizedTariffCode) {
		return true
	}

	return false
}

// SetHarmonizedTariffCode gets a reference to the given string and assigns it to the HarmonizedTariffCode field.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) SetHarmonizedTariffCode(v string) {
	o.HarmonizedTariffCode = &v
}

// GetHazardous returns the Hazardous field value if set, zero value otherwise.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetHazardous() bool {
	if o == nil || IsNil(o.Hazardous) {
		var ret bool
		return ret
	}
	return *o.Hazardous
}

// GetHazardousOk returns a tuple with the Hazardous field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetHazardousOk() (*bool, bool) {
	if o == nil || IsNil(o.Hazardous) {
		return nil, false
	}
	return o.Hazardous, true
}

// HasHazardous returns a boolean if a field has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) HasHazardous() bool {
	if o != nil && !IsNil(o.Hazardous) {
		return true
	}

	return false
}

// SetHazardous gets a reference to the given bool and assigns it to the Hazardous field.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) SetHazardous(v bool) {
	o.Hazardous = &v
}

// GetFreightClassification returns the FreightClassification field value if set, zero value otherwise.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetFreightClassification() string {
	if o == nil || IsNil(o.FreightClassification) {
		var ret string
		return ret
	}
	return *o.FreightClassification
}

// GetFreightClassificationOk returns a tuple with the FreightClassification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetFreightClassificationOk() (*string, bool) {
	if o == nil || IsNil(o.FreightClassification) {
		return nil, false
	}
	return o.FreightClassification, true
}

// HasFreightClassification returns a boolean if a field has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) HasFreightClassification() bool {
	if o != nil && !IsNil(o.FreightClassification) {
		return true
	}

	return false
}

// SetFreightClassification gets a reference to the given string and assigns it to the FreightClassification field.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) SetFreightClassification(v string) {
	o.FreightClassification = &v
}

// GetWeightClassification returns the WeightClassification field value if set, zero value otherwise.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetWeightClassification() string {
	if o == nil || IsNil(o.WeightClassification) {
		var ret string
		return ret
	}
	return *o.WeightClassification
}

// GetWeightClassificationOk returns a tuple with the WeightClassification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) GetWeightClassificationOk() (*string, bool) {
	if o == nil || IsNil(o.WeightClassification) {
		return nil, false
	}
	return o.WeightClassification, true
}

// HasWeightClassification returns a boolean if a field has been set.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) HasWeightClassification() bool {
	if o != nil && !IsNil(o.WeightClassification) {
		return true
	}

	return false
}

// SetWeightClassification gets a reference to the given string and assigns it to the WeightClassification field.
func (o *ShippingInventoryApiGetPartShippingDetailsResponse) SetWeightClassification(v string) {
	o.WeightClassification = &v
}

func (o ShippingInventoryApiGetPartShippingDetailsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShippingInventoryApiGetPartShippingDetailsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PartId) {
		toSerialize["partId"] = o.PartId
	}
	if !IsNil(o.PartNumber) {
		toSerialize["partNumber"] = o.PartNumber
	}
	if !IsNil(o.PartRevision) {
		toSerialize["partRevision"] = o.PartRevision
	}
	if !IsNil(o.PartNumberRevision) {
		toSerialize["partNumberRevision"] = o.PartNumberRevision
	}
	if !IsNil(o.ContainerType) {
		toSerialize["containerType"] = o.ContainerType
	}
	if !IsNil(o.PartPieceWeight) {
		toSerialize["partPieceWeight"] = o.PartPieceWeight
	}
	if !IsNil(o.WeightUnit) {
		toSerialize["weightUnit"] = o.WeightUnit
	}
	if !IsNil(o.CubeHeight) {
		toSerialize["cubeHeight"] = o.CubeHeight
	}
	if !IsNil(o.CubeLength) {
		toSerialize["cubeLength"] = o.CubeLength
	}
	if !IsNil(o.CubeWidth) {
		toSerialize["cubeWidth"] = o.CubeWidth
	}
	if !IsNil(o.CommodityCode) {
		toSerialize["commodityCode"] = o.CommodityCode
	}
	if !IsNil(o.HarmonizedTariffCode) {
		toSerialize["harmonizedTariffCode"] = o.HarmonizedTariffCode
	}
	if !IsNil(o.Hazardous) {
		toSerialize["hazardous"] = o.Hazardous
	}
	if !IsNil(o.FreightClassification) {
		toSerialize["freightClassification"] = o.FreightClassification
	}
	if !IsNil(o.WeightClassification) {
		toSerialize["weightClassification"] = o.WeightClassification
	}
	return toSerialize, nil
}

type NullableShippingInventoryApiGetPartShippingDetailsResponse struct {
	value *ShippingInventoryApiGetPartShippingDetailsResponse
	isSet bool
}

func (v NullableShippingInventoryApiGetPartShippingDetailsResponse) Get() *ShippingInventoryApiGetPartShippingDetailsResponse {
	return v.value
}

func (v *NullableShippingInventoryApiGetPartShippingDetailsResponse) Set(val *ShippingInventoryApiGetPartShippingDetailsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableShippingInventoryApiGetPartShippingDetailsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableShippingInventoryApiGetPartShippingDetailsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShippingInventoryApiGetPartShippingDetailsResponse(val *ShippingInventoryApiGetPartShippingDetailsResponse) *NullableShippingInventoryApiGetPartShippingDetailsResponse {
	return &NullableShippingInventoryApiGetPartShippingDetailsResponse{value: val, isSet: true}
}

func (v NullableShippingInventoryApiGetPartShippingDetailsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShippingInventoryApiGetPartShippingDetailsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


