/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response{}

// PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response Progress details for a batch request.
type PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response struct {
	// The ID of the batch request.
	Id *string `json:"id,omitempty"`
	// The number of releases in the batch request.
	ReleasesCount *int32 `json:"releasesCount,omitempty"`
	// The number of releases in the batch request that have been processed.
	ReleasesProcessed *int32 `json:"releasesProcessed,omitempty"`
	// Any errors encountered while processing the releases from a batch request.
	Failures []string `json:"failures,omitempty"`
}

// NewPurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response instantiates a new PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response() *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response {
	this := PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response{}
	return &this
}

// NewPurchaseOrderReleasesBatchApiDeleteReleaseBatch202ResponseWithDefaults instantiates a new PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPurchaseOrderReleasesBatchApiDeleteReleaseBatch202ResponseWithDefaults() *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response {
	this := PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) SetId(v string) {
	o.Id = &v
}

// GetReleasesCount returns the ReleasesCount field value if set, zero value otherwise.
func (o *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) GetReleasesCount() int32 {
	if o == nil || IsNil(o.ReleasesCount) {
		var ret int32
		return ret
	}
	return *o.ReleasesCount
}

// GetReleasesCountOk returns a tuple with the ReleasesCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) GetReleasesCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ReleasesCount) {
		return nil, false
	}
	return o.ReleasesCount, true
}

// HasReleasesCount returns a boolean if a field has been set.
func (o *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) HasReleasesCount() bool {
	if o != nil && !IsNil(o.ReleasesCount) {
		return true
	}

	return false
}

// SetReleasesCount gets a reference to the given int32 and assigns it to the ReleasesCount field.
func (o *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) SetReleasesCount(v int32) {
	o.ReleasesCount = &v
}

// GetReleasesProcessed returns the ReleasesProcessed field value if set, zero value otherwise.
func (o *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) GetReleasesProcessed() int32 {
	if o == nil || IsNil(o.ReleasesProcessed) {
		var ret int32
		return ret
	}
	return *o.ReleasesProcessed
}

// GetReleasesProcessedOk returns a tuple with the ReleasesProcessed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) GetReleasesProcessedOk() (*int32, bool) {
	if o == nil || IsNil(o.ReleasesProcessed) {
		return nil, false
	}
	return o.ReleasesProcessed, true
}

// HasReleasesProcessed returns a boolean if a field has been set.
func (o *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) HasReleasesProcessed() bool {
	if o != nil && !IsNil(o.ReleasesProcessed) {
		return true
	}

	return false
}

// SetReleasesProcessed gets a reference to the given int32 and assigns it to the ReleasesProcessed field.
func (o *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) SetReleasesProcessed(v int32) {
	o.ReleasesProcessed = &v
}

// GetFailures returns the Failures field value if set, zero value otherwise.
func (o *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) GetFailures() []string {
	if o == nil || IsNil(o.Failures) {
		var ret []string
		return ret
	}
	return o.Failures
}

// GetFailuresOk returns a tuple with the Failures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) GetFailuresOk() ([]string, bool) {
	if o == nil || IsNil(o.Failures) {
		return nil, false
	}
	return o.Failures, true
}

// HasFailures returns a boolean if a field has been set.
func (o *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) HasFailures() bool {
	if o != nil && !IsNil(o.Failures) {
		return true
	}

	return false
}

// SetFailures gets a reference to the given []string and assigns it to the Failures field.
func (o *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) SetFailures(v []string) {
	o.Failures = v
}

func (o PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ReleasesCount) {
		toSerialize["releasesCount"] = o.ReleasesCount
	}
	if !IsNil(o.ReleasesProcessed) {
		toSerialize["releasesProcessed"] = o.ReleasesProcessed
	}
	if !IsNil(o.Failures) {
		toSerialize["failures"] = o.Failures
	}
	return toSerialize, nil
}

type NullablePurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response struct {
	value *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response
	isSet bool
}

func (v NullablePurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) Get() *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response {
	return v.value
}

func (v *NullablePurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) Set(val *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response(val *PurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) *NullablePurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response {
	return &NullablePurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response{value: val, isSet: true}
}

func (v NullablePurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePurchaseOrderReleasesBatchApiDeleteReleaseBatch202Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


