/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plex

import (
	"encoding/json"
)

// checks if the KitRecommendationsApiGetKitRecommendationBomAssociationItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KitRecommendationsApiGetKitRecommendationBomAssociationItem{}

// KitRecommendationsApiGetKitRecommendationBomAssociationItem struct for KitRecommendationsApiGetKitRecommendationBomAssociationItem
type KitRecommendationsApiGetKitRecommendationBomAssociationItem struct {
	// The Bill of Material ID.
	BomId *string `json:"bomId,omitempty"`
	// The Part ID.
	PartId *string `json:"partId,omitempty"`
	// The Part Operation ID.
	PartOperationId *string `json:"partOperationId,omitempty"`
}

// NewKitRecommendationsApiGetKitRecommendationBomAssociationItem instantiates a new KitRecommendationsApiGetKitRecommendationBomAssociationItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKitRecommendationsApiGetKitRecommendationBomAssociationItem() *KitRecommendationsApiGetKitRecommendationBomAssociationItem {
	this := KitRecommendationsApiGetKitRecommendationBomAssociationItem{}
	return &this
}

// NewKitRecommendationsApiGetKitRecommendationBomAssociationItemWithDefaults instantiates a new KitRecommendationsApiGetKitRecommendationBomAssociationItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKitRecommendationsApiGetKitRecommendationBomAssociationItemWithDefaults() *KitRecommendationsApiGetKitRecommendationBomAssociationItem {
	this := KitRecommendationsApiGetKitRecommendationBomAssociationItem{}
	return &this
}

// GetBomId returns the BomId field value if set, zero value otherwise.
func (o *KitRecommendationsApiGetKitRecommendationBomAssociationItem) GetBomId() string {
	if o == nil || IsNil(o.BomId) {
		var ret string
		return ret
	}
	return *o.BomId
}

// GetBomIdOk returns a tuple with the BomId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KitRecommendationsApiGetKitRecommendationBomAssociationItem) GetBomIdOk() (*string, bool) {
	if o == nil || IsNil(o.BomId) {
		return nil, false
	}
	return o.BomId, true
}

// HasBomId returns a boolean if a field has been set.
func (o *KitRecommendationsApiGetKitRecommendationBomAssociationItem) HasBomId() bool {
	if o != nil && !IsNil(o.BomId) {
		return true
	}

	return false
}

// SetBomId gets a reference to the given string and assigns it to the BomId field.
func (o *KitRecommendationsApiGetKitRecommendationBomAssociationItem) SetBomId(v string) {
	o.BomId = &v
}

// GetPartId returns the PartId field value if set, zero value otherwise.
func (o *KitRecommendationsApiGetKitRecommendationBomAssociationItem) GetPartId() string {
	if o == nil || IsNil(o.PartId) {
		var ret string
		return ret
	}
	return *o.PartId
}

// GetPartIdOk returns a tuple with the PartId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KitRecommendationsApiGetKitRecommendationBomAssociationItem) GetPartIdOk() (*string, bool) {
	if o == nil || IsNil(o.PartId) {
		return nil, false
	}
	return o.PartId, true
}

// HasPartId returns a boolean if a field has been set.
func (o *KitRecommendationsApiGetKitRecommendationBomAssociationItem) HasPartId() bool {
	if o != nil && !IsNil(o.PartId) {
		return true
	}

	return false
}

// SetPartId gets a reference to the given string and assigns it to the PartId field.
func (o *KitRecommendationsApiGetKitRecommendationBomAssociationItem) SetPartId(v string) {
	o.PartId = &v
}

// GetPartOperationId returns the PartOperationId field value if set, zero value otherwise.
func (o *KitRecommendationsApiGetKitRecommendationBomAssociationItem) GetPartOperationId() string {
	if o == nil || IsNil(o.PartOperationId) {
		var ret string
		return ret
	}
	return *o.PartOperationId
}

// GetPartOperationIdOk returns a tuple with the PartOperationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KitRecommendationsApiGetKitRecommendationBomAssociationItem) GetPartOperationIdOk() (*string, bool) {
	if o == nil || IsNil(o.PartOperationId) {
		return nil, false
	}
	return o.PartOperationId, true
}

// HasPartOperationId returns a boolean if a field has been set.
func (o *KitRecommendationsApiGetKitRecommendationBomAssociationItem) HasPartOperationId() bool {
	if o != nil && !IsNil(o.PartOperationId) {
		return true
	}

	return false
}

// SetPartOperationId gets a reference to the given string and assigns it to the PartOperationId field.
func (o *KitRecommendationsApiGetKitRecommendationBomAssociationItem) SetPartOperationId(v string) {
	o.PartOperationId = &v
}

func (o KitRecommendationsApiGetKitRecommendationBomAssociationItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KitRecommendationsApiGetKitRecommendationBomAssociationItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BomId) {
		toSerialize["bomId"] = o.BomId
	}
	if !IsNil(o.PartId) {
		toSerialize["partId"] = o.PartId
	}
	if !IsNil(o.PartOperationId) {
		toSerialize["partOperationId"] = o.PartOperationId
	}
	return toSerialize, nil
}

type NullableKitRecommendationsApiGetKitRecommendationBomAssociationItem struct {
	value *KitRecommendationsApiGetKitRecommendationBomAssociationItem
	isSet bool
}

func (v NullableKitRecommendationsApiGetKitRecommendationBomAssociationItem) Get() *KitRecommendationsApiGetKitRecommendationBomAssociationItem {
	return v.value
}

func (v *NullableKitRecommendationsApiGetKitRecommendationBomAssociationItem) Set(val *KitRecommendationsApiGetKitRecommendationBomAssociationItem) {
	v.value = val
	v.isSet = true
}

func (v NullableKitRecommendationsApiGetKitRecommendationBomAssociationItem) IsSet() bool {
	return v.isSet
}

func (v *NullableKitRecommendationsApiGetKitRecommendationBomAssociationItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKitRecommendationsApiGetKitRecommendationBomAssociationItem(val *KitRecommendationsApiGetKitRecommendationBomAssociationItem) *NullableKitRecommendationsApiGetKitRecommendationBomAssociationItem {
	return &NullableKitRecommendationsApiGetKitRecommendationBomAssociationItem{value: val, isSet: true}
}

func (v NullableKitRecommendationsApiGetKitRecommendationBomAssociationItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKitRecommendationsApiGetKitRecommendationBomAssociationItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


