/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plex

import (
	"encoding/json"
)

// checks if the PlexApmApiGetElapsedTimeByTags500Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlexApmApiGetElapsedTimeByTags500Response{}

// PlexApmApiGetElapsedTimeByTags500Response struct for PlexApmApiGetElapsedTimeByTags500Response
type PlexApmApiGetElapsedTimeByTags500Response struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewPlexApmApiGetElapsedTimeByTags500Response instantiates a new PlexApmApiGetElapsedTimeByTags500Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlexApmApiGetElapsedTimeByTags500Response() *PlexApmApiGetElapsedTimeByTags500Response {
	this := PlexApmApiGetElapsedTimeByTags500Response{}
	return &this
}

// NewPlexApmApiGetElapsedTimeByTags500ResponseWithDefaults instantiates a new PlexApmApiGetElapsedTimeByTags500Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlexApmApiGetElapsedTimeByTags500ResponseWithDefaults() *PlexApmApiGetElapsedTimeByTags500Response {
	this := PlexApmApiGetElapsedTimeByTags500Response{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *PlexApmApiGetElapsedTimeByTags500Response) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlexApmApiGetElapsedTimeByTags500Response) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *PlexApmApiGetElapsedTimeByTags500Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *PlexApmApiGetElapsedTimeByTags500Response) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *PlexApmApiGetElapsedTimeByTags500Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlexApmApiGetElapsedTimeByTags500Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *PlexApmApiGetElapsedTimeByTags500Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *PlexApmApiGetElapsedTimeByTags500Response) SetMessage(v string) {
	o.Message = &v
}

func (o PlexApmApiGetElapsedTimeByTags500Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlexApmApiGetElapsedTimeByTags500Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullablePlexApmApiGetElapsedTimeByTags500Response struct {
	value *PlexApmApiGetElapsedTimeByTags500Response
	isSet bool
}

func (v NullablePlexApmApiGetElapsedTimeByTags500Response) Get() *PlexApmApiGetElapsedTimeByTags500Response {
	return v.value
}

func (v *NullablePlexApmApiGetElapsedTimeByTags500Response) Set(val *PlexApmApiGetElapsedTimeByTags500Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePlexApmApiGetElapsedTimeByTags500Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePlexApmApiGetElapsedTimeByTags500Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlexApmApiGetElapsedTimeByTags500Response(val *PlexApmApiGetElapsedTimeByTags500Response) *NullablePlexApmApiGetElapsedTimeByTags500Response {
	return &NullablePlexApmApiGetElapsedTimeByTags500Response{value: val, isSet: true}
}

func (v NullablePlexApmApiGetElapsedTimeByTags500Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlexApmApiGetElapsedTimeByTags500Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


