/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plex

import (
	"encoding/json"
)

// checks if the CustomObjectsApiGetFieldDefinitionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomObjectsApiGetFieldDefinitionResponse{}

// CustomObjectsApiGetFieldDefinitionResponse struct for CustomObjectsApiGetFieldDefinitionResponse
type CustomObjectsApiGetFieldDefinitionResponse struct {
	// The name of the data type used internally by the system.
	FieldTypeName *string `json:"fieldTypeName,omitempty"`
	// The name of the field definition that uniquely identifies the field within a standard object and is used internally by the system.
	FieldName *string `json:"fieldName,omitempty"`
	// The display name of the custom field that is used as a label on forms within Plex and on printed documents.
	FieldLabel *string `json:"fieldLabel,omitempty"`
	// The description of the custom field definition that helps users understand of information should be saved to the custom field.
	Description *string `json:"description,omitempty"`
	// Constraints of the custom field definition, such as minimum and maximum values that are allowed.
	Constraints *string `json:"constraints,omitempty"`
}

// NewCustomObjectsApiGetFieldDefinitionResponse instantiates a new CustomObjectsApiGetFieldDefinitionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomObjectsApiGetFieldDefinitionResponse() *CustomObjectsApiGetFieldDefinitionResponse {
	this := CustomObjectsApiGetFieldDefinitionResponse{}
	return &this
}

// NewCustomObjectsApiGetFieldDefinitionResponseWithDefaults instantiates a new CustomObjectsApiGetFieldDefinitionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomObjectsApiGetFieldDefinitionResponseWithDefaults() *CustomObjectsApiGetFieldDefinitionResponse {
	this := CustomObjectsApiGetFieldDefinitionResponse{}
	return &this
}

// GetFieldTypeName returns the FieldTypeName field value if set, zero value otherwise.
func (o *CustomObjectsApiGetFieldDefinitionResponse) GetFieldTypeName() string {
	if o == nil || IsNil(o.FieldTypeName) {
		var ret string
		return ret
	}
	return *o.FieldTypeName
}

// GetFieldTypeNameOk returns a tuple with the FieldTypeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomObjectsApiGetFieldDefinitionResponse) GetFieldTypeNameOk() (*string, bool) {
	if o == nil || IsNil(o.FieldTypeName) {
		return nil, false
	}
	return o.FieldTypeName, true
}

// HasFieldTypeName returns a boolean if a field has been set.
func (o *CustomObjectsApiGetFieldDefinitionResponse) HasFieldTypeName() bool {
	if o != nil && !IsNil(o.FieldTypeName) {
		return true
	}

	return false
}

// SetFieldTypeName gets a reference to the given string and assigns it to the FieldTypeName field.
func (o *CustomObjectsApiGetFieldDefinitionResponse) SetFieldTypeName(v string) {
	o.FieldTypeName = &v
}

// GetFieldName returns the FieldName field value if set, zero value otherwise.
func (o *CustomObjectsApiGetFieldDefinitionResponse) GetFieldName() string {
	if o == nil || IsNil(o.FieldName) {
		var ret string
		return ret
	}
	return *o.FieldName
}

// GetFieldNameOk returns a tuple with the FieldName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomObjectsApiGetFieldDefinitionResponse) GetFieldNameOk() (*string, bool) {
	if o == nil || IsNil(o.FieldName) {
		return nil, false
	}
	return o.FieldName, true
}

// HasFieldName returns a boolean if a field has been set.
func (o *CustomObjectsApiGetFieldDefinitionResponse) HasFieldName() bool {
	if o != nil && !IsNil(o.FieldName) {
		return true
	}

	return false
}

// SetFieldName gets a reference to the given string and assigns it to the FieldName field.
func (o *CustomObjectsApiGetFieldDefinitionResponse) SetFieldName(v string) {
	o.FieldName = &v
}

// GetFieldLabel returns the FieldLabel field value if set, zero value otherwise.
func (o *CustomObjectsApiGetFieldDefinitionResponse) GetFieldLabel() string {
	if o == nil || IsNil(o.FieldLabel) {
		var ret string
		return ret
	}
	return *o.FieldLabel
}

// GetFieldLabelOk returns a tuple with the FieldLabel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomObjectsApiGetFieldDefinitionResponse) GetFieldLabelOk() (*string, bool) {
	if o == nil || IsNil(o.FieldLabel) {
		return nil, false
	}
	return o.FieldLabel, true
}

// HasFieldLabel returns a boolean if a field has been set.
func (o *CustomObjectsApiGetFieldDefinitionResponse) HasFieldLabel() bool {
	if o != nil && !IsNil(o.FieldLabel) {
		return true
	}

	return false
}

// SetFieldLabel gets a reference to the given string and assigns it to the FieldLabel field.
func (o *CustomObjectsApiGetFieldDefinitionResponse) SetFieldLabel(v string) {
	o.FieldLabel = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CustomObjectsApiGetFieldDefinitionResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomObjectsApiGetFieldDefinitionResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CustomObjectsApiGetFieldDefinitionResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CustomObjectsApiGetFieldDefinitionResponse) SetDescription(v string) {
	o.Description = &v
}

// GetConstraints returns the Constraints field value if set, zero value otherwise.
func (o *CustomObjectsApiGetFieldDefinitionResponse) GetConstraints() string {
	if o == nil || IsNil(o.Constraints) {
		var ret string
		return ret
	}
	return *o.Constraints
}

// GetConstraintsOk returns a tuple with the Constraints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomObjectsApiGetFieldDefinitionResponse) GetConstraintsOk() (*string, bool) {
	if o == nil || IsNil(o.Constraints) {
		return nil, false
	}
	return o.Constraints, true
}

// HasConstraints returns a boolean if a field has been set.
func (o *CustomObjectsApiGetFieldDefinitionResponse) HasConstraints() bool {
	if o != nil && !IsNil(o.Constraints) {
		return true
	}

	return false
}

// SetConstraints gets a reference to the given string and assigns it to the Constraints field.
func (o *CustomObjectsApiGetFieldDefinitionResponse) SetConstraints(v string) {
	o.Constraints = &v
}

func (o CustomObjectsApiGetFieldDefinitionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomObjectsApiGetFieldDefinitionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FieldTypeName) {
		toSerialize["fieldTypeName"] = o.FieldTypeName
	}
	if !IsNil(o.FieldName) {
		toSerialize["fieldName"] = o.FieldName
	}
	if !IsNil(o.FieldLabel) {
		toSerialize["fieldLabel"] = o.FieldLabel
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Constraints) {
		toSerialize["constraints"] = o.Constraints
	}
	return toSerialize, nil
}

type NullableCustomObjectsApiGetFieldDefinitionResponse struct {
	value *CustomObjectsApiGetFieldDefinitionResponse
	isSet bool
}

func (v NullableCustomObjectsApiGetFieldDefinitionResponse) Get() *CustomObjectsApiGetFieldDefinitionResponse {
	return v.value
}

func (v *NullableCustomObjectsApiGetFieldDefinitionResponse) Set(val *CustomObjectsApiGetFieldDefinitionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomObjectsApiGetFieldDefinitionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomObjectsApiGetFieldDefinitionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomObjectsApiGetFieldDefinitionResponse(val *CustomObjectsApiGetFieldDefinitionResponse) *NullableCustomObjectsApiGetFieldDefinitionResponse {
	return &NullableCustomObjectsApiGetFieldDefinitionResponse{value: val, isSet: true}
}

func (v NullableCustomObjectsApiGetFieldDefinitionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomObjectsApiGetFieldDefinitionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


