/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plex

import (
	"encoding/json"
)

// checks if the SalesOrdersApiUpdateSalesOrderLinePrice400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SalesOrdersApiUpdateSalesOrderLinePrice400Response{}

// SalesOrdersApiUpdateSalesOrderLinePrice400Response struct for SalesOrdersApiUpdateSalesOrderLinePrice400Response
type SalesOrdersApiUpdateSalesOrderLinePrice400Response struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Errors []ErrorsItem `json:"errors,omitempty"`
}

// NewSalesOrdersApiUpdateSalesOrderLinePrice400Response instantiates a new SalesOrdersApiUpdateSalesOrderLinePrice400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSalesOrdersApiUpdateSalesOrderLinePrice400Response() *SalesOrdersApiUpdateSalesOrderLinePrice400Response {
	this := SalesOrdersApiUpdateSalesOrderLinePrice400Response{}
	return &this
}

// NewSalesOrdersApiUpdateSalesOrderLinePrice400ResponseWithDefaults instantiates a new SalesOrdersApiUpdateSalesOrderLinePrice400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSalesOrdersApiUpdateSalesOrderLinePrice400ResponseWithDefaults() *SalesOrdersApiUpdateSalesOrderLinePrice400Response {
	this := SalesOrdersApiUpdateSalesOrderLinePrice400Response{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *SalesOrdersApiUpdateSalesOrderLinePrice400Response) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SalesOrdersApiUpdateSalesOrderLinePrice400Response) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *SalesOrdersApiUpdateSalesOrderLinePrice400Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *SalesOrdersApiUpdateSalesOrderLinePrice400Response) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *SalesOrdersApiUpdateSalesOrderLinePrice400Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SalesOrdersApiUpdateSalesOrderLinePrice400Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *SalesOrdersApiUpdateSalesOrderLinePrice400Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *SalesOrdersApiUpdateSalesOrderLinePrice400Response) SetMessage(v string) {
	o.Message = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *SalesOrdersApiUpdateSalesOrderLinePrice400Response) GetErrors() []ErrorsItem {
	if o == nil || IsNil(o.Errors) {
		var ret []ErrorsItem
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SalesOrdersApiUpdateSalesOrderLinePrice400Response) GetErrorsOk() ([]ErrorsItem, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *SalesOrdersApiUpdateSalesOrderLinePrice400Response) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []ErrorsItem and assigns it to the Errors field.
func (o *SalesOrdersApiUpdateSalesOrderLinePrice400Response) SetErrors(v []ErrorsItem) {
	o.Errors = v
}

func (o SalesOrdersApiUpdateSalesOrderLinePrice400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SalesOrdersApiUpdateSalesOrderLinePrice400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableSalesOrdersApiUpdateSalesOrderLinePrice400Response struct {
	value *SalesOrdersApiUpdateSalesOrderLinePrice400Response
	isSet bool
}

func (v NullableSalesOrdersApiUpdateSalesOrderLinePrice400Response) Get() *SalesOrdersApiUpdateSalesOrderLinePrice400Response {
	return v.value
}

func (v *NullableSalesOrdersApiUpdateSalesOrderLinePrice400Response) Set(val *SalesOrdersApiUpdateSalesOrderLinePrice400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSalesOrdersApiUpdateSalesOrderLinePrice400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSalesOrdersApiUpdateSalesOrderLinePrice400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSalesOrdersApiUpdateSalesOrderLinePrice400Response(val *SalesOrdersApiUpdateSalesOrderLinePrice400Response) *NullableSalesOrdersApiUpdateSalesOrderLinePrice400Response {
	return &NullableSalesOrdersApiUpdateSalesOrderLinePrice400Response{value: val, isSet: true}
}

func (v NullableSalesOrdersApiUpdateSalesOrderLinePrice400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSalesOrdersApiUpdateSalesOrderLinePrice400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


