/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CustomerPartsApiSyncCustomerPartsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerPartsApiSyncCustomerPartsRequest{}

// CustomerPartsApiSyncCustomerPartsRequest The full CustomerPart Resource structure.
type CustomerPartsApiSyncCustomerPartsRequest struct {
	// A unique identifier for the Customer Part. This will be automatically generated if omitted from the request.
	Id *string `json:"id,omitempty"`
	// The customer part number.
	Number *string `json:"number,omitempty"`
	PartId *string `json:"partId,omitempty"`
	CustomerId *string `json:"customerId,omitempty"`
	// A description of the part.
	Description *string `json:"description,omitempty"`
	Revision *string `json:"revision,omitempty"`
}

// NewCustomerPartsApiSyncCustomerPartsRequest instantiates a new CustomerPartsApiSyncCustomerPartsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerPartsApiSyncCustomerPartsRequest() *CustomerPartsApiSyncCustomerPartsRequest {
	this := CustomerPartsApiSyncCustomerPartsRequest{}
	return &this
}

// NewCustomerPartsApiSyncCustomerPartsRequestWithDefaults instantiates a new CustomerPartsApiSyncCustomerPartsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerPartsApiSyncCustomerPartsRequestWithDefaults() *CustomerPartsApiSyncCustomerPartsRequest {
	this := CustomerPartsApiSyncCustomerPartsRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CustomerPartsApiSyncCustomerPartsRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerPartsApiSyncCustomerPartsRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CustomerPartsApiSyncCustomerPartsRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CustomerPartsApiSyncCustomerPartsRequest) SetId(v string) {
	o.Id = &v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *CustomerPartsApiSyncCustomerPartsRequest) GetNumber() string {
	if o == nil || IsNil(o.Number) {
		var ret string
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerPartsApiSyncCustomerPartsRequest) GetNumberOk() (*string, bool) {
	if o == nil || IsNil(o.Number) {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *CustomerPartsApiSyncCustomerPartsRequest) HasNumber() bool {
	if o != nil && !IsNil(o.Number) {
		return true
	}

	return false
}

// SetNumber gets a reference to the given string and assigns it to the Number field.
func (o *CustomerPartsApiSyncCustomerPartsRequest) SetNumber(v string) {
	o.Number = &v
}

// GetPartId returns the PartId field value if set, zero value otherwise.
func (o *CustomerPartsApiSyncCustomerPartsRequest) GetPartId() string {
	if o == nil || IsNil(o.PartId) {
		var ret string
		return ret
	}
	return *o.PartId
}

// GetPartIdOk returns a tuple with the PartId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerPartsApiSyncCustomerPartsRequest) GetPartIdOk() (*string, bool) {
	if o == nil || IsNil(o.PartId) {
		return nil, false
	}
	return o.PartId, true
}

// HasPartId returns a boolean if a field has been set.
func (o *CustomerPartsApiSyncCustomerPartsRequest) HasPartId() bool {
	if o != nil && !IsNil(o.PartId) {
		return true
	}

	return false
}

// SetPartId gets a reference to the given string and assigns it to the PartId field.
func (o *CustomerPartsApiSyncCustomerPartsRequest) SetPartId(v string) {
	o.PartId = &v
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *CustomerPartsApiSyncCustomerPartsRequest) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerPartsApiSyncCustomerPartsRequest) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *CustomerPartsApiSyncCustomerPartsRequest) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *CustomerPartsApiSyncCustomerPartsRequest) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CustomerPartsApiSyncCustomerPartsRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerPartsApiSyncCustomerPartsRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CustomerPartsApiSyncCustomerPartsRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CustomerPartsApiSyncCustomerPartsRequest) SetDescription(v string) {
	o.Description = &v
}

// GetRevision returns the Revision field value if set, zero value otherwise.
func (o *CustomerPartsApiSyncCustomerPartsRequest) GetRevision() string {
	if o == nil || IsNil(o.Revision) {
		var ret string
		return ret
	}
	return *o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerPartsApiSyncCustomerPartsRequest) GetRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.Revision) {
		return nil, false
	}
	return o.Revision, true
}

// HasRevision returns a boolean if a field has been set.
func (o *CustomerPartsApiSyncCustomerPartsRequest) HasRevision() bool {
	if o != nil && !IsNil(o.Revision) {
		return true
	}

	return false
}

// SetRevision gets a reference to the given string and assigns it to the Revision field.
func (o *CustomerPartsApiSyncCustomerPartsRequest) SetRevision(v string) {
	o.Revision = &v
}

func (o CustomerPartsApiSyncCustomerPartsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerPartsApiSyncCustomerPartsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Number) {
		toSerialize["number"] = o.Number
	}
	if !IsNil(o.PartId) {
		toSerialize["partId"] = o.PartId
	}
	if !IsNil(o.CustomerId) {
		toSerialize["customerId"] = o.CustomerId
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Revision) {
		toSerialize["revision"] = o.Revision
	}
	return toSerialize, nil
}

type NullableCustomerPartsApiSyncCustomerPartsRequest struct {
	value *CustomerPartsApiSyncCustomerPartsRequest
	isSet bool
}

func (v NullableCustomerPartsApiSyncCustomerPartsRequest) Get() *CustomerPartsApiSyncCustomerPartsRequest {
	return v.value
}

func (v *NullableCustomerPartsApiSyncCustomerPartsRequest) Set(val *CustomerPartsApiSyncCustomerPartsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerPartsApiSyncCustomerPartsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerPartsApiSyncCustomerPartsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerPartsApiSyncCustomerPartsRequest(val *CustomerPartsApiSyncCustomerPartsRequest) *NullableCustomerPartsApiSyncCustomerPartsRequest {
	return &NullableCustomerPartsApiSyncCustomerPartsRequest{value: val, isSet: true}
}

func (v NullableCustomerPartsApiSyncCustomerPartsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerPartsApiSyncCustomerPartsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


