/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plex

import (
	"encoding/json"
	"time"
)

// checks if the PurchaseOrdersApiListPurchaseOrderPricesItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PurchaseOrdersApiListPurchaseOrderPricesItem{}

// PurchaseOrdersApiListPurchaseOrderPricesItem The primary model for a Price.
type PurchaseOrdersApiListPurchaseOrderPricesItem struct {
	// The effective date of the price.
	EffectiveDate *time.Time `json:"effectiveDate,omitempty"`
	// The expiration date of the price.
	ExpirationDate *time.Time `json:"expirationDate,omitempty"`
	// Price per unit.
	UnitPrice *float64 `json:"unitPrice,omitempty"`
	Note *string `json:"note,omitempty"`
	// The ID of the user who created the record.
	CreatedById *string `json:"createdById,omitempty"`
	// The date on which the record was created.
	CreatedDate *time.Time `json:"createdDate,omitempty"`
	// The ID of the user who last modified the record.
	ModifiedById *string `json:"modifiedById,omitempty"`
	// The date on which the record was last modified.
	ModifiedDate *time.Time `json:"modifiedDate,omitempty"`
}

// NewPurchaseOrdersApiListPurchaseOrderPricesItem instantiates a new PurchaseOrdersApiListPurchaseOrderPricesItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPurchaseOrdersApiListPurchaseOrderPricesItem() *PurchaseOrdersApiListPurchaseOrderPricesItem {
	this := PurchaseOrdersApiListPurchaseOrderPricesItem{}
	return &this
}

// NewPurchaseOrdersApiListPurchaseOrderPricesItemWithDefaults instantiates a new PurchaseOrdersApiListPurchaseOrderPricesItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPurchaseOrdersApiListPurchaseOrderPricesItemWithDefaults() *PurchaseOrdersApiListPurchaseOrderPricesItem {
	this := PurchaseOrdersApiListPurchaseOrderPricesItem{}
	return &this
}

// GetEffectiveDate returns the EffectiveDate field value if set, zero value otherwise.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) GetEffectiveDate() time.Time {
	if o == nil || IsNil(o.EffectiveDate) {
		var ret time.Time
		return ret
	}
	return *o.EffectiveDate
}

// GetEffectiveDateOk returns a tuple with the EffectiveDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) GetEffectiveDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EffectiveDate) {
		return nil, false
	}
	return o.EffectiveDate, true
}

// HasEffectiveDate returns a boolean if a field has been set.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) HasEffectiveDate() bool {
	if o != nil && !IsNil(o.EffectiveDate) {
		return true
	}

	return false
}

// SetEffectiveDate gets a reference to the given time.Time and assigns it to the EffectiveDate field.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) SetEffectiveDate(v time.Time) {
	o.EffectiveDate = &v
}

// GetExpirationDate returns the ExpirationDate field value if set, zero value otherwise.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) GetExpirationDate() time.Time {
	if o == nil || IsNil(o.ExpirationDate) {
		var ret time.Time
		return ret
	}
	return *o.ExpirationDate
}

// GetExpirationDateOk returns a tuple with the ExpirationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) GetExpirationDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpirationDate) {
		return nil, false
	}
	return o.ExpirationDate, true
}

// HasExpirationDate returns a boolean if a field has been set.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) HasExpirationDate() bool {
	if o != nil && !IsNil(o.ExpirationDate) {
		return true
	}

	return false
}

// SetExpirationDate gets a reference to the given time.Time and assigns it to the ExpirationDate field.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) SetExpirationDate(v time.Time) {
	o.ExpirationDate = &v
}

// GetUnitPrice returns the UnitPrice field value if set, zero value otherwise.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) GetUnitPrice() float64 {
	if o == nil || IsNil(o.UnitPrice) {
		var ret float64
		return ret
	}
	return *o.UnitPrice
}

// GetUnitPriceOk returns a tuple with the UnitPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) GetUnitPriceOk() (*float64, bool) {
	if o == nil || IsNil(o.UnitPrice) {
		return nil, false
	}
	return o.UnitPrice, true
}

// HasUnitPrice returns a boolean if a field has been set.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) HasUnitPrice() bool {
	if o != nil && !IsNil(o.UnitPrice) {
		return true
	}

	return false
}

// SetUnitPrice gets a reference to the given float64 and assigns it to the UnitPrice field.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) SetUnitPrice(v float64) {
	o.UnitPrice = &v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) GetNote() string {
	if o == nil || IsNil(o.Note) {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) GetNoteOk() (*string, bool) {
	if o == nil || IsNil(o.Note) {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) HasNote() bool {
	if o != nil && !IsNil(o.Note) {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) SetNote(v string) {
	o.Note = &v
}

// GetCreatedById returns the CreatedById field value if set, zero value otherwise.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) GetCreatedById() string {
	if o == nil || IsNil(o.CreatedById) {
		var ret string
		return ret
	}
	return *o.CreatedById
}

// GetCreatedByIdOk returns a tuple with the CreatedById field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) GetCreatedByIdOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedById) {
		return nil, false
	}
	return o.CreatedById, true
}

// HasCreatedById returns a boolean if a field has been set.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) HasCreatedById() bool {
	if o != nil && !IsNil(o.CreatedById) {
		return true
	}

	return false
}

// SetCreatedById gets a reference to the given string and assigns it to the CreatedById field.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) SetCreatedById(v string) {
	o.CreatedById = &v
}

// GetCreatedDate returns the CreatedDate field value if set, zero value otherwise.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) GetCreatedDate() time.Time {
	if o == nil || IsNil(o.CreatedDate) {
		var ret time.Time
		return ret
	}
	return *o.CreatedDate
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) GetCreatedDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedDate) {
		return nil, false
	}
	return o.CreatedDate, true
}

// HasCreatedDate returns a boolean if a field has been set.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) HasCreatedDate() bool {
	if o != nil && !IsNil(o.CreatedDate) {
		return true
	}

	return false
}

// SetCreatedDate gets a reference to the given time.Time and assigns it to the CreatedDate field.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) SetCreatedDate(v time.Time) {
	o.CreatedDate = &v
}

// GetModifiedById returns the ModifiedById field value if set, zero value otherwise.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) GetModifiedById() string {
	if o == nil || IsNil(o.ModifiedById) {
		var ret string
		return ret
	}
	return *o.ModifiedById
}

// GetModifiedByIdOk returns a tuple with the ModifiedById field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) GetModifiedByIdOk() (*string, bool) {
	if o == nil || IsNil(o.ModifiedById) {
		return nil, false
	}
	return o.ModifiedById, true
}

// HasModifiedById returns a boolean if a field has been set.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) HasModifiedById() bool {
	if o != nil && !IsNil(o.ModifiedById) {
		return true
	}

	return false
}

// SetModifiedById gets a reference to the given string and assigns it to the ModifiedById field.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) SetModifiedById(v string) {
	o.ModifiedById = &v
}

// GetModifiedDate returns the ModifiedDate field value if set, zero value otherwise.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) GetModifiedDate() time.Time {
	if o == nil || IsNil(o.ModifiedDate) {
		var ret time.Time
		return ret
	}
	return *o.ModifiedDate
}

// GetModifiedDateOk returns a tuple with the ModifiedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) GetModifiedDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ModifiedDate) {
		return nil, false
	}
	return o.ModifiedDate, true
}

// HasModifiedDate returns a boolean if a field has been set.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) HasModifiedDate() bool {
	if o != nil && !IsNil(o.ModifiedDate) {
		return true
	}

	return false
}

// SetModifiedDate gets a reference to the given time.Time and assigns it to the ModifiedDate field.
func (o *PurchaseOrdersApiListPurchaseOrderPricesItem) SetModifiedDate(v time.Time) {
	o.ModifiedDate = &v
}

func (o PurchaseOrdersApiListPurchaseOrderPricesItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PurchaseOrdersApiListPurchaseOrderPricesItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EffectiveDate) {
		toSerialize["effectiveDate"] = o.EffectiveDate
	}
	if !IsNil(o.ExpirationDate) {
		toSerialize["expirationDate"] = o.ExpirationDate
	}
	if !IsNil(o.UnitPrice) {
		toSerialize["unitPrice"] = o.UnitPrice
	}
	if !IsNil(o.Note) {
		toSerialize["note"] = o.Note
	}
	if !IsNil(o.CreatedById) {
		toSerialize["createdById"] = o.CreatedById
	}
	if !IsNil(o.CreatedDate) {
		toSerialize["createdDate"] = o.CreatedDate
	}
	if !IsNil(o.ModifiedById) {
		toSerialize["modifiedById"] = o.ModifiedById
	}
	if !IsNil(o.ModifiedDate) {
		toSerialize["modifiedDate"] = o.ModifiedDate
	}
	return toSerialize, nil
}

type NullablePurchaseOrdersApiListPurchaseOrderPricesItem struct {
	value *PurchaseOrdersApiListPurchaseOrderPricesItem
	isSet bool
}

func (v NullablePurchaseOrdersApiListPurchaseOrderPricesItem) Get() *PurchaseOrdersApiListPurchaseOrderPricesItem {
	return v.value
}

func (v *NullablePurchaseOrdersApiListPurchaseOrderPricesItem) Set(val *PurchaseOrdersApiListPurchaseOrderPricesItem) {
	v.value = val
	v.isSet = true
}

func (v NullablePurchaseOrdersApiListPurchaseOrderPricesItem) IsSet() bool {
	return v.isSet
}

func (v *NullablePurchaseOrdersApiListPurchaseOrderPricesItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePurchaseOrdersApiListPurchaseOrderPricesItem(val *PurchaseOrdersApiListPurchaseOrderPricesItem) *NullablePurchaseOrdersApiListPurchaseOrderPricesItem {
	return &NullablePurchaseOrdersApiListPurchaseOrderPricesItem{value: val, isSet: true}
}

func (v NullablePurchaseOrdersApiListPurchaseOrderPricesItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePurchaseOrdersApiListPurchaseOrderPricesItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


