/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plex

import (
	"encoding/json"
)

// checks if the InventoryOperationsManagementApiCreateInventoryShipmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InventoryOperationsManagementApiCreateInventoryShipmentRequest{}

// InventoryOperationsManagementApiCreateInventoryShipmentRequest struct for InventoryOperationsManagementApiCreateInventoryShipmentRequest
type InventoryOperationsManagementApiCreateInventoryShipmentRequest struct {
	// The external inventory shipment code. This code is not provided by Plex and is distinct from the shipment ID. 50 character max.
	ExternalShipmentCode *string `json:"externalShipmentCode,omitempty"`
}

// NewInventoryOperationsManagementApiCreateInventoryShipmentRequest instantiates a new InventoryOperationsManagementApiCreateInventoryShipmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInventoryOperationsManagementApiCreateInventoryShipmentRequest() *InventoryOperationsManagementApiCreateInventoryShipmentRequest {
	this := InventoryOperationsManagementApiCreateInventoryShipmentRequest{}
	return &this
}

// NewInventoryOperationsManagementApiCreateInventoryShipmentRequestWithDefaults instantiates a new InventoryOperationsManagementApiCreateInventoryShipmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInventoryOperationsManagementApiCreateInventoryShipmentRequestWithDefaults() *InventoryOperationsManagementApiCreateInventoryShipmentRequest {
	this := InventoryOperationsManagementApiCreateInventoryShipmentRequest{}
	return &this
}

// GetExternalShipmentCode returns the ExternalShipmentCode field value if set, zero value otherwise.
func (o *InventoryOperationsManagementApiCreateInventoryShipmentRequest) GetExternalShipmentCode() string {
	if o == nil || IsNil(o.ExternalShipmentCode) {
		var ret string
		return ret
	}
	return *o.ExternalShipmentCode
}

// GetExternalShipmentCodeOk returns a tuple with the ExternalShipmentCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryOperationsManagementApiCreateInventoryShipmentRequest) GetExternalShipmentCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalShipmentCode) {
		return nil, false
	}
	return o.ExternalShipmentCode, true
}

// HasExternalShipmentCode returns a boolean if a field has been set.
func (o *InventoryOperationsManagementApiCreateInventoryShipmentRequest) HasExternalShipmentCode() bool {
	if o != nil && !IsNil(o.ExternalShipmentCode) {
		return true
	}

	return false
}

// SetExternalShipmentCode gets a reference to the given string and assigns it to the ExternalShipmentCode field.
func (o *InventoryOperationsManagementApiCreateInventoryShipmentRequest) SetExternalShipmentCode(v string) {
	o.ExternalShipmentCode = &v
}

func (o InventoryOperationsManagementApiCreateInventoryShipmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InventoryOperationsManagementApiCreateInventoryShipmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ExternalShipmentCode) {
		toSerialize["externalShipmentCode"] = o.ExternalShipmentCode
	}
	return toSerialize, nil
}

type NullableInventoryOperationsManagementApiCreateInventoryShipmentRequest struct {
	value *InventoryOperationsManagementApiCreateInventoryShipmentRequest
	isSet bool
}

func (v NullableInventoryOperationsManagementApiCreateInventoryShipmentRequest) Get() *InventoryOperationsManagementApiCreateInventoryShipmentRequest {
	return v.value
}

func (v *NullableInventoryOperationsManagementApiCreateInventoryShipmentRequest) Set(val *InventoryOperationsManagementApiCreateInventoryShipmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInventoryOperationsManagementApiCreateInventoryShipmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInventoryOperationsManagementApiCreateInventoryShipmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInventoryOperationsManagementApiCreateInventoryShipmentRequest(val *InventoryOperationsManagementApiCreateInventoryShipmentRequest) *NullableInventoryOperationsManagementApiCreateInventoryShipmentRequest {
	return &NullableInventoryOperationsManagementApiCreateInventoryShipmentRequest{value: val, isSet: true}
}

func (v NullableInventoryOperationsManagementApiCreateInventoryShipmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInventoryOperationsManagementApiCreateInventoryShipmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


