/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plex

import (
	"encoding/json"
)

// checks if the KitRecommendationsApiGetKitRecommendationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KitRecommendationsApiGetKitRecommendationResponse{}

// KitRecommendationsApiGetKitRecommendationResponse struct for KitRecommendationsApiGetKitRecommendationResponse
type KitRecommendationsApiGetKitRecommendationResponse struct {
	// The Kit Recommendation ID.
	Id *string `json:"id,omitempty"`
	// The Part's ID.
	PartId *string `json:"partId,omitempty"`
	// The Part's Number.
	PartNo *string `json:"partNo,omitempty"`
	// The Part's Revision.
	PartRevision *string `json:"partRevision,omitempty"`
}

// NewKitRecommendationsApiGetKitRecommendationResponse instantiates a new KitRecommendationsApiGetKitRecommendationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKitRecommendationsApiGetKitRecommendationResponse() *KitRecommendationsApiGetKitRecommendationResponse {
	this := KitRecommendationsApiGetKitRecommendationResponse{}
	return &this
}

// NewKitRecommendationsApiGetKitRecommendationResponseWithDefaults instantiates a new KitRecommendationsApiGetKitRecommendationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKitRecommendationsApiGetKitRecommendationResponseWithDefaults() *KitRecommendationsApiGetKitRecommendationResponse {
	this := KitRecommendationsApiGetKitRecommendationResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *KitRecommendationsApiGetKitRecommendationResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KitRecommendationsApiGetKitRecommendationResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *KitRecommendationsApiGetKitRecommendationResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *KitRecommendationsApiGetKitRecommendationResponse) SetId(v string) {
	o.Id = &v
}

// GetPartId returns the PartId field value if set, zero value otherwise.
func (o *KitRecommendationsApiGetKitRecommendationResponse) GetPartId() string {
	if o == nil || IsNil(o.PartId) {
		var ret string
		return ret
	}
	return *o.PartId
}

// GetPartIdOk returns a tuple with the PartId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KitRecommendationsApiGetKitRecommendationResponse) GetPartIdOk() (*string, bool) {
	if o == nil || IsNil(o.PartId) {
		return nil, false
	}
	return o.PartId, true
}

// HasPartId returns a boolean if a field has been set.
func (o *KitRecommendationsApiGetKitRecommendationResponse) HasPartId() bool {
	if o != nil && !IsNil(o.PartId) {
		return true
	}

	return false
}

// SetPartId gets a reference to the given string and assigns it to the PartId field.
func (o *KitRecommendationsApiGetKitRecommendationResponse) SetPartId(v string) {
	o.PartId = &v
}

// GetPartNo returns the PartNo field value if set, zero value otherwise.
func (o *KitRecommendationsApiGetKitRecommendationResponse) GetPartNo() string {
	if o == nil || IsNil(o.PartNo) {
		var ret string
		return ret
	}
	return *o.PartNo
}

// GetPartNoOk returns a tuple with the PartNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KitRecommendationsApiGetKitRecommendationResponse) GetPartNoOk() (*string, bool) {
	if o == nil || IsNil(o.PartNo) {
		return nil, false
	}
	return o.PartNo, true
}

// HasPartNo returns a boolean if a field has been set.
func (o *KitRecommendationsApiGetKitRecommendationResponse) HasPartNo() bool {
	if o != nil && !IsNil(o.PartNo) {
		return true
	}

	return false
}

// SetPartNo gets a reference to the given string and assigns it to the PartNo field.
func (o *KitRecommendationsApiGetKitRecommendationResponse) SetPartNo(v string) {
	o.PartNo = &v
}

// GetPartRevision returns the PartRevision field value if set, zero value otherwise.
func (o *KitRecommendationsApiGetKitRecommendationResponse) GetPartRevision() string {
	if o == nil || IsNil(o.PartRevision) {
		var ret string
		return ret
	}
	return *o.PartRevision
}

// GetPartRevisionOk returns a tuple with the PartRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KitRecommendationsApiGetKitRecommendationResponse) GetPartRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.PartRevision) {
		return nil, false
	}
	return o.PartRevision, true
}

// HasPartRevision returns a boolean if a field has been set.
func (o *KitRecommendationsApiGetKitRecommendationResponse) HasPartRevision() bool {
	if o != nil && !IsNil(o.PartRevision) {
		return true
	}

	return false
}

// SetPartRevision gets a reference to the given string and assigns it to the PartRevision field.
func (o *KitRecommendationsApiGetKitRecommendationResponse) SetPartRevision(v string) {
	o.PartRevision = &v
}

func (o KitRecommendationsApiGetKitRecommendationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KitRecommendationsApiGetKitRecommendationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.PartId) {
		toSerialize["partId"] = o.PartId
	}
	if !IsNil(o.PartNo) {
		toSerialize["partNo"] = o.PartNo
	}
	if !IsNil(o.PartRevision) {
		toSerialize["partRevision"] = o.PartRevision
	}
	return toSerialize, nil
}

type NullableKitRecommendationsApiGetKitRecommendationResponse struct {
	value *KitRecommendationsApiGetKitRecommendationResponse
	isSet bool
}

func (v NullableKitRecommendationsApiGetKitRecommendationResponse) Get() *KitRecommendationsApiGetKitRecommendationResponse {
	return v.value
}

func (v *NullableKitRecommendationsApiGetKitRecommendationResponse) Set(val *KitRecommendationsApiGetKitRecommendationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableKitRecommendationsApiGetKitRecommendationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableKitRecommendationsApiGetKitRecommendationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKitRecommendationsApiGetKitRecommendationResponse(val *KitRecommendationsApiGetKitRecommendationResponse) *NullableKitRecommendationsApiGetKitRecommendationResponse {
	return &NullableKitRecommendationsApiGetKitRecommendationResponse{value: val, isSet: true}
}

func (v NullableKitRecommendationsApiGetKitRecommendationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKitRecommendationsApiGetKitRecommendationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


