/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plex

import (
	"encoding/json"
	"time"
)

// checks if the InventoryTrackingApiGetContainerBySerialNumberResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InventoryTrackingApiGetContainerBySerialNumberResponse{}

// InventoryTrackingApiGetContainerBySerialNumberResponse The Container model.
type InventoryTrackingApiGetContainerBySerialNumberResponse struct {
	// The serial number of the container. 25 characters max.
	SerialNumber *string `json:"serialNumber,omitempty"`
	// The container's status.
	Status *string `json:"status,omitempty"`
	// The ID of the part that was produced.
	PartId *string `json:"partId,omitempty"`
	// The part number associated to the &quot;partId&quot; that was produced. Acceptable part number characters include uppercase and lowercase letters (A-Z), numbers (0-9), and special characters such as dashes (-), underscores ( _ ), and spaces. Part numbers cannot use question marks (?) or ampersands. Other characters may cause issues.
	PartNumber *string `json:"partNumber,omitempty"`
	// The part revision of the &quot;partId&quot;. A revision represents a change or modification to a part or part drawing that is usually initiated through an engineering change request (ECR).
	PartRevision *string `json:"partRevision,omitempty"`
	// The part number and revision formatted with separator. If a part number has a revision, Plex will return the part number and the revision separated by the Part Rev Separator setting. A Part Rev Separator can be up to 5 characters long. Format: {partNumber}{part rev separator}{revision}.
	PartNumberRevision *string `json:"partNumberRevision,omitempty"`
	// The ID of the part operation.
	PartOperationId *string `json:"partOperationId,omitempty"`
	// The operation number of the part operation.
	OperationNumber *int32 `json:"operationNumber,omitempty"`
	// The operation code associated to the &quot;partOperationId&quot;. 30 characters max.
	OperationCode *string `json:"operationCode,omitempty"`
	// The container's location.
	Location *string `json:"location,omitempty"`
	// The unique job number. 20 characters max.
	JobNumber *string `json:"jobNumber,omitempty"`
	// The ID of the production job that production was recorded against. Note that a production job is not necessary to record production. Another scheduling method such as Kanban may have been used.
	JobId *string `json:"jobId,omitempty"`
	// The container type of the container's.
	Type *string `json:"type,omitempty"`
	// The container's part quantity.
	Quantity *float64 `json:"quantity,omitempty"`
	// The container's active status (active or inactive).
	Active *bool `json:"active,omitempty"`
	// The date on which the container record was added.
	CreatedDate *time.Time `json:"createdDate,omitempty"`
	// The date on which the container record was updated.
	ModifiedDate *time.Time `json:"modifiedDate,omitempty"`
	// The unit used for the container quantity, as defined on the operation.
	QuantityUnit *string `json:"quantityUnit,omitempty"`
	// The container's gross weight.
	GrossWeight *float64 `json:"grossWeight,omitempty"`
	// The container's net weight.
	NetWeight *float64 `json:"netWeight,omitempty"`
	// The container's tare weight.
	TareWeight *float64 `json:"tareWeight,omitempty"`
	// The tracking number of the container. 50 characters max.
	TrackingNumber *string `json:"trackingNumber,omitempty"`
	// The heat number of the heat. 30 characters max.
	HeatNumber *string `json:"heatNumber,omitempty"`
	// The unique lot number. 25 characters max.
	LotNumber *string `json:"lotNumber,omitempty"`
	// The master unit number of the master unit. 10 characters max.
	MasterUnitNo *string `json:"masterUnitNo,omitempty"`
	// The master unit resource ID.
	MasterUnitId *string `json:"masterUnitId,omitempty"`
	// The lot resource ID.
	LotId *string `json:"lotId,omitempty"`
	// The heat code of the heat. 50 characters max.
	HeatCode *string `json:"heatCode,omitempty"`
	// The material heat resource ID.
	HeatId *string `json:"heatId,omitempty"`
	// The shelf life date of the container.
	ShelfDateTime *time.Time `json:"shelfDateTime,omitempty"`
	// The date a lot was manufactured, either in Plex or by a supplier or subcontractor.
	ManufacturedDateTime *time.Time `json:"manufacturedDateTime,omitempty"`
	// The best-by date which represents the last date for consumption of products in a lot by consumers.
	BestByDateTime *time.Time `json:"bestByDateTime,omitempty"`
	// The last date to use a lot for production.
	UseByDateTime *time.Time `json:"useByDateTime,omitempty"`
	// The last date for the sale of a product in a lot to consumers.
	SellByDateTime *time.Time `json:"sellByDateTime,omitempty"`
	// The RFID of the container. Maximum length is 64 characters.
	Rfid *string `json:"rfid,omitempty"`
}

// NewInventoryTrackingApiGetContainerBySerialNumberResponse instantiates a new InventoryTrackingApiGetContainerBySerialNumberResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInventoryTrackingApiGetContainerBySerialNumberResponse() *InventoryTrackingApiGetContainerBySerialNumberResponse {
	this := InventoryTrackingApiGetContainerBySerialNumberResponse{}
	return &this
}

// NewInventoryTrackingApiGetContainerBySerialNumberResponseWithDefaults instantiates a new InventoryTrackingApiGetContainerBySerialNumberResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInventoryTrackingApiGetContainerBySerialNumberResponseWithDefaults() *InventoryTrackingApiGetContainerBySerialNumberResponse {
	this := InventoryTrackingApiGetContainerBySerialNumberResponse{}
	return &this
}

// GetSerialNumber returns the SerialNumber field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetSerialNumber() string {
	if o == nil || IsNil(o.SerialNumber) {
		var ret string
		return ret
	}
	return *o.SerialNumber
}

// GetSerialNumberOk returns a tuple with the SerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetSerialNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SerialNumber) {
		return nil, false
	}
	return o.SerialNumber, true
}

// HasSerialNumber returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasSerialNumber() bool {
	if o != nil && !IsNil(o.SerialNumber) {
		return true
	}

	return false
}

// SetSerialNumber gets a reference to the given string and assigns it to the SerialNumber field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetSerialNumber(v string) {
	o.SerialNumber = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetStatus(v string) {
	o.Status = &v
}

// GetPartId returns the PartId field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetPartId() string {
	if o == nil || IsNil(o.PartId) {
		var ret string
		return ret
	}
	return *o.PartId
}

// GetPartIdOk returns a tuple with the PartId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetPartIdOk() (*string, bool) {
	if o == nil || IsNil(o.PartId) {
		return nil, false
	}
	return o.PartId, true
}

// HasPartId returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasPartId() bool {
	if o != nil && !IsNil(o.PartId) {
		return true
	}

	return false
}

// SetPartId gets a reference to the given string and assigns it to the PartId field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetPartId(v string) {
	o.PartId = &v
}

// GetPartNumber returns the PartNumber field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetPartNumber() string {
	if o == nil || IsNil(o.PartNumber) {
		var ret string
		return ret
	}
	return *o.PartNumber
}

// GetPartNumberOk returns a tuple with the PartNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetPartNumberOk() (*string, bool) {
	if o == nil || IsNil(o.PartNumber) {
		return nil, false
	}
	return o.PartNumber, true
}

// HasPartNumber returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasPartNumber() bool {
	if o != nil && !IsNil(o.PartNumber) {
		return true
	}

	return false
}

// SetPartNumber gets a reference to the given string and assigns it to the PartNumber field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetPartNumber(v string) {
	o.PartNumber = &v
}

// GetPartRevision returns the PartRevision field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetPartRevision() string {
	if o == nil || IsNil(o.PartRevision) {
		var ret string
		return ret
	}
	return *o.PartRevision
}

// GetPartRevisionOk returns a tuple with the PartRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetPartRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.PartRevision) {
		return nil, false
	}
	return o.PartRevision, true
}

// HasPartRevision returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasPartRevision() bool {
	if o != nil && !IsNil(o.PartRevision) {
		return true
	}

	return false
}

// SetPartRevision gets a reference to the given string and assigns it to the PartRevision field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetPartRevision(v string) {
	o.PartRevision = &v
}

// GetPartNumberRevision returns the PartNumberRevision field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetPartNumberRevision() string {
	if o == nil || IsNil(o.PartNumberRevision) {
		var ret string
		return ret
	}
	return *o.PartNumberRevision
}

// GetPartNumberRevisionOk returns a tuple with the PartNumberRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetPartNumberRevisionOk() (*string, bool) {
	if o == nil || IsNil(o.PartNumberRevision) {
		return nil, false
	}
	return o.PartNumberRevision, true
}

// HasPartNumberRevision returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasPartNumberRevision() bool {
	if o != nil && !IsNil(o.PartNumberRevision) {
		return true
	}

	return false
}

// SetPartNumberRevision gets a reference to the given string and assigns it to the PartNumberRevision field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetPartNumberRevision(v string) {
	o.PartNumberRevision = &v
}

// GetPartOperationId returns the PartOperationId field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetPartOperationId() string {
	if o == nil || IsNil(o.PartOperationId) {
		var ret string
		return ret
	}
	return *o.PartOperationId
}

// GetPartOperationIdOk returns a tuple with the PartOperationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetPartOperationIdOk() (*string, bool) {
	if o == nil || IsNil(o.PartOperationId) {
		return nil, false
	}
	return o.PartOperationId, true
}

// HasPartOperationId returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasPartOperationId() bool {
	if o != nil && !IsNil(o.PartOperationId) {
		return true
	}

	return false
}

// SetPartOperationId gets a reference to the given string and assigns it to the PartOperationId field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetPartOperationId(v string) {
	o.PartOperationId = &v
}

// GetOperationNumber returns the OperationNumber field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetOperationNumber() int32 {
	if o == nil || IsNil(o.OperationNumber) {
		var ret int32
		return ret
	}
	return *o.OperationNumber
}

// GetOperationNumberOk returns a tuple with the OperationNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetOperationNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.OperationNumber) {
		return nil, false
	}
	return o.OperationNumber, true
}

// HasOperationNumber returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasOperationNumber() bool {
	if o != nil && !IsNil(o.OperationNumber) {
		return true
	}

	return false
}

// SetOperationNumber gets a reference to the given int32 and assigns it to the OperationNumber field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetOperationNumber(v int32) {
	o.OperationNumber = &v
}

// GetOperationCode returns the OperationCode field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetOperationCode() string {
	if o == nil || IsNil(o.OperationCode) {
		var ret string
		return ret
	}
	return *o.OperationCode
}

// GetOperationCodeOk returns a tuple with the OperationCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetOperationCodeOk() (*string, bool) {
	if o == nil || IsNil(o.OperationCode) {
		return nil, false
	}
	return o.OperationCode, true
}

// HasOperationCode returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasOperationCode() bool {
	if o != nil && !IsNil(o.OperationCode) {
		return true
	}

	return false
}

// SetOperationCode gets a reference to the given string and assigns it to the OperationCode field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetOperationCode(v string) {
	o.OperationCode = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetLocation(v string) {
	o.Location = &v
}

// GetJobNumber returns the JobNumber field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetJobNumber() string {
	if o == nil || IsNil(o.JobNumber) {
		var ret string
		return ret
	}
	return *o.JobNumber
}

// GetJobNumberOk returns a tuple with the JobNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetJobNumberOk() (*string, bool) {
	if o == nil || IsNil(o.JobNumber) {
		return nil, false
	}
	return o.JobNumber, true
}

// HasJobNumber returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasJobNumber() bool {
	if o != nil && !IsNil(o.JobNumber) {
		return true
	}

	return false
}

// SetJobNumber gets a reference to the given string and assigns it to the JobNumber field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetJobNumber(v string) {
	o.JobNumber = &v
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetJobId() string {
	if o == nil || IsNil(o.JobId) {
		var ret string
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetJobIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobId) {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasJobId() bool {
	if o != nil && !IsNil(o.JobId) {
		return true
	}

	return false
}

// SetJobId gets a reference to the given string and assigns it to the JobId field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetJobId(v string) {
	o.JobId = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetType(v string) {
	o.Type = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetQuantity() float64 {
	if o == nil || IsNil(o.Quantity) {
		var ret float64
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetQuantityOk() (*float64, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given float64 and assigns it to the Quantity field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetQuantity(v float64) {
	o.Quantity = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetActive(v bool) {
	o.Active = &v
}

// GetCreatedDate returns the CreatedDate field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetCreatedDate() time.Time {
	if o == nil || IsNil(o.CreatedDate) {
		var ret time.Time
		return ret
	}
	return *o.CreatedDate
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetCreatedDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedDate) {
		return nil, false
	}
	return o.CreatedDate, true
}

// HasCreatedDate returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasCreatedDate() bool {
	if o != nil && !IsNil(o.CreatedDate) {
		return true
	}

	return false
}

// SetCreatedDate gets a reference to the given time.Time and assigns it to the CreatedDate field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetCreatedDate(v time.Time) {
	o.CreatedDate = &v
}

// GetModifiedDate returns the ModifiedDate field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetModifiedDate() time.Time {
	if o == nil || IsNil(o.ModifiedDate) {
		var ret time.Time
		return ret
	}
	return *o.ModifiedDate
}

// GetModifiedDateOk returns a tuple with the ModifiedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetModifiedDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ModifiedDate) {
		return nil, false
	}
	return o.ModifiedDate, true
}

// HasModifiedDate returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasModifiedDate() bool {
	if o != nil && !IsNil(o.ModifiedDate) {
		return true
	}

	return false
}

// SetModifiedDate gets a reference to the given time.Time and assigns it to the ModifiedDate field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetModifiedDate(v time.Time) {
	o.ModifiedDate = &v
}

// GetQuantityUnit returns the QuantityUnit field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetQuantityUnit() string {
	if o == nil || IsNil(o.QuantityUnit) {
		var ret string
		return ret
	}
	return *o.QuantityUnit
}

// GetQuantityUnitOk returns a tuple with the QuantityUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetQuantityUnitOk() (*string, bool) {
	if o == nil || IsNil(o.QuantityUnit) {
		return nil, false
	}
	return o.QuantityUnit, true
}

// HasQuantityUnit returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasQuantityUnit() bool {
	if o != nil && !IsNil(o.QuantityUnit) {
		return true
	}

	return false
}

// SetQuantityUnit gets a reference to the given string and assigns it to the QuantityUnit field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetQuantityUnit(v string) {
	o.QuantityUnit = &v
}

// GetGrossWeight returns the GrossWeight field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetGrossWeight() float64 {
	if o == nil || IsNil(o.GrossWeight) {
		var ret float64
		return ret
	}
	return *o.GrossWeight
}

// GetGrossWeightOk returns a tuple with the GrossWeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetGrossWeightOk() (*float64, bool) {
	if o == nil || IsNil(o.GrossWeight) {
		return nil, false
	}
	return o.GrossWeight, true
}

// HasGrossWeight returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasGrossWeight() bool {
	if o != nil && !IsNil(o.GrossWeight) {
		return true
	}

	return false
}

// SetGrossWeight gets a reference to the given float64 and assigns it to the GrossWeight field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetGrossWeight(v float64) {
	o.GrossWeight = &v
}

// GetNetWeight returns the NetWeight field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetNetWeight() float64 {
	if o == nil || IsNil(o.NetWeight) {
		var ret float64
		return ret
	}
	return *o.NetWeight
}

// GetNetWeightOk returns a tuple with the NetWeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetNetWeightOk() (*float64, bool) {
	if o == nil || IsNil(o.NetWeight) {
		return nil, false
	}
	return o.NetWeight, true
}

// HasNetWeight returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasNetWeight() bool {
	if o != nil && !IsNil(o.NetWeight) {
		return true
	}

	return false
}

// SetNetWeight gets a reference to the given float64 and assigns it to the NetWeight field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetNetWeight(v float64) {
	o.NetWeight = &v
}

// GetTareWeight returns the TareWeight field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetTareWeight() float64 {
	if o == nil || IsNil(o.TareWeight) {
		var ret float64
		return ret
	}
	return *o.TareWeight
}

// GetTareWeightOk returns a tuple with the TareWeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetTareWeightOk() (*float64, bool) {
	if o == nil || IsNil(o.TareWeight) {
		return nil, false
	}
	return o.TareWeight, true
}

// HasTareWeight returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasTareWeight() bool {
	if o != nil && !IsNil(o.TareWeight) {
		return true
	}

	return false
}

// SetTareWeight gets a reference to the given float64 and assigns it to the TareWeight field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetTareWeight(v float64) {
	o.TareWeight = &v
}

// GetTrackingNumber returns the TrackingNumber field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetTrackingNumber() string {
	if o == nil || IsNil(o.TrackingNumber) {
		var ret string
		return ret
	}
	return *o.TrackingNumber
}

// GetTrackingNumberOk returns a tuple with the TrackingNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetTrackingNumberOk() (*string, bool) {
	if o == nil || IsNil(o.TrackingNumber) {
		return nil, false
	}
	return o.TrackingNumber, true
}

// HasTrackingNumber returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasTrackingNumber() bool {
	if o != nil && !IsNil(o.TrackingNumber) {
		return true
	}

	return false
}

// SetTrackingNumber gets a reference to the given string and assigns it to the TrackingNumber field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetTrackingNumber(v string) {
	o.TrackingNumber = &v
}

// GetHeatNumber returns the HeatNumber field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetHeatNumber() string {
	if o == nil || IsNil(o.HeatNumber) {
		var ret string
		return ret
	}
	return *o.HeatNumber
}

// GetHeatNumberOk returns a tuple with the HeatNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetHeatNumberOk() (*string, bool) {
	if o == nil || IsNil(o.HeatNumber) {
		return nil, false
	}
	return o.HeatNumber, true
}

// HasHeatNumber returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasHeatNumber() bool {
	if o != nil && !IsNil(o.HeatNumber) {
		return true
	}

	return false
}

// SetHeatNumber gets a reference to the given string and assigns it to the HeatNumber field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetHeatNumber(v string) {
	o.HeatNumber = &v
}

// GetLotNumber returns the LotNumber field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetLotNumber() string {
	if o == nil || IsNil(o.LotNumber) {
		var ret string
		return ret
	}
	return *o.LotNumber
}

// GetLotNumberOk returns a tuple with the LotNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetLotNumberOk() (*string, bool) {
	if o == nil || IsNil(o.LotNumber) {
		return nil, false
	}
	return o.LotNumber, true
}

// HasLotNumber returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasLotNumber() bool {
	if o != nil && !IsNil(o.LotNumber) {
		return true
	}

	return false
}

// SetLotNumber gets a reference to the given string and assigns it to the LotNumber field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetLotNumber(v string) {
	o.LotNumber = &v
}

// GetMasterUnitNo returns the MasterUnitNo field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetMasterUnitNo() string {
	if o == nil || IsNil(o.MasterUnitNo) {
		var ret string
		return ret
	}
	return *o.MasterUnitNo
}

// GetMasterUnitNoOk returns a tuple with the MasterUnitNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetMasterUnitNoOk() (*string, bool) {
	if o == nil || IsNil(o.MasterUnitNo) {
		return nil, false
	}
	return o.MasterUnitNo, true
}

// HasMasterUnitNo returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasMasterUnitNo() bool {
	if o != nil && !IsNil(o.MasterUnitNo) {
		return true
	}

	return false
}

// SetMasterUnitNo gets a reference to the given string and assigns it to the MasterUnitNo field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetMasterUnitNo(v string) {
	o.MasterUnitNo = &v
}

// GetMasterUnitId returns the MasterUnitId field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetMasterUnitId() string {
	if o == nil || IsNil(o.MasterUnitId) {
		var ret string
		return ret
	}
	return *o.MasterUnitId
}

// GetMasterUnitIdOk returns a tuple with the MasterUnitId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetMasterUnitIdOk() (*string, bool) {
	if o == nil || IsNil(o.MasterUnitId) {
		return nil, false
	}
	return o.MasterUnitId, true
}

// HasMasterUnitId returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasMasterUnitId() bool {
	if o != nil && !IsNil(o.MasterUnitId) {
		return true
	}

	return false
}

// SetMasterUnitId gets a reference to the given string and assigns it to the MasterUnitId field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetMasterUnitId(v string) {
	o.MasterUnitId = &v
}

// GetLotId returns the LotId field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetLotId() string {
	if o == nil || IsNil(o.LotId) {
		var ret string
		return ret
	}
	return *o.LotId
}

// GetLotIdOk returns a tuple with the LotId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetLotIdOk() (*string, bool) {
	if o == nil || IsNil(o.LotId) {
		return nil, false
	}
	return o.LotId, true
}

// HasLotId returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasLotId() bool {
	if o != nil && !IsNil(o.LotId) {
		return true
	}

	return false
}

// SetLotId gets a reference to the given string and assigns it to the LotId field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetLotId(v string) {
	o.LotId = &v
}

// GetHeatCode returns the HeatCode field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetHeatCode() string {
	if o == nil || IsNil(o.HeatCode) {
		var ret string
		return ret
	}
	return *o.HeatCode
}

// GetHeatCodeOk returns a tuple with the HeatCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetHeatCodeOk() (*string, bool) {
	if o == nil || IsNil(o.HeatCode) {
		return nil, false
	}
	return o.HeatCode, true
}

// HasHeatCode returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasHeatCode() bool {
	if o != nil && !IsNil(o.HeatCode) {
		return true
	}

	return false
}

// SetHeatCode gets a reference to the given string and assigns it to the HeatCode field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetHeatCode(v string) {
	o.HeatCode = &v
}

// GetHeatId returns the HeatId field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetHeatId() string {
	if o == nil || IsNil(o.HeatId) {
		var ret string
		return ret
	}
	return *o.HeatId
}

// GetHeatIdOk returns a tuple with the HeatId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetHeatIdOk() (*string, bool) {
	if o == nil || IsNil(o.HeatId) {
		return nil, false
	}
	return o.HeatId, true
}

// HasHeatId returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasHeatId() bool {
	if o != nil && !IsNil(o.HeatId) {
		return true
	}

	return false
}

// SetHeatId gets a reference to the given string and assigns it to the HeatId field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetHeatId(v string) {
	o.HeatId = &v
}

// GetShelfDateTime returns the ShelfDateTime field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetShelfDateTime() time.Time {
	if o == nil || IsNil(o.ShelfDateTime) {
		var ret time.Time
		return ret
	}
	return *o.ShelfDateTime
}

// GetShelfDateTimeOk returns a tuple with the ShelfDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetShelfDateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ShelfDateTime) {
		return nil, false
	}
	return o.ShelfDateTime, true
}

// HasShelfDateTime returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasShelfDateTime() bool {
	if o != nil && !IsNil(o.ShelfDateTime) {
		return true
	}

	return false
}

// SetShelfDateTime gets a reference to the given time.Time and assigns it to the ShelfDateTime field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetShelfDateTime(v time.Time) {
	o.ShelfDateTime = &v
}

// GetManufacturedDateTime returns the ManufacturedDateTime field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetManufacturedDateTime() time.Time {
	if o == nil || IsNil(o.ManufacturedDateTime) {
		var ret time.Time
		return ret
	}
	return *o.ManufacturedDateTime
}

// GetManufacturedDateTimeOk returns a tuple with the ManufacturedDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetManufacturedDateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ManufacturedDateTime) {
		return nil, false
	}
	return o.ManufacturedDateTime, true
}

// HasManufacturedDateTime returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasManufacturedDateTime() bool {
	if o != nil && !IsNil(o.ManufacturedDateTime) {
		return true
	}

	return false
}

// SetManufacturedDateTime gets a reference to the given time.Time and assigns it to the ManufacturedDateTime field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetManufacturedDateTime(v time.Time) {
	o.ManufacturedDateTime = &v
}

// GetBestByDateTime returns the BestByDateTime field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetBestByDateTime() time.Time {
	if o == nil || IsNil(o.BestByDateTime) {
		var ret time.Time
		return ret
	}
	return *o.BestByDateTime
}

// GetBestByDateTimeOk returns a tuple with the BestByDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetBestByDateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.BestByDateTime) {
		return nil, false
	}
	return o.BestByDateTime, true
}

// HasBestByDateTime returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasBestByDateTime() bool {
	if o != nil && !IsNil(o.BestByDateTime) {
		return true
	}

	return false
}

// SetBestByDateTime gets a reference to the given time.Time and assigns it to the BestByDateTime field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetBestByDateTime(v time.Time) {
	o.BestByDateTime = &v
}

// GetUseByDateTime returns the UseByDateTime field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetUseByDateTime() time.Time {
	if o == nil || IsNil(o.UseByDateTime) {
		var ret time.Time
		return ret
	}
	return *o.UseByDateTime
}

// GetUseByDateTimeOk returns a tuple with the UseByDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetUseByDateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UseByDateTime) {
		return nil, false
	}
	return o.UseByDateTime, true
}

// HasUseByDateTime returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasUseByDateTime() bool {
	if o != nil && !IsNil(o.UseByDateTime) {
		return true
	}

	return false
}

// SetUseByDateTime gets a reference to the given time.Time and assigns it to the UseByDateTime field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetUseByDateTime(v time.Time) {
	o.UseByDateTime = &v
}

// GetSellByDateTime returns the SellByDateTime field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetSellByDateTime() time.Time {
	if o == nil || IsNil(o.SellByDateTime) {
		var ret time.Time
		return ret
	}
	return *o.SellByDateTime
}

// GetSellByDateTimeOk returns a tuple with the SellByDateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetSellByDateTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.SellByDateTime) {
		return nil, false
	}
	return o.SellByDateTime, true
}

// HasSellByDateTime returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasSellByDateTime() bool {
	if o != nil && !IsNil(o.SellByDateTime) {
		return true
	}

	return false
}

// SetSellByDateTime gets a reference to the given time.Time and assigns it to the SellByDateTime field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetSellByDateTime(v time.Time) {
	o.SellByDateTime = &v
}

// GetRfid returns the Rfid field value if set, zero value otherwise.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetRfid() string {
	if o == nil || IsNil(o.Rfid) {
		var ret string
		return ret
	}
	return *o.Rfid
}

// GetRfidOk returns a tuple with the Rfid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) GetRfidOk() (*string, bool) {
	if o == nil || IsNil(o.Rfid) {
		return nil, false
	}
	return o.Rfid, true
}

// HasRfid returns a boolean if a field has been set.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) HasRfid() bool {
	if o != nil && !IsNil(o.Rfid) {
		return true
	}

	return false
}

// SetRfid gets a reference to the given string and assigns it to the Rfid field.
func (o *InventoryTrackingApiGetContainerBySerialNumberResponse) SetRfid(v string) {
	o.Rfid = &v
}

func (o InventoryTrackingApiGetContainerBySerialNumberResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InventoryTrackingApiGetContainerBySerialNumberResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SerialNumber) {
		toSerialize["serialNumber"] = o.SerialNumber
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.PartId) {
		toSerialize["partId"] = o.PartId
	}
	if !IsNil(o.PartNumber) {
		toSerialize["partNumber"] = o.PartNumber
	}
	if !IsNil(o.PartRevision) {
		toSerialize["partRevision"] = o.PartRevision
	}
	if !IsNil(o.PartNumberRevision) {
		toSerialize["partNumberRevision"] = o.PartNumberRevision
	}
	if !IsNil(o.PartOperationId) {
		toSerialize["partOperationId"] = o.PartOperationId
	}
	if !IsNil(o.OperationNumber) {
		toSerialize["operationNumber"] = o.OperationNumber
	}
	if !IsNil(o.OperationCode) {
		toSerialize["operationCode"] = o.OperationCode
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.JobNumber) {
		toSerialize["jobNumber"] = o.JobNumber
	}
	if !IsNil(o.JobId) {
		toSerialize["jobId"] = o.JobId
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.CreatedDate) {
		toSerialize["createdDate"] = o.CreatedDate
	}
	if !IsNil(o.ModifiedDate) {
		toSerialize["modifiedDate"] = o.ModifiedDate
	}
	if !IsNil(o.QuantityUnit) {
		toSerialize["quantityUnit"] = o.QuantityUnit
	}
	if !IsNil(o.GrossWeight) {
		toSerialize["grossWeight"] = o.GrossWeight
	}
	if !IsNil(o.NetWeight) {
		toSerialize["netWeight"] = o.NetWeight
	}
	if !IsNil(o.TareWeight) {
		toSerialize["tareWeight"] = o.TareWeight
	}
	if !IsNil(o.TrackingNumber) {
		toSerialize["trackingNumber"] = o.TrackingNumber
	}
	if !IsNil(o.HeatNumber) {
		toSerialize["heatNumber"] = o.HeatNumber
	}
	if !IsNil(o.LotNumber) {
		toSerialize["lotNumber"] = o.LotNumber
	}
	if !IsNil(o.MasterUnitNo) {
		toSerialize["masterUnitNo"] = o.MasterUnitNo
	}
	if !IsNil(o.MasterUnitId) {
		toSerialize["masterUnitId"] = o.MasterUnitId
	}
	if !IsNil(o.LotId) {
		toSerialize["lotId"] = o.LotId
	}
	if !IsNil(o.HeatCode) {
		toSerialize["heatCode"] = o.HeatCode
	}
	if !IsNil(o.HeatId) {
		toSerialize["heatId"] = o.HeatId
	}
	if !IsNil(o.ShelfDateTime) {
		toSerialize["shelfDateTime"] = o.ShelfDateTime
	}
	if !IsNil(o.ManufacturedDateTime) {
		toSerialize["manufacturedDateTime"] = o.ManufacturedDateTime
	}
	if !IsNil(o.BestByDateTime) {
		toSerialize["bestByDateTime"] = o.BestByDateTime
	}
	if !IsNil(o.UseByDateTime) {
		toSerialize["useByDateTime"] = o.UseByDateTime
	}
	if !IsNil(o.SellByDateTime) {
		toSerialize["sellByDateTime"] = o.SellByDateTime
	}
	if !IsNil(o.Rfid) {
		toSerialize["rfid"] = o.Rfid
	}
	return toSerialize, nil
}

type NullableInventoryTrackingApiGetContainerBySerialNumberResponse struct {
	value *InventoryTrackingApiGetContainerBySerialNumberResponse
	isSet bool
}

func (v NullableInventoryTrackingApiGetContainerBySerialNumberResponse) Get() *InventoryTrackingApiGetContainerBySerialNumberResponse {
	return v.value
}

func (v *NullableInventoryTrackingApiGetContainerBySerialNumberResponse) Set(val *InventoryTrackingApiGetContainerBySerialNumberResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInventoryTrackingApiGetContainerBySerialNumberResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInventoryTrackingApiGetContainerBySerialNumberResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInventoryTrackingApiGetContainerBySerialNumberResponse(val *InventoryTrackingApiGetContainerBySerialNumberResponse) *NullableInventoryTrackingApiGetContainerBySerialNumberResponse {
	return &NullableInventoryTrackingApiGetContainerBySerialNumberResponse{value: val, isSet: true}
}

func (v NullableInventoryTrackingApiGetContainerBySerialNumberResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInventoryTrackingApiGetContainerBySerialNumberResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


