/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plex

import (
	"encoding/json"
)

// checks if the ApprovedSuppliersApiListApprovedSuppliersItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApprovedSuppliersApiListApprovedSuppliersItem{}

// ApprovedSuppliersApiListApprovedSuppliersItem The Approved Supplier model.
type ApprovedSuppliersApiListApprovedSuppliersItem struct {
	// A unique identifier for the Approved Supplier.
	Id *string `json:"id,omitempty"`
	// The part ID.
	PartId *string `json:"partId,omitempty"`
	// Application: Operation List
	OperationCode *string `json:"operationCode,omitempty"`
	// The supplier ID.
	SupplierId *string `json:"supplierId,omitempty"`
	// Estimated lead time
	LeadTime *float64 `json:"leadTime,omitempty"`
	// The part number used by the Supplier.
	SupplierPartNumber *string `json:"supplierPartNumber,omitempty"`
	// The business percentage for the approved supplier.
	BusinessPercentage *float64 `json:"businessPercentage,omitempty"`
	// Estimated transit time.
	TransitTime *float64 `json:"transitTime,omitempty"`
	// The approved supplier note.
	Note *string `json:"note,omitempty"`
	// The part operation ID.
	PartOperationId *string `json:"partOperationId,omitempty"`
}

// NewApprovedSuppliersApiListApprovedSuppliersItem instantiates a new ApprovedSuppliersApiListApprovedSuppliersItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApprovedSuppliersApiListApprovedSuppliersItem() *ApprovedSuppliersApiListApprovedSuppliersItem {
	this := ApprovedSuppliersApiListApprovedSuppliersItem{}
	return &this
}

// NewApprovedSuppliersApiListApprovedSuppliersItemWithDefaults instantiates a new ApprovedSuppliersApiListApprovedSuppliersItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApprovedSuppliersApiListApprovedSuppliersItemWithDefaults() *ApprovedSuppliersApiListApprovedSuppliersItem {
	this := ApprovedSuppliersApiListApprovedSuppliersItem{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) SetId(v string) {
	o.Id = &v
}

// GetPartId returns the PartId field value if set, zero value otherwise.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) GetPartId() string {
	if o == nil || IsNil(o.PartId) {
		var ret string
		return ret
	}
	return *o.PartId
}

// GetPartIdOk returns a tuple with the PartId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) GetPartIdOk() (*string, bool) {
	if o == nil || IsNil(o.PartId) {
		return nil, false
	}
	return o.PartId, true
}

// HasPartId returns a boolean if a field has been set.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) HasPartId() bool {
	if o != nil && !IsNil(o.PartId) {
		return true
	}

	return false
}

// SetPartId gets a reference to the given string and assigns it to the PartId field.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) SetPartId(v string) {
	o.PartId = &v
}

// GetOperationCode returns the OperationCode field value if set, zero value otherwise.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) GetOperationCode() string {
	if o == nil || IsNil(o.OperationCode) {
		var ret string
		return ret
	}
	return *o.OperationCode
}

// GetOperationCodeOk returns a tuple with the OperationCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) GetOperationCodeOk() (*string, bool) {
	if o == nil || IsNil(o.OperationCode) {
		return nil, false
	}
	return o.OperationCode, true
}

// HasOperationCode returns a boolean if a field has been set.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) HasOperationCode() bool {
	if o != nil && !IsNil(o.OperationCode) {
		return true
	}

	return false
}

// SetOperationCode gets a reference to the given string and assigns it to the OperationCode field.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) SetOperationCode(v string) {
	o.OperationCode = &v
}

// GetSupplierId returns the SupplierId field value if set, zero value otherwise.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) GetSupplierId() string {
	if o == nil || IsNil(o.SupplierId) {
		var ret string
		return ret
	}
	return *o.SupplierId
}

// GetSupplierIdOk returns a tuple with the SupplierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) GetSupplierIdOk() (*string, bool) {
	if o == nil || IsNil(o.SupplierId) {
		return nil, false
	}
	return o.SupplierId, true
}

// HasSupplierId returns a boolean if a field has been set.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) HasSupplierId() bool {
	if o != nil && !IsNil(o.SupplierId) {
		return true
	}

	return false
}

// SetSupplierId gets a reference to the given string and assigns it to the SupplierId field.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) SetSupplierId(v string) {
	o.SupplierId = &v
}

// GetLeadTime returns the LeadTime field value if set, zero value otherwise.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) GetLeadTime() float64 {
	if o == nil || IsNil(o.LeadTime) {
		var ret float64
		return ret
	}
	return *o.LeadTime
}

// GetLeadTimeOk returns a tuple with the LeadTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) GetLeadTimeOk() (*float64, bool) {
	if o == nil || IsNil(o.LeadTime) {
		return nil, false
	}
	return o.LeadTime, true
}

// HasLeadTime returns a boolean if a field has been set.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) HasLeadTime() bool {
	if o != nil && !IsNil(o.LeadTime) {
		return true
	}

	return false
}

// SetLeadTime gets a reference to the given float64 and assigns it to the LeadTime field.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) SetLeadTime(v float64) {
	o.LeadTime = &v
}

// GetSupplierPartNumber returns the SupplierPartNumber field value if set, zero value otherwise.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) GetSupplierPartNumber() string {
	if o == nil || IsNil(o.SupplierPartNumber) {
		var ret string
		return ret
	}
	return *o.SupplierPartNumber
}

// GetSupplierPartNumberOk returns a tuple with the SupplierPartNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) GetSupplierPartNumberOk() (*string, bool) {
	if o == nil || IsNil(o.SupplierPartNumber) {
		return nil, false
	}
	return o.SupplierPartNumber, true
}

// HasSupplierPartNumber returns a boolean if a field has been set.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) HasSupplierPartNumber() bool {
	if o != nil && !IsNil(o.SupplierPartNumber) {
		return true
	}

	return false
}

// SetSupplierPartNumber gets a reference to the given string and assigns it to the SupplierPartNumber field.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) SetSupplierPartNumber(v string) {
	o.SupplierPartNumber = &v
}

// GetBusinessPercentage returns the BusinessPercentage field value if set, zero value otherwise.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) GetBusinessPercentage() float64 {
	if o == nil || IsNil(o.BusinessPercentage) {
		var ret float64
		return ret
	}
	return *o.BusinessPercentage
}

// GetBusinessPercentageOk returns a tuple with the BusinessPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) GetBusinessPercentageOk() (*float64, bool) {
	if o == nil || IsNil(o.BusinessPercentage) {
		return nil, false
	}
	return o.BusinessPercentage, true
}

// HasBusinessPercentage returns a boolean if a field has been set.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) HasBusinessPercentage() bool {
	if o != nil && !IsNil(o.BusinessPercentage) {
		return true
	}

	return false
}

// SetBusinessPercentage gets a reference to the given float64 and assigns it to the BusinessPercentage field.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) SetBusinessPercentage(v float64) {
	o.BusinessPercentage = &v
}

// GetTransitTime returns the TransitTime field value if set, zero value otherwise.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) GetTransitTime() float64 {
	if o == nil || IsNil(o.TransitTime) {
		var ret float64
		return ret
	}
	return *o.TransitTime
}

// GetTransitTimeOk returns a tuple with the TransitTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) GetTransitTimeOk() (*float64, bool) {
	if o == nil || IsNil(o.TransitTime) {
		return nil, false
	}
	return o.TransitTime, true
}

// HasTransitTime returns a boolean if a field has been set.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) HasTransitTime() bool {
	if o != nil && !IsNil(o.TransitTime) {
		return true
	}

	return false
}

// SetTransitTime gets a reference to the given float64 and assigns it to the TransitTime field.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) SetTransitTime(v float64) {
	o.TransitTime = &v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) GetNote() string {
	if o == nil || IsNil(o.Note) {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) GetNoteOk() (*string, bool) {
	if o == nil || IsNil(o.Note) {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) HasNote() bool {
	if o != nil && !IsNil(o.Note) {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) SetNote(v string) {
	o.Note = &v
}

// GetPartOperationId returns the PartOperationId field value if set, zero value otherwise.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) GetPartOperationId() string {
	if o == nil || IsNil(o.PartOperationId) {
		var ret string
		return ret
	}
	return *o.PartOperationId
}

// GetPartOperationIdOk returns a tuple with the PartOperationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) GetPartOperationIdOk() (*string, bool) {
	if o == nil || IsNil(o.PartOperationId) {
		return nil, false
	}
	return o.PartOperationId, true
}

// HasPartOperationId returns a boolean if a field has been set.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) HasPartOperationId() bool {
	if o != nil && !IsNil(o.PartOperationId) {
		return true
	}

	return false
}

// SetPartOperationId gets a reference to the given string and assigns it to the PartOperationId field.
func (o *ApprovedSuppliersApiListApprovedSuppliersItem) SetPartOperationId(v string) {
	o.PartOperationId = &v
}

func (o ApprovedSuppliersApiListApprovedSuppliersItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApprovedSuppliersApiListApprovedSuppliersItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.PartId) {
		toSerialize["partId"] = o.PartId
	}
	if !IsNil(o.OperationCode) {
		toSerialize["operationCode"] = o.OperationCode
	}
	if !IsNil(o.SupplierId) {
		toSerialize["supplierId"] = o.SupplierId
	}
	if !IsNil(o.LeadTime) {
		toSerialize["leadTime"] = o.LeadTime
	}
	if !IsNil(o.SupplierPartNumber) {
		toSerialize["supplierPartNumber"] = o.SupplierPartNumber
	}
	if !IsNil(o.BusinessPercentage) {
		toSerialize["businessPercentage"] = o.BusinessPercentage
	}
	if !IsNil(o.TransitTime) {
		toSerialize["transitTime"] = o.TransitTime
	}
	if !IsNil(o.Note) {
		toSerialize["note"] = o.Note
	}
	if !IsNil(o.PartOperationId) {
		toSerialize["partOperationId"] = o.PartOperationId
	}
	return toSerialize, nil
}

type NullableApprovedSuppliersApiListApprovedSuppliersItem struct {
	value *ApprovedSuppliersApiListApprovedSuppliersItem
	isSet bool
}

func (v NullableApprovedSuppliersApiListApprovedSuppliersItem) Get() *ApprovedSuppliersApiListApprovedSuppliersItem {
	return v.value
}

func (v *NullableApprovedSuppliersApiListApprovedSuppliersItem) Set(val *ApprovedSuppliersApiListApprovedSuppliersItem) {
	v.value = val
	v.isSet = true
}

func (v NullableApprovedSuppliersApiListApprovedSuppliersItem) IsSet() bool {
	return v.isSet
}

func (v *NullableApprovedSuppliersApiListApprovedSuppliersItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApprovedSuppliersApiListApprovedSuppliersItem(val *ApprovedSuppliersApiListApprovedSuppliersItem) *NullableApprovedSuppliersApiListApprovedSuppliersItem {
	return &NullableApprovedSuppliersApiListApprovedSuppliersItem{value: val, isSet: true}
}

func (v NullableApprovedSuppliersApiListApprovedSuppliersItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApprovedSuppliersApiListApprovedSuppliersItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


