/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the CustomerTrucksApiListCustomerTrucksItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerTrucksApiListCustomerTrucksItem{}

// CustomerTrucksApiListCustomerTrucksItem The truck model exposed for adding records.
type CustomerTrucksApiListCustomerTrucksItem struct {
	// A unique identifier for the truck. This will be automatically generated if omitted from the request.
	Id *string `json:"id,omitempty"`
	// The ship date assigned to the truck.
	ShipDate *time.Time `json:"shipDate,omitempty"`
	// Terms of the freight payment; for example, COD, Collect, or Prepaid.
	FreightTerms *string `json:"freightTerms,omitempty"`
	// The tracking number, often provided by a carrier, related to a specific shipment.
	TrackingNumber *string `json:"trackingNumber,omitempty"`
	// The trailer number associated with the physical trailer that a specific shipment was shipped on.
	TrailerNumber *string `json:"trailerNumber,omitempty"`
	// A note assigned to the truck.
	Note *string `json:"note,omitempty"`
	// Indicates if the carrier has been contacted.
	TruckCalled *bool `json:"truckCalled,omitempty"`
	// The arrival time of the truck (arrival time can be planned or actual, depending on implementation).
	TruckArrivalTime *time.Time `json:"truckArrivalTime,omitempty"`
	// The bill of lading number.
	BolNumber *string `json:"bolNumber,omitempty"`
	// A note on the bill of lading.
	BolNote *string `json:"bolNote,omitempty"`
	// Indicates that the truck is part of a pool shipment. A pool is a central warehouse that redistributes shippers from one truck to another before shipping to customer locations.
	Pool *bool `json:"pool,omitempty"`
	// The ID of the carrier associated with the truck. (A carrier is a supplier with a supplier type of &quot;Carrier&quot;.)
	CarrierId *string `json:"carrierId,omitempty"`
	// The customer address ID of the pool location associated with the truck.
	PoolCustomerAddressId *string `json:"poolCustomerAddressId,omitempty"`
	// The ID of the supplier with a &quot;Carrier&quot; type used as the trailer carrier.
	TrailerCarrierId *string `json:"trailerCarrierId,omitempty"`
	// The ID of the supplier with a &quot;Carrier&quot; type used as the brokered carrier.
	BrokeredCarrierId *string `json:"brokeredCarrierId,omitempty"`
	// The date the carrier was called regarding the shipment or truck.
	TruckCalledDate *time.Time `json:"truckCalledDate,omitempty"`
	// The confirmation from the carrier regarding the shipment or truck.
	TruckConfirmation *string `json:"truckConfirmation,omitempty"`
	// A contact person, typically at the carrier, regarding the shipment or truck.
	TruckContact *string `json:"truckContact,omitempty"`
	// The Plex user ID of the truck driver associated with this Truck (Truck_Drive_Key).
	TruckDriverId *string `json:"truckDriverId,omitempty"`
	// The ID of the user who shipped the truck.
	ShippedById *string `json:"shippedById,omitempty"`
	// The date on which the truck is scheduled to ship.
	ScheduledShipDate *time.Time `json:"scheduledShipDate,omitempty"`
	// The ID of the user who created the record.
	CreatedById *string `json:"createdById,omitempty"`
	// The date on which the record was created.
	CreatedDate *time.Time `json:"createdDate,omitempty"`
	// The ID of the user who last modified the record.
	ModifiedById *string `json:"modifiedById,omitempty"`
	// The date on which the record was last modified.
	ModifiedDate *time.Time `json:"modifiedDate,omitempty"`
	// The name of a route with multiple stops that happens on a recurring basis.
	MilkRun *string `json:"milkRun,omitempty"`
	// The truck type.
	Type *string `json:"type,omitempty"`
	// The truck status.
	Status *string `json:"status,omitempty"`
	// A Plex-generated unique number representing the truck shipment.
	TruckNumber *string `json:"truckNumber,omitempty"`
	// The transportation mode associated with the truck.
	TransMode *string `json:"transMode,omitempty"`
	// The ID of the customer address from which the truck was shipped.
	ShipFromId *string `json:"shipFromId,omitempty"`
	// International Commercial (INCO) terms applied to the sales order.
	IncoTerms *string `json:"incoTerms,omitempty"`
	// The ID of the supplier with a &quot;Customs Broker&quot; type.
	CustomsBrokerSupplierId *string `json:"customsBrokerSupplierId,omitempty"`
	// The sub-building code indicating the location in the building where the truck will be loaded.
	SubBuilding *string `json:"subBuilding,omitempty"`
	// The dropship supplier resource ID associated with the truck.
	DropshipSupplierId *string `json:"dropshipSupplierId,omitempty"`
	// The dropship supplier code associated with the truck.
	DropshipSupplierCode *string `json:"dropshipSupplierCode,omitempty"`
	// The route for the truck.
	TruckRoute *string `json:"truckRoute,omitempty"`
	// The estimated arrival date of the truck.
	EstimatedArrivalDate *time.Time `json:"estimatedArrivalDate,omitempty"`
	// The amount of the truck freight charge.
	TruckFreightAmount *float64 `json:"truckFreightAmount,omitempty"`
	// The time at which the truck arrived.
	TruckArrivalTimeOfDay *string `json:"truckArrivalTimeOfDay,omitempty"`
}

// NewCustomerTrucksApiListCustomerTrucksItem instantiates a new CustomerTrucksApiListCustomerTrucksItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerTrucksApiListCustomerTrucksItem() *CustomerTrucksApiListCustomerTrucksItem {
	this := CustomerTrucksApiListCustomerTrucksItem{}
	return &this
}

// NewCustomerTrucksApiListCustomerTrucksItemWithDefaults instantiates a new CustomerTrucksApiListCustomerTrucksItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerTrucksApiListCustomerTrucksItemWithDefaults() *CustomerTrucksApiListCustomerTrucksItem {
	this := CustomerTrucksApiListCustomerTrucksItem{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetId(v string) {
	o.Id = &v
}

// GetShipDate returns the ShipDate field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetShipDate() time.Time {
	if o == nil || IsNil(o.ShipDate) {
		var ret time.Time
		return ret
	}
	return *o.ShipDate
}

// GetShipDateOk returns a tuple with the ShipDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetShipDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ShipDate) {
		return nil, false
	}
	return o.ShipDate, true
}

// HasShipDate returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasShipDate() bool {
	if o != nil && !IsNil(o.ShipDate) {
		return true
	}

	return false
}

// SetShipDate gets a reference to the given time.Time and assigns it to the ShipDate field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetShipDate(v time.Time) {
	o.ShipDate = &v
}

// GetFreightTerms returns the FreightTerms field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetFreightTerms() string {
	if o == nil || IsNil(o.FreightTerms) {
		var ret string
		return ret
	}
	return *o.FreightTerms
}

// GetFreightTermsOk returns a tuple with the FreightTerms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetFreightTermsOk() (*string, bool) {
	if o == nil || IsNil(o.FreightTerms) {
		return nil, false
	}
	return o.FreightTerms, true
}

// HasFreightTerms returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasFreightTerms() bool {
	if o != nil && !IsNil(o.FreightTerms) {
		return true
	}

	return false
}

// SetFreightTerms gets a reference to the given string and assigns it to the FreightTerms field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetFreightTerms(v string) {
	o.FreightTerms = &v
}

// GetTrackingNumber returns the TrackingNumber field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTrackingNumber() string {
	if o == nil || IsNil(o.TrackingNumber) {
		var ret string
		return ret
	}
	return *o.TrackingNumber
}

// GetTrackingNumberOk returns a tuple with the TrackingNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTrackingNumberOk() (*string, bool) {
	if o == nil || IsNil(o.TrackingNumber) {
		return nil, false
	}
	return o.TrackingNumber, true
}

// HasTrackingNumber returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasTrackingNumber() bool {
	if o != nil && !IsNil(o.TrackingNumber) {
		return true
	}

	return false
}

// SetTrackingNumber gets a reference to the given string and assigns it to the TrackingNumber field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetTrackingNumber(v string) {
	o.TrackingNumber = &v
}

// GetTrailerNumber returns the TrailerNumber field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTrailerNumber() string {
	if o == nil || IsNil(o.TrailerNumber) {
		var ret string
		return ret
	}
	return *o.TrailerNumber
}

// GetTrailerNumberOk returns a tuple with the TrailerNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTrailerNumberOk() (*string, bool) {
	if o == nil || IsNil(o.TrailerNumber) {
		return nil, false
	}
	return o.TrailerNumber, true
}

// HasTrailerNumber returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasTrailerNumber() bool {
	if o != nil && !IsNil(o.TrailerNumber) {
		return true
	}

	return false
}

// SetTrailerNumber gets a reference to the given string and assigns it to the TrailerNumber field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetTrailerNumber(v string) {
	o.TrailerNumber = &v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetNote() string {
	if o == nil || IsNil(o.Note) {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetNoteOk() (*string, bool) {
	if o == nil || IsNil(o.Note) {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasNote() bool {
	if o != nil && !IsNil(o.Note) {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetNote(v string) {
	o.Note = &v
}

// GetTruckCalled returns the TruckCalled field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTruckCalled() bool {
	if o == nil || IsNil(o.TruckCalled) {
		var ret bool
		return ret
	}
	return *o.TruckCalled
}

// GetTruckCalledOk returns a tuple with the TruckCalled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTruckCalledOk() (*bool, bool) {
	if o == nil || IsNil(o.TruckCalled) {
		return nil, false
	}
	return o.TruckCalled, true
}

// HasTruckCalled returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasTruckCalled() bool {
	if o != nil && !IsNil(o.TruckCalled) {
		return true
	}

	return false
}

// SetTruckCalled gets a reference to the given bool and assigns it to the TruckCalled field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetTruckCalled(v bool) {
	o.TruckCalled = &v
}

// GetTruckArrivalTime returns the TruckArrivalTime field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTruckArrivalTime() time.Time {
	if o == nil || IsNil(o.TruckArrivalTime) {
		var ret time.Time
		return ret
	}
	return *o.TruckArrivalTime
}

// GetTruckArrivalTimeOk returns a tuple with the TruckArrivalTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTruckArrivalTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.TruckArrivalTime) {
		return nil, false
	}
	return o.TruckArrivalTime, true
}

// HasTruckArrivalTime returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasTruckArrivalTime() bool {
	if o != nil && !IsNil(o.TruckArrivalTime) {
		return true
	}

	return false
}

// SetTruckArrivalTime gets a reference to the given time.Time and assigns it to the TruckArrivalTime field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetTruckArrivalTime(v time.Time) {
	o.TruckArrivalTime = &v
}

// GetBolNumber returns the BolNumber field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetBolNumber() string {
	if o == nil || IsNil(o.BolNumber) {
		var ret string
		return ret
	}
	return *o.BolNumber
}

// GetBolNumberOk returns a tuple with the BolNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetBolNumberOk() (*string, bool) {
	if o == nil || IsNil(o.BolNumber) {
		return nil, false
	}
	return o.BolNumber, true
}

// HasBolNumber returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasBolNumber() bool {
	if o != nil && !IsNil(o.BolNumber) {
		return true
	}

	return false
}

// SetBolNumber gets a reference to the given string and assigns it to the BolNumber field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetBolNumber(v string) {
	o.BolNumber = &v
}

// GetBolNote returns the BolNote field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetBolNote() string {
	if o == nil || IsNil(o.BolNote) {
		var ret string
		return ret
	}
	return *o.BolNote
}

// GetBolNoteOk returns a tuple with the BolNote field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetBolNoteOk() (*string, bool) {
	if o == nil || IsNil(o.BolNote) {
		return nil, false
	}
	return o.BolNote, true
}

// HasBolNote returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasBolNote() bool {
	if o != nil && !IsNil(o.BolNote) {
		return true
	}

	return false
}

// SetBolNote gets a reference to the given string and assigns it to the BolNote field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetBolNote(v string) {
	o.BolNote = &v
}

// GetPool returns the Pool field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetPool() bool {
	if o == nil || IsNil(o.Pool) {
		var ret bool
		return ret
	}
	return *o.Pool
}

// GetPoolOk returns a tuple with the Pool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetPoolOk() (*bool, bool) {
	if o == nil || IsNil(o.Pool) {
		return nil, false
	}
	return o.Pool, true
}

// HasPool returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasPool() bool {
	if o != nil && !IsNil(o.Pool) {
		return true
	}

	return false
}

// SetPool gets a reference to the given bool and assigns it to the Pool field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetPool(v bool) {
	o.Pool = &v
}

// GetCarrierId returns the CarrierId field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetCarrierId() string {
	if o == nil || IsNil(o.CarrierId) {
		var ret string
		return ret
	}
	return *o.CarrierId
}

// GetCarrierIdOk returns a tuple with the CarrierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetCarrierIdOk() (*string, bool) {
	if o == nil || IsNil(o.CarrierId) {
		return nil, false
	}
	return o.CarrierId, true
}

// HasCarrierId returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasCarrierId() bool {
	if o != nil && !IsNil(o.CarrierId) {
		return true
	}

	return false
}

// SetCarrierId gets a reference to the given string and assigns it to the CarrierId field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetCarrierId(v string) {
	o.CarrierId = &v
}

// GetPoolCustomerAddressId returns the PoolCustomerAddressId field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetPoolCustomerAddressId() string {
	if o == nil || IsNil(o.PoolCustomerAddressId) {
		var ret string
		return ret
	}
	return *o.PoolCustomerAddressId
}

// GetPoolCustomerAddressIdOk returns a tuple with the PoolCustomerAddressId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetPoolCustomerAddressIdOk() (*string, bool) {
	if o == nil || IsNil(o.PoolCustomerAddressId) {
		return nil, false
	}
	return o.PoolCustomerAddressId, true
}

// HasPoolCustomerAddressId returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasPoolCustomerAddressId() bool {
	if o != nil && !IsNil(o.PoolCustomerAddressId) {
		return true
	}

	return false
}

// SetPoolCustomerAddressId gets a reference to the given string and assigns it to the PoolCustomerAddressId field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetPoolCustomerAddressId(v string) {
	o.PoolCustomerAddressId = &v
}

// GetTrailerCarrierId returns the TrailerCarrierId field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTrailerCarrierId() string {
	if o == nil || IsNil(o.TrailerCarrierId) {
		var ret string
		return ret
	}
	return *o.TrailerCarrierId
}

// GetTrailerCarrierIdOk returns a tuple with the TrailerCarrierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTrailerCarrierIdOk() (*string, bool) {
	if o == nil || IsNil(o.TrailerCarrierId) {
		return nil, false
	}
	return o.TrailerCarrierId, true
}

// HasTrailerCarrierId returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasTrailerCarrierId() bool {
	if o != nil && !IsNil(o.TrailerCarrierId) {
		return true
	}

	return false
}

// SetTrailerCarrierId gets a reference to the given string and assigns it to the TrailerCarrierId field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetTrailerCarrierId(v string) {
	o.TrailerCarrierId = &v
}

// GetBrokeredCarrierId returns the BrokeredCarrierId field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetBrokeredCarrierId() string {
	if o == nil || IsNil(o.BrokeredCarrierId) {
		var ret string
		return ret
	}
	return *o.BrokeredCarrierId
}

// GetBrokeredCarrierIdOk returns a tuple with the BrokeredCarrierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetBrokeredCarrierIdOk() (*string, bool) {
	if o == nil || IsNil(o.BrokeredCarrierId) {
		return nil, false
	}
	return o.BrokeredCarrierId, true
}

// HasBrokeredCarrierId returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasBrokeredCarrierId() bool {
	if o != nil && !IsNil(o.BrokeredCarrierId) {
		return true
	}

	return false
}

// SetBrokeredCarrierId gets a reference to the given string and assigns it to the BrokeredCarrierId field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetBrokeredCarrierId(v string) {
	o.BrokeredCarrierId = &v
}

// GetTruckCalledDate returns the TruckCalledDate field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTruckCalledDate() time.Time {
	if o == nil || IsNil(o.TruckCalledDate) {
		var ret time.Time
		return ret
	}
	return *o.TruckCalledDate
}

// GetTruckCalledDateOk returns a tuple with the TruckCalledDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTruckCalledDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.TruckCalledDate) {
		return nil, false
	}
	return o.TruckCalledDate, true
}

// HasTruckCalledDate returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasTruckCalledDate() bool {
	if o != nil && !IsNil(o.TruckCalledDate) {
		return true
	}

	return false
}

// SetTruckCalledDate gets a reference to the given time.Time and assigns it to the TruckCalledDate field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetTruckCalledDate(v time.Time) {
	o.TruckCalledDate = &v
}

// GetTruckConfirmation returns the TruckConfirmation field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTruckConfirmation() string {
	if o == nil || IsNil(o.TruckConfirmation) {
		var ret string
		return ret
	}
	return *o.TruckConfirmation
}

// GetTruckConfirmationOk returns a tuple with the TruckConfirmation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTruckConfirmationOk() (*string, bool) {
	if o == nil || IsNil(o.TruckConfirmation) {
		return nil, false
	}
	return o.TruckConfirmation, true
}

// HasTruckConfirmation returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasTruckConfirmation() bool {
	if o != nil && !IsNil(o.TruckConfirmation) {
		return true
	}

	return false
}

// SetTruckConfirmation gets a reference to the given string and assigns it to the TruckConfirmation field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetTruckConfirmation(v string) {
	o.TruckConfirmation = &v
}

// GetTruckContact returns the TruckContact field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTruckContact() string {
	if o == nil || IsNil(o.TruckContact) {
		var ret string
		return ret
	}
	return *o.TruckContact
}

// GetTruckContactOk returns a tuple with the TruckContact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTruckContactOk() (*string, bool) {
	if o == nil || IsNil(o.TruckContact) {
		return nil, false
	}
	return o.TruckContact, true
}

// HasTruckContact returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasTruckContact() bool {
	if o != nil && !IsNil(o.TruckContact) {
		return true
	}

	return false
}

// SetTruckContact gets a reference to the given string and assigns it to the TruckContact field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetTruckContact(v string) {
	o.TruckContact = &v
}

// GetTruckDriverId returns the TruckDriverId field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTruckDriverId() string {
	if o == nil || IsNil(o.TruckDriverId) {
		var ret string
		return ret
	}
	return *o.TruckDriverId
}

// GetTruckDriverIdOk returns a tuple with the TruckDriverId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTruckDriverIdOk() (*string, bool) {
	if o == nil || IsNil(o.TruckDriverId) {
		return nil, false
	}
	return o.TruckDriverId, true
}

// HasTruckDriverId returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasTruckDriverId() bool {
	if o != nil && !IsNil(o.TruckDriverId) {
		return true
	}

	return false
}

// SetTruckDriverId gets a reference to the given string and assigns it to the TruckDriverId field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetTruckDriverId(v string) {
	o.TruckDriverId = &v
}

// GetShippedById returns the ShippedById field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetShippedById() string {
	if o == nil || IsNil(o.ShippedById) {
		var ret string
		return ret
	}
	return *o.ShippedById
}

// GetShippedByIdOk returns a tuple with the ShippedById field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetShippedByIdOk() (*string, bool) {
	if o == nil || IsNil(o.ShippedById) {
		return nil, false
	}
	return o.ShippedById, true
}

// HasShippedById returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasShippedById() bool {
	if o != nil && !IsNil(o.ShippedById) {
		return true
	}

	return false
}

// SetShippedById gets a reference to the given string and assigns it to the ShippedById field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetShippedById(v string) {
	o.ShippedById = &v
}

// GetScheduledShipDate returns the ScheduledShipDate field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetScheduledShipDate() time.Time {
	if o == nil || IsNil(o.ScheduledShipDate) {
		var ret time.Time
		return ret
	}
	return *o.ScheduledShipDate
}

// GetScheduledShipDateOk returns a tuple with the ScheduledShipDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetScheduledShipDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ScheduledShipDate) {
		return nil, false
	}
	return o.ScheduledShipDate, true
}

// HasScheduledShipDate returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasScheduledShipDate() bool {
	if o != nil && !IsNil(o.ScheduledShipDate) {
		return true
	}

	return false
}

// SetScheduledShipDate gets a reference to the given time.Time and assigns it to the ScheduledShipDate field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetScheduledShipDate(v time.Time) {
	o.ScheduledShipDate = &v
}

// GetCreatedById returns the CreatedById field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetCreatedById() string {
	if o == nil || IsNil(o.CreatedById) {
		var ret string
		return ret
	}
	return *o.CreatedById
}

// GetCreatedByIdOk returns a tuple with the CreatedById field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetCreatedByIdOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedById) {
		return nil, false
	}
	return o.CreatedById, true
}

// HasCreatedById returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasCreatedById() bool {
	if o != nil && !IsNil(o.CreatedById) {
		return true
	}

	return false
}

// SetCreatedById gets a reference to the given string and assigns it to the CreatedById field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetCreatedById(v string) {
	o.CreatedById = &v
}

// GetCreatedDate returns the CreatedDate field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetCreatedDate() time.Time {
	if o == nil || IsNil(o.CreatedDate) {
		var ret time.Time
		return ret
	}
	return *o.CreatedDate
}

// GetCreatedDateOk returns a tuple with the CreatedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetCreatedDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedDate) {
		return nil, false
	}
	return o.CreatedDate, true
}

// HasCreatedDate returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasCreatedDate() bool {
	if o != nil && !IsNil(o.CreatedDate) {
		return true
	}

	return false
}

// SetCreatedDate gets a reference to the given time.Time and assigns it to the CreatedDate field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetCreatedDate(v time.Time) {
	o.CreatedDate = &v
}

// GetModifiedById returns the ModifiedById field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetModifiedById() string {
	if o == nil || IsNil(o.ModifiedById) {
		var ret string
		return ret
	}
	return *o.ModifiedById
}

// GetModifiedByIdOk returns a tuple with the ModifiedById field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetModifiedByIdOk() (*string, bool) {
	if o == nil || IsNil(o.ModifiedById) {
		return nil, false
	}
	return o.ModifiedById, true
}

// HasModifiedById returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasModifiedById() bool {
	if o != nil && !IsNil(o.ModifiedById) {
		return true
	}

	return false
}

// SetModifiedById gets a reference to the given string and assigns it to the ModifiedById field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetModifiedById(v string) {
	o.ModifiedById = &v
}

// GetModifiedDate returns the ModifiedDate field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetModifiedDate() time.Time {
	if o == nil || IsNil(o.ModifiedDate) {
		var ret time.Time
		return ret
	}
	return *o.ModifiedDate
}

// GetModifiedDateOk returns a tuple with the ModifiedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetModifiedDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ModifiedDate) {
		return nil, false
	}
	return o.ModifiedDate, true
}

// HasModifiedDate returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasModifiedDate() bool {
	if o != nil && !IsNil(o.ModifiedDate) {
		return true
	}

	return false
}

// SetModifiedDate gets a reference to the given time.Time and assigns it to the ModifiedDate field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetModifiedDate(v time.Time) {
	o.ModifiedDate = &v
}

// GetMilkRun returns the MilkRun field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetMilkRun() string {
	if o == nil || IsNil(o.MilkRun) {
		var ret string
		return ret
	}
	return *o.MilkRun
}

// GetMilkRunOk returns a tuple with the MilkRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetMilkRunOk() (*string, bool) {
	if o == nil || IsNil(o.MilkRun) {
		return nil, false
	}
	return o.MilkRun, true
}

// HasMilkRun returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasMilkRun() bool {
	if o != nil && !IsNil(o.MilkRun) {
		return true
	}

	return false
}

// SetMilkRun gets a reference to the given string and assigns it to the MilkRun field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetMilkRun(v string) {
	o.MilkRun = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetType(v string) {
	o.Type = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetStatus(v string) {
	o.Status = &v
}

// GetTruckNumber returns the TruckNumber field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTruckNumber() string {
	if o == nil || IsNil(o.TruckNumber) {
		var ret string
		return ret
	}
	return *o.TruckNumber
}

// GetTruckNumberOk returns a tuple with the TruckNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTruckNumberOk() (*string, bool) {
	if o == nil || IsNil(o.TruckNumber) {
		return nil, false
	}
	return o.TruckNumber, true
}

// HasTruckNumber returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasTruckNumber() bool {
	if o != nil && !IsNil(o.TruckNumber) {
		return true
	}

	return false
}

// SetTruckNumber gets a reference to the given string and assigns it to the TruckNumber field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetTruckNumber(v string) {
	o.TruckNumber = &v
}

// GetTransMode returns the TransMode field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTransMode() string {
	if o == nil || IsNil(o.TransMode) {
		var ret string
		return ret
	}
	return *o.TransMode
}

// GetTransModeOk returns a tuple with the TransMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTransModeOk() (*string, bool) {
	if o == nil || IsNil(o.TransMode) {
		return nil, false
	}
	return o.TransMode, true
}

// HasTransMode returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasTransMode() bool {
	if o != nil && !IsNil(o.TransMode) {
		return true
	}

	return false
}

// SetTransMode gets a reference to the given string and assigns it to the TransMode field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetTransMode(v string) {
	o.TransMode = &v
}

// GetShipFromId returns the ShipFromId field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetShipFromId() string {
	if o == nil || IsNil(o.ShipFromId) {
		var ret string
		return ret
	}
	return *o.ShipFromId
}

// GetShipFromIdOk returns a tuple with the ShipFromId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetShipFromIdOk() (*string, bool) {
	if o == nil || IsNil(o.ShipFromId) {
		return nil, false
	}
	return o.ShipFromId, true
}

// HasShipFromId returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasShipFromId() bool {
	if o != nil && !IsNil(o.ShipFromId) {
		return true
	}

	return false
}

// SetShipFromId gets a reference to the given string and assigns it to the ShipFromId field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetShipFromId(v string) {
	o.ShipFromId = &v
}

// GetIncoTerms returns the IncoTerms field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetIncoTerms() string {
	if o == nil || IsNil(o.IncoTerms) {
		var ret string
		return ret
	}
	return *o.IncoTerms
}

// GetIncoTermsOk returns a tuple with the IncoTerms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetIncoTermsOk() (*string, bool) {
	if o == nil || IsNil(o.IncoTerms) {
		return nil, false
	}
	return o.IncoTerms, true
}

// HasIncoTerms returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasIncoTerms() bool {
	if o != nil && !IsNil(o.IncoTerms) {
		return true
	}

	return false
}

// SetIncoTerms gets a reference to the given string and assigns it to the IncoTerms field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetIncoTerms(v string) {
	o.IncoTerms = &v
}

// GetCustomsBrokerSupplierId returns the CustomsBrokerSupplierId field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetCustomsBrokerSupplierId() string {
	if o == nil || IsNil(o.CustomsBrokerSupplierId) {
		var ret string
		return ret
	}
	return *o.CustomsBrokerSupplierId
}

// GetCustomsBrokerSupplierIdOk returns a tuple with the CustomsBrokerSupplierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetCustomsBrokerSupplierIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomsBrokerSupplierId) {
		return nil, false
	}
	return o.CustomsBrokerSupplierId, true
}

// HasCustomsBrokerSupplierId returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasCustomsBrokerSupplierId() bool {
	if o != nil && !IsNil(o.CustomsBrokerSupplierId) {
		return true
	}

	return false
}

// SetCustomsBrokerSupplierId gets a reference to the given string and assigns it to the CustomsBrokerSupplierId field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetCustomsBrokerSupplierId(v string) {
	o.CustomsBrokerSupplierId = &v
}

// GetSubBuilding returns the SubBuilding field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetSubBuilding() string {
	if o == nil || IsNil(o.SubBuilding) {
		var ret string
		return ret
	}
	return *o.SubBuilding
}

// GetSubBuildingOk returns a tuple with the SubBuilding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetSubBuildingOk() (*string, bool) {
	if o == nil || IsNil(o.SubBuilding) {
		return nil, false
	}
	return o.SubBuilding, true
}

// HasSubBuilding returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasSubBuilding() bool {
	if o != nil && !IsNil(o.SubBuilding) {
		return true
	}

	return false
}

// SetSubBuilding gets a reference to the given string and assigns it to the SubBuilding field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetSubBuilding(v string) {
	o.SubBuilding = &v
}

// GetDropshipSupplierId returns the DropshipSupplierId field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetDropshipSupplierId() string {
	if o == nil || IsNil(o.DropshipSupplierId) {
		var ret string
		return ret
	}
	return *o.DropshipSupplierId
}

// GetDropshipSupplierIdOk returns a tuple with the DropshipSupplierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetDropshipSupplierIdOk() (*string, bool) {
	if o == nil || IsNil(o.DropshipSupplierId) {
		return nil, false
	}
	return o.DropshipSupplierId, true
}

// HasDropshipSupplierId returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasDropshipSupplierId() bool {
	if o != nil && !IsNil(o.DropshipSupplierId) {
		return true
	}

	return false
}

// SetDropshipSupplierId gets a reference to the given string and assigns it to the DropshipSupplierId field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetDropshipSupplierId(v string) {
	o.DropshipSupplierId = &v
}

// GetDropshipSupplierCode returns the DropshipSupplierCode field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetDropshipSupplierCode() string {
	if o == nil || IsNil(o.DropshipSupplierCode) {
		var ret string
		return ret
	}
	return *o.DropshipSupplierCode
}

// GetDropshipSupplierCodeOk returns a tuple with the DropshipSupplierCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetDropshipSupplierCodeOk() (*string, bool) {
	if o == nil || IsNil(o.DropshipSupplierCode) {
		return nil, false
	}
	return o.DropshipSupplierCode, true
}

// HasDropshipSupplierCode returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasDropshipSupplierCode() bool {
	if o != nil && !IsNil(o.DropshipSupplierCode) {
		return true
	}

	return false
}

// SetDropshipSupplierCode gets a reference to the given string and assigns it to the DropshipSupplierCode field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetDropshipSupplierCode(v string) {
	o.DropshipSupplierCode = &v
}

// GetTruckRoute returns the TruckRoute field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTruckRoute() string {
	if o == nil || IsNil(o.TruckRoute) {
		var ret string
		return ret
	}
	return *o.TruckRoute
}

// GetTruckRouteOk returns a tuple with the TruckRoute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTruckRouteOk() (*string, bool) {
	if o == nil || IsNil(o.TruckRoute) {
		return nil, false
	}
	return o.TruckRoute, true
}

// HasTruckRoute returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasTruckRoute() bool {
	if o != nil && !IsNil(o.TruckRoute) {
		return true
	}

	return false
}

// SetTruckRoute gets a reference to the given string and assigns it to the TruckRoute field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetTruckRoute(v string) {
	o.TruckRoute = &v
}

// GetEstimatedArrivalDate returns the EstimatedArrivalDate field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetEstimatedArrivalDate() time.Time {
	if o == nil || IsNil(o.EstimatedArrivalDate) {
		var ret time.Time
		return ret
	}
	return *o.EstimatedArrivalDate
}

// GetEstimatedArrivalDateOk returns a tuple with the EstimatedArrivalDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetEstimatedArrivalDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EstimatedArrivalDate) {
		return nil, false
	}
	return o.EstimatedArrivalDate, true
}

// HasEstimatedArrivalDate returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasEstimatedArrivalDate() bool {
	if o != nil && !IsNil(o.EstimatedArrivalDate) {
		return true
	}

	return false
}

// SetEstimatedArrivalDate gets a reference to the given time.Time and assigns it to the EstimatedArrivalDate field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetEstimatedArrivalDate(v time.Time) {
	o.EstimatedArrivalDate = &v
}

// GetTruckFreightAmount returns the TruckFreightAmount field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTruckFreightAmount() float64 {
	if o == nil || IsNil(o.TruckFreightAmount) {
		var ret float64
		return ret
	}
	return *o.TruckFreightAmount
}

// GetTruckFreightAmountOk returns a tuple with the TruckFreightAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTruckFreightAmountOk() (*float64, bool) {
	if o == nil || IsNil(o.TruckFreightAmount) {
		return nil, false
	}
	return o.TruckFreightAmount, true
}

// HasTruckFreightAmount returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasTruckFreightAmount() bool {
	if o != nil && !IsNil(o.TruckFreightAmount) {
		return true
	}

	return false
}

// SetTruckFreightAmount gets a reference to the given float64 and assigns it to the TruckFreightAmount field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetTruckFreightAmount(v float64) {
	o.TruckFreightAmount = &v
}

// GetTruckArrivalTimeOfDay returns the TruckArrivalTimeOfDay field value if set, zero value otherwise.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTruckArrivalTimeOfDay() string {
	if o == nil || IsNil(o.TruckArrivalTimeOfDay) {
		var ret string
		return ret
	}
	return *o.TruckArrivalTimeOfDay
}

// GetTruckArrivalTimeOfDayOk returns a tuple with the TruckArrivalTimeOfDay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) GetTruckArrivalTimeOfDayOk() (*string, bool) {
	if o == nil || IsNil(o.TruckArrivalTimeOfDay) {
		return nil, false
	}
	return o.TruckArrivalTimeOfDay, true
}

// HasTruckArrivalTimeOfDay returns a boolean if a field has been set.
func (o *CustomerTrucksApiListCustomerTrucksItem) HasTruckArrivalTimeOfDay() bool {
	if o != nil && !IsNil(o.TruckArrivalTimeOfDay) {
		return true
	}

	return false
}

// SetTruckArrivalTimeOfDay gets a reference to the given string and assigns it to the TruckArrivalTimeOfDay field.
func (o *CustomerTrucksApiListCustomerTrucksItem) SetTruckArrivalTimeOfDay(v string) {
	o.TruckArrivalTimeOfDay = &v
}

func (o CustomerTrucksApiListCustomerTrucksItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerTrucksApiListCustomerTrucksItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ShipDate) {
		toSerialize["shipDate"] = o.ShipDate
	}
	if !IsNil(o.FreightTerms) {
		toSerialize["freightTerms"] = o.FreightTerms
	}
	if !IsNil(o.TrackingNumber) {
		toSerialize["trackingNumber"] = o.TrackingNumber
	}
	if !IsNil(o.TrailerNumber) {
		toSerialize["trailerNumber"] = o.TrailerNumber
	}
	if !IsNil(o.Note) {
		toSerialize["note"] = o.Note
	}
	if !IsNil(o.TruckCalled) {
		toSerialize["truckCalled"] = o.TruckCalled
	}
	if !IsNil(o.TruckArrivalTime) {
		toSerialize["truckArrivalTime"] = o.TruckArrivalTime
	}
	if !IsNil(o.BolNumber) {
		toSerialize["bolNumber"] = o.BolNumber
	}
	if !IsNil(o.BolNote) {
		toSerialize["bolNote"] = o.BolNote
	}
	if !IsNil(o.Pool) {
		toSerialize["pool"] = o.Pool
	}
	if !IsNil(o.CarrierId) {
		toSerialize["carrierId"] = o.CarrierId
	}
	if !IsNil(o.PoolCustomerAddressId) {
		toSerialize["poolCustomerAddressId"] = o.PoolCustomerAddressId
	}
	if !IsNil(o.TrailerCarrierId) {
		toSerialize["trailerCarrierId"] = o.TrailerCarrierId
	}
	if !IsNil(o.BrokeredCarrierId) {
		toSerialize["brokeredCarrierId"] = o.BrokeredCarrierId
	}
	if !IsNil(o.TruckCalledDate) {
		toSerialize["truckCalledDate"] = o.TruckCalledDate
	}
	if !IsNil(o.TruckConfirmation) {
		toSerialize["truckConfirmation"] = o.TruckConfirmation
	}
	if !IsNil(o.TruckContact) {
		toSerialize["truckContact"] = o.TruckContact
	}
	if !IsNil(o.TruckDriverId) {
		toSerialize["truckDriverId"] = o.TruckDriverId
	}
	if !IsNil(o.ShippedById) {
		toSerialize["shippedById"] = o.ShippedById
	}
	if !IsNil(o.ScheduledShipDate) {
		toSerialize["scheduledShipDate"] = o.ScheduledShipDate
	}
	if !IsNil(o.CreatedById) {
		toSerialize["createdById"] = o.CreatedById
	}
	if !IsNil(o.CreatedDate) {
		toSerialize["createdDate"] = o.CreatedDate
	}
	if !IsNil(o.ModifiedById) {
		toSerialize["modifiedById"] = o.ModifiedById
	}
	if !IsNil(o.ModifiedDate) {
		toSerialize["modifiedDate"] = o.ModifiedDate
	}
	if !IsNil(o.MilkRun) {
		toSerialize["milkRun"] = o.MilkRun
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.TruckNumber) {
		toSerialize["truckNumber"] = o.TruckNumber
	}
	if !IsNil(o.TransMode) {
		toSerialize["transMode"] = o.TransMode
	}
	if !IsNil(o.ShipFromId) {
		toSerialize["shipFromId"] = o.ShipFromId
	}
	if !IsNil(o.IncoTerms) {
		toSerialize["incoTerms"] = o.IncoTerms
	}
	if !IsNil(o.CustomsBrokerSupplierId) {
		toSerialize["customsBrokerSupplierId"] = o.CustomsBrokerSupplierId
	}
	if !IsNil(o.SubBuilding) {
		toSerialize["subBuilding"] = o.SubBuilding
	}
	if !IsNil(o.DropshipSupplierId) {
		toSerialize["dropshipSupplierId"] = o.DropshipSupplierId
	}
	if !IsNil(o.DropshipSupplierCode) {
		toSerialize["dropshipSupplierCode"] = o.DropshipSupplierCode
	}
	if !IsNil(o.TruckRoute) {
		toSerialize["truckRoute"] = o.TruckRoute
	}
	if !IsNil(o.EstimatedArrivalDate) {
		toSerialize["estimatedArrivalDate"] = o.EstimatedArrivalDate
	}
	if !IsNil(o.TruckFreightAmount) {
		toSerialize["truckFreightAmount"] = o.TruckFreightAmount
	}
	if !IsNil(o.TruckArrivalTimeOfDay) {
		toSerialize["truckArrivalTimeOfDay"] = o.TruckArrivalTimeOfDay
	}
	return toSerialize, nil
}

type NullableCustomerTrucksApiListCustomerTrucksItem struct {
	value *CustomerTrucksApiListCustomerTrucksItem
	isSet bool
}

func (v NullableCustomerTrucksApiListCustomerTrucksItem) Get() *CustomerTrucksApiListCustomerTrucksItem {
	return v.value
}

func (v *NullableCustomerTrucksApiListCustomerTrucksItem) Set(val *CustomerTrucksApiListCustomerTrucksItem) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerTrucksApiListCustomerTrucksItem) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerTrucksApiListCustomerTrucksItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerTrucksApiListCustomerTrucksItem(val *CustomerTrucksApiListCustomerTrucksItem) *NullableCustomerTrucksApiListCustomerTrucksItem {
	return &NullableCustomerTrucksApiListCustomerTrucksItem{value: val, isSet: true}
}

func (v NullableCustomerTrucksApiListCustomerTrucksItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerTrucksApiListCustomerTrucksItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


