/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plex

import (
	"encoding/json"
)

// checks if the ProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest{}

// ProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest Tank Lot Log Ignore request.
type ProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest struct {
	// The lot ID to ignore.
	LotId *string `json:"lotId,omitempty"`
}

// NewProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest instantiates a new ProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest() *ProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest {
	this := ProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest{}
	return &this
}

// NewProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequestWithDefaults instantiates a new ProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequestWithDefaults() *ProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest {
	this := ProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest{}
	return &this
}

// GetLotId returns the LotId field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest) GetLotId() string {
	if o == nil || IsNil(o.LotId) {
		var ret string
		return ret
	}
	return *o.LotId
}

// GetLotIdOk returns a tuple with the LotId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest) GetLotIdOk() (*string, bool) {
	if o == nil || IsNil(o.LotId) {
		return nil, false
	}
	return o.LotId, true
}

// HasLotId returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest) HasLotId() bool {
	if o != nil && !IsNil(o.LotId) {
		return true
	}

	return false
}

// SetLotId gets a reference to the given string and assigns it to the LotId field.
func (o *ProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest) SetLotId(v string) {
	o.LotId = &v
}

func (o ProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LotId) {
		toSerialize["lotId"] = o.LotId
	}
	return toSerialize, nil
}

type NullableProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest struct {
	value *ProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest
	isSet bool
}

func (v NullableProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest) Get() *ProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest {
	return v.value
}

func (v *NullableProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest) Set(val *ProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest(val *ProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest) *NullableProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest {
	return &NullableProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest{value: val, isSet: true}
}

func (v NullableProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductionOperationsManagementApiActivateTankEventsLocationIgnoreForLotTraceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


