/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EquipmentApiListEquipmentItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EquipmentApiListEquipmentItem{}

// EquipmentApiListEquipmentItem struct for EquipmentApiListEquipmentItem
type EquipmentApiListEquipmentItem struct {
	// The ID of the Equipment.
	Id *string `json:"id,omitempty"`
	// The Equipment ID.
	EquipmentId *string `json:"equipmentId,omitempty"`
	// The Equipment Description.
	Description *string `json:"description,omitempty"`
	// The Equipment Brand.
	Brand *string `json:"brand,omitempty"`
	// The Equipment Model Number.
	ModelNo *string `json:"modelNo,omitempty"`
	// The Equipment Type of the Equipment.
	EquipmentType *string `json:"equipmentType,omitempty"`
	// The ID of the Equipment Type.
	EquipmentTypeId *string `json:"equipmentTypeId,omitempty"`
	// The Group of the Equipment.
	EquipmentGroup *string `json:"equipmentGroup,omitempty"`
	// The Category of the Equipment.
	EquipmentCategory *string `json:"equipmentCategory,omitempty"`
	// The Priority of the Equipment.
	EquipmentPriority *string `json:"equipmentPriority,omitempty"`
	// The Location of the Equipment.
	Location *string `json:"location,omitempty"`
	// The ID of the Equipment Location.
	LocationId *string `json:"locationId,omitempty"`
	// The Building of the Equipment.
	Building *string `json:"building,omitempty"`
	// The ID of the Equipment Building.
	BuildingId *string `json:"buildingId,omitempty"`
	// The Workcenter of the Equipment.
	Workcenter *string `json:"workcenter,omitempty"`
	// The ID of the Equipment Workcenter.
	WorkcenterId *string `json:"workcenterId,omitempty"`
	// The Department of the Equipment.
	Department *string `json:"department,omitempty"`
	// The Status of the Equipment.
	Status *string `json:"status,omitempty"`
	// The Tax Classification of the Equipment.
	TaxClassification *string `json:"taxClassification,omitempty"`
	// The Champion of the Equipment.
	Champion *string `json:"champion,omitempty"`
	// The Equipment Serial Number.
	SerialNo *string `json:"serialNo,omitempty"`
	// The Equipment Active flag.
	Active *bool `json:"active,omitempty"`
	// The list of associated Equipment Attributes.
	EquipmentAttributes []EquipmentAttributesItem `json:"equipmentAttributes,omitempty"`
	// The list of associated Parts.
	Parts []PartsItem1 `json:"parts,omitempty"`
}

// NewEquipmentApiListEquipmentItem instantiates a new EquipmentApiListEquipmentItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEquipmentApiListEquipmentItem() *EquipmentApiListEquipmentItem {
	this := EquipmentApiListEquipmentItem{}
	return &this
}

// NewEquipmentApiListEquipmentItemWithDefaults instantiates a new EquipmentApiListEquipmentItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEquipmentApiListEquipmentItemWithDefaults() *EquipmentApiListEquipmentItem {
	this := EquipmentApiListEquipmentItem{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *EquipmentApiListEquipmentItem) SetId(v string) {
	o.Id = &v
}

// GetEquipmentId returns the EquipmentId field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetEquipmentId() string {
	if o == nil || IsNil(o.EquipmentId) {
		var ret string
		return ret
	}
	return *o.EquipmentId
}

// GetEquipmentIdOk returns a tuple with the EquipmentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetEquipmentIdOk() (*string, bool) {
	if o == nil || IsNil(o.EquipmentId) {
		return nil, false
	}
	return o.EquipmentId, true
}

// HasEquipmentId returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasEquipmentId() bool {
	if o != nil && !IsNil(o.EquipmentId) {
		return true
	}

	return false
}

// SetEquipmentId gets a reference to the given string and assigns it to the EquipmentId field.
func (o *EquipmentApiListEquipmentItem) SetEquipmentId(v string) {
	o.EquipmentId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *EquipmentApiListEquipmentItem) SetDescription(v string) {
	o.Description = &v
}

// GetBrand returns the Brand field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetBrand() string {
	if o == nil || IsNil(o.Brand) {
		var ret string
		return ret
	}
	return *o.Brand
}

// GetBrandOk returns a tuple with the Brand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetBrandOk() (*string, bool) {
	if o == nil || IsNil(o.Brand) {
		return nil, false
	}
	return o.Brand, true
}

// HasBrand returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasBrand() bool {
	if o != nil && !IsNil(o.Brand) {
		return true
	}

	return false
}

// SetBrand gets a reference to the given string and assigns it to the Brand field.
func (o *EquipmentApiListEquipmentItem) SetBrand(v string) {
	o.Brand = &v
}

// GetModelNo returns the ModelNo field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetModelNo() string {
	if o == nil || IsNil(o.ModelNo) {
		var ret string
		return ret
	}
	return *o.ModelNo
}

// GetModelNoOk returns a tuple with the ModelNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetModelNoOk() (*string, bool) {
	if o == nil || IsNil(o.ModelNo) {
		return nil, false
	}
	return o.ModelNo, true
}

// HasModelNo returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasModelNo() bool {
	if o != nil && !IsNil(o.ModelNo) {
		return true
	}

	return false
}

// SetModelNo gets a reference to the given string and assigns it to the ModelNo field.
func (o *EquipmentApiListEquipmentItem) SetModelNo(v string) {
	o.ModelNo = &v
}

// GetEquipmentType returns the EquipmentType field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetEquipmentType() string {
	if o == nil || IsNil(o.EquipmentType) {
		var ret string
		return ret
	}
	return *o.EquipmentType
}

// GetEquipmentTypeOk returns a tuple with the EquipmentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetEquipmentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.EquipmentType) {
		return nil, false
	}
	return o.EquipmentType, true
}

// HasEquipmentType returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasEquipmentType() bool {
	if o != nil && !IsNil(o.EquipmentType) {
		return true
	}

	return false
}

// SetEquipmentType gets a reference to the given string and assigns it to the EquipmentType field.
func (o *EquipmentApiListEquipmentItem) SetEquipmentType(v string) {
	o.EquipmentType = &v
}

// GetEquipmentTypeId returns the EquipmentTypeId field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetEquipmentTypeId() string {
	if o == nil || IsNil(o.EquipmentTypeId) {
		var ret string
		return ret
	}
	return *o.EquipmentTypeId
}

// GetEquipmentTypeIdOk returns a tuple with the EquipmentTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetEquipmentTypeIdOk() (*string, bool) {
	if o == nil || IsNil(o.EquipmentTypeId) {
		return nil, false
	}
	return o.EquipmentTypeId, true
}

// HasEquipmentTypeId returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasEquipmentTypeId() bool {
	if o != nil && !IsNil(o.EquipmentTypeId) {
		return true
	}

	return false
}

// SetEquipmentTypeId gets a reference to the given string and assigns it to the EquipmentTypeId field.
func (o *EquipmentApiListEquipmentItem) SetEquipmentTypeId(v string) {
	o.EquipmentTypeId = &v
}

// GetEquipmentGroup returns the EquipmentGroup field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetEquipmentGroup() string {
	if o == nil || IsNil(o.EquipmentGroup) {
		var ret string
		return ret
	}
	return *o.EquipmentGroup
}

// GetEquipmentGroupOk returns a tuple with the EquipmentGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetEquipmentGroupOk() (*string, bool) {
	if o == nil || IsNil(o.EquipmentGroup) {
		return nil, false
	}
	return o.EquipmentGroup, true
}

// HasEquipmentGroup returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasEquipmentGroup() bool {
	if o != nil && !IsNil(o.EquipmentGroup) {
		return true
	}

	return false
}

// SetEquipmentGroup gets a reference to the given string and assigns it to the EquipmentGroup field.
func (o *EquipmentApiListEquipmentItem) SetEquipmentGroup(v string) {
	o.EquipmentGroup = &v
}

// GetEquipmentCategory returns the EquipmentCategory field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetEquipmentCategory() string {
	if o == nil || IsNil(o.EquipmentCategory) {
		var ret string
		return ret
	}
	return *o.EquipmentCategory
}

// GetEquipmentCategoryOk returns a tuple with the EquipmentCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetEquipmentCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.EquipmentCategory) {
		return nil, false
	}
	return o.EquipmentCategory, true
}

// HasEquipmentCategory returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasEquipmentCategory() bool {
	if o != nil && !IsNil(o.EquipmentCategory) {
		return true
	}

	return false
}

// SetEquipmentCategory gets a reference to the given string and assigns it to the EquipmentCategory field.
func (o *EquipmentApiListEquipmentItem) SetEquipmentCategory(v string) {
	o.EquipmentCategory = &v
}

// GetEquipmentPriority returns the EquipmentPriority field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetEquipmentPriority() string {
	if o == nil || IsNil(o.EquipmentPriority) {
		var ret string
		return ret
	}
	return *o.EquipmentPriority
}

// GetEquipmentPriorityOk returns a tuple with the EquipmentPriority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetEquipmentPriorityOk() (*string, bool) {
	if o == nil || IsNil(o.EquipmentPriority) {
		return nil, false
	}
	return o.EquipmentPriority, true
}

// HasEquipmentPriority returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasEquipmentPriority() bool {
	if o != nil && !IsNil(o.EquipmentPriority) {
		return true
	}

	return false
}

// SetEquipmentPriority gets a reference to the given string and assigns it to the EquipmentPriority field.
func (o *EquipmentApiListEquipmentItem) SetEquipmentPriority(v string) {
	o.EquipmentPriority = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *EquipmentApiListEquipmentItem) SetLocation(v string) {
	o.Location = &v
}

// GetLocationId returns the LocationId field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetLocationId() string {
	if o == nil || IsNil(o.LocationId) {
		var ret string
		return ret
	}
	return *o.LocationId
}

// GetLocationIdOk returns a tuple with the LocationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetLocationIdOk() (*string, bool) {
	if o == nil || IsNil(o.LocationId) {
		return nil, false
	}
	return o.LocationId, true
}

// HasLocationId returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasLocationId() bool {
	if o != nil && !IsNil(o.LocationId) {
		return true
	}

	return false
}

// SetLocationId gets a reference to the given string and assigns it to the LocationId field.
func (o *EquipmentApiListEquipmentItem) SetLocationId(v string) {
	o.LocationId = &v
}

// GetBuilding returns the Building field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetBuilding() string {
	if o == nil || IsNil(o.Building) {
		var ret string
		return ret
	}
	return *o.Building
}

// GetBuildingOk returns a tuple with the Building field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetBuildingOk() (*string, bool) {
	if o == nil || IsNil(o.Building) {
		return nil, false
	}
	return o.Building, true
}

// HasBuilding returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasBuilding() bool {
	if o != nil && !IsNil(o.Building) {
		return true
	}

	return false
}

// SetBuilding gets a reference to the given string and assigns it to the Building field.
func (o *EquipmentApiListEquipmentItem) SetBuilding(v string) {
	o.Building = &v
}

// GetBuildingId returns the BuildingId field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetBuildingId() string {
	if o == nil || IsNil(o.BuildingId) {
		var ret string
		return ret
	}
	return *o.BuildingId
}

// GetBuildingIdOk returns a tuple with the BuildingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetBuildingIdOk() (*string, bool) {
	if o == nil || IsNil(o.BuildingId) {
		return nil, false
	}
	return o.BuildingId, true
}

// HasBuildingId returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasBuildingId() bool {
	if o != nil && !IsNil(o.BuildingId) {
		return true
	}

	return false
}

// SetBuildingId gets a reference to the given string and assigns it to the BuildingId field.
func (o *EquipmentApiListEquipmentItem) SetBuildingId(v string) {
	o.BuildingId = &v
}

// GetWorkcenter returns the Workcenter field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetWorkcenter() string {
	if o == nil || IsNil(o.Workcenter) {
		var ret string
		return ret
	}
	return *o.Workcenter
}

// GetWorkcenterOk returns a tuple with the Workcenter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetWorkcenterOk() (*string, bool) {
	if o == nil || IsNil(o.Workcenter) {
		return nil, false
	}
	return o.Workcenter, true
}

// HasWorkcenter returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasWorkcenter() bool {
	if o != nil && !IsNil(o.Workcenter) {
		return true
	}

	return false
}

// SetWorkcenter gets a reference to the given string and assigns it to the Workcenter field.
func (o *EquipmentApiListEquipmentItem) SetWorkcenter(v string) {
	o.Workcenter = &v
}

// GetWorkcenterId returns the WorkcenterId field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetWorkcenterId() string {
	if o == nil || IsNil(o.WorkcenterId) {
		var ret string
		return ret
	}
	return *o.WorkcenterId
}

// GetWorkcenterIdOk returns a tuple with the WorkcenterId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetWorkcenterIdOk() (*string, bool) {
	if o == nil || IsNil(o.WorkcenterId) {
		return nil, false
	}
	return o.WorkcenterId, true
}

// HasWorkcenterId returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasWorkcenterId() bool {
	if o != nil && !IsNil(o.WorkcenterId) {
		return true
	}

	return false
}

// SetWorkcenterId gets a reference to the given string and assigns it to the WorkcenterId field.
func (o *EquipmentApiListEquipmentItem) SetWorkcenterId(v string) {
	o.WorkcenterId = &v
}

// GetDepartment returns the Department field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetDepartment() string {
	if o == nil || IsNil(o.Department) {
		var ret string
		return ret
	}
	return *o.Department
}

// GetDepartmentOk returns a tuple with the Department field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetDepartmentOk() (*string, bool) {
	if o == nil || IsNil(o.Department) {
		return nil, false
	}
	return o.Department, true
}

// HasDepartment returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasDepartment() bool {
	if o != nil && !IsNil(o.Department) {
		return true
	}

	return false
}

// SetDepartment gets a reference to the given string and assigns it to the Department field.
func (o *EquipmentApiListEquipmentItem) SetDepartment(v string) {
	o.Department = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *EquipmentApiListEquipmentItem) SetStatus(v string) {
	o.Status = &v
}

// GetTaxClassification returns the TaxClassification field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetTaxClassification() string {
	if o == nil || IsNil(o.TaxClassification) {
		var ret string
		return ret
	}
	return *o.TaxClassification
}

// GetTaxClassificationOk returns a tuple with the TaxClassification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetTaxClassificationOk() (*string, bool) {
	if o == nil || IsNil(o.TaxClassification) {
		return nil, false
	}
	return o.TaxClassification, true
}

// HasTaxClassification returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasTaxClassification() bool {
	if o != nil && !IsNil(o.TaxClassification) {
		return true
	}

	return false
}

// SetTaxClassification gets a reference to the given string and assigns it to the TaxClassification field.
func (o *EquipmentApiListEquipmentItem) SetTaxClassification(v string) {
	o.TaxClassification = &v
}

// GetChampion returns the Champion field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetChampion() string {
	if o == nil || IsNil(o.Champion) {
		var ret string
		return ret
	}
	return *o.Champion
}

// GetChampionOk returns a tuple with the Champion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetChampionOk() (*string, bool) {
	if o == nil || IsNil(o.Champion) {
		return nil, false
	}
	return o.Champion, true
}

// HasChampion returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasChampion() bool {
	if o != nil && !IsNil(o.Champion) {
		return true
	}

	return false
}

// SetChampion gets a reference to the given string and assigns it to the Champion field.
func (o *EquipmentApiListEquipmentItem) SetChampion(v string) {
	o.Champion = &v
}

// GetSerialNo returns the SerialNo field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetSerialNo() string {
	if o == nil || IsNil(o.SerialNo) {
		var ret string
		return ret
	}
	return *o.SerialNo
}

// GetSerialNoOk returns a tuple with the SerialNo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetSerialNoOk() (*string, bool) {
	if o == nil || IsNil(o.SerialNo) {
		return nil, false
	}
	return o.SerialNo, true
}

// HasSerialNo returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasSerialNo() bool {
	if o != nil && !IsNil(o.SerialNo) {
		return true
	}

	return false
}

// SetSerialNo gets a reference to the given string and assigns it to the SerialNo field.
func (o *EquipmentApiListEquipmentItem) SetSerialNo(v string) {
	o.SerialNo = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *EquipmentApiListEquipmentItem) SetActive(v bool) {
	o.Active = &v
}

// GetEquipmentAttributes returns the EquipmentAttributes field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetEquipmentAttributes() []EquipmentAttributesItem {
	if o == nil || IsNil(o.EquipmentAttributes) {
		var ret []EquipmentAttributesItem
		return ret
	}
	return o.EquipmentAttributes
}

// GetEquipmentAttributesOk returns a tuple with the EquipmentAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetEquipmentAttributesOk() ([]EquipmentAttributesItem, bool) {
	if o == nil || IsNil(o.EquipmentAttributes) {
		return nil, false
	}
	return o.EquipmentAttributes, true
}

// HasEquipmentAttributes returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasEquipmentAttributes() bool {
	if o != nil && !IsNil(o.EquipmentAttributes) {
		return true
	}

	return false
}

// SetEquipmentAttributes gets a reference to the given []EquipmentAttributesItem and assigns it to the EquipmentAttributes field.
func (o *EquipmentApiListEquipmentItem) SetEquipmentAttributes(v []EquipmentAttributesItem) {
	o.EquipmentAttributes = v
}

// GetParts returns the Parts field value if set, zero value otherwise.
func (o *EquipmentApiListEquipmentItem) GetParts() []PartsItem1 {
	if o == nil || IsNil(o.Parts) {
		var ret []PartsItem1
		return ret
	}
	return o.Parts
}

// GetPartsOk returns a tuple with the Parts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquipmentApiListEquipmentItem) GetPartsOk() ([]PartsItem1, bool) {
	if o == nil || IsNil(o.Parts) {
		return nil, false
	}
	return o.Parts, true
}

// HasParts returns a boolean if a field has been set.
func (o *EquipmentApiListEquipmentItem) HasParts() bool {
	if o != nil && !IsNil(o.Parts) {
		return true
	}

	return false
}

// SetParts gets a reference to the given []PartsItem1 and assigns it to the Parts field.
func (o *EquipmentApiListEquipmentItem) SetParts(v []PartsItem1) {
	o.Parts = v
}

func (o EquipmentApiListEquipmentItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EquipmentApiListEquipmentItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.EquipmentId) {
		toSerialize["equipmentId"] = o.EquipmentId
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Brand) {
		toSerialize["brand"] = o.Brand
	}
	if !IsNil(o.ModelNo) {
		toSerialize["modelNo"] = o.ModelNo
	}
	if !IsNil(o.EquipmentType) {
		toSerialize["equipmentType"] = o.EquipmentType
	}
	if !IsNil(o.EquipmentTypeId) {
		toSerialize["equipmentTypeId"] = o.EquipmentTypeId
	}
	if !IsNil(o.EquipmentGroup) {
		toSerialize["equipmentGroup"] = o.EquipmentGroup
	}
	if !IsNil(o.EquipmentCategory) {
		toSerialize["equipmentCategory"] = o.EquipmentCategory
	}
	if !IsNil(o.EquipmentPriority) {
		toSerialize["equipmentPriority"] = o.EquipmentPriority
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.LocationId) {
		toSerialize["locationId"] = o.LocationId
	}
	if !IsNil(o.Building) {
		toSerialize["building"] = o.Building
	}
	if !IsNil(o.BuildingId) {
		toSerialize["buildingId"] = o.BuildingId
	}
	if !IsNil(o.Workcenter) {
		toSerialize["workcenter"] = o.Workcenter
	}
	if !IsNil(o.WorkcenterId) {
		toSerialize["workcenterId"] = o.WorkcenterId
	}
	if !IsNil(o.Department) {
		toSerialize["department"] = o.Department
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.TaxClassification) {
		toSerialize["taxClassification"] = o.TaxClassification
	}
	if !IsNil(o.Champion) {
		toSerialize["champion"] = o.Champion
	}
	if !IsNil(o.SerialNo) {
		toSerialize["serialNo"] = o.SerialNo
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.EquipmentAttributes) {
		toSerialize["equipmentAttributes"] = o.EquipmentAttributes
	}
	if !IsNil(o.Parts) {
		toSerialize["parts"] = o.Parts
	}
	return toSerialize, nil
}

type NullableEquipmentApiListEquipmentItem struct {
	value *EquipmentApiListEquipmentItem
	isSet bool
}

func (v NullableEquipmentApiListEquipmentItem) Get() *EquipmentApiListEquipmentItem {
	return v.value
}

func (v *NullableEquipmentApiListEquipmentItem) Set(val *EquipmentApiListEquipmentItem) {
	v.value = val
	v.isSet = true
}

func (v NullableEquipmentApiListEquipmentItem) IsSet() bool {
	return v.isSet
}

func (v *NullableEquipmentApiListEquipmentItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEquipmentApiListEquipmentItem(val *EquipmentApiListEquipmentItem) *NullableEquipmentApiListEquipmentItem {
	return &NullableEquipmentApiListEquipmentItem{value: val, isSet: true}
}

func (v NullableEquipmentApiListEquipmentItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEquipmentApiListEquipmentItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


