/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProductionOperationsManagementApiRecordVariableBOMProductionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductionOperationsManagementApiRecordVariableBOMProductionRequest{}

// ProductionOperationsManagementApiRecordVariableBOMProductionRequest Request object for recording variable BOM production.
type ProductionOperationsManagementApiRecordVariableBOMProductionRequest struct {
	// The list of source components to add to the batch.
	SourceComponentQuantities []SourceComponentQuantitiesItem `json:"sourceComponentQuantities,omitempty"`
	// The source component quantity.
	Quantity *float64 `json:"quantity,omitempty"`
	// A unique identifier for the job op on the workcenter.
	JobOpId *string `json:"jobOpId,omitempty"`
	// Flag indicating if the output container should be finalized.
	CompleteContainer *bool `json:"completeContainer,omitempty"`
	// A unique identifier for a part.
	PartId *string `json:"partId,omitempty"`
	// A unique identifier for a supply item.
	ItemId *string `json:"itemId,omitempty"`
}

// NewProductionOperationsManagementApiRecordVariableBOMProductionRequest instantiates a new ProductionOperationsManagementApiRecordVariableBOMProductionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductionOperationsManagementApiRecordVariableBOMProductionRequest() *ProductionOperationsManagementApiRecordVariableBOMProductionRequest {
	this := ProductionOperationsManagementApiRecordVariableBOMProductionRequest{}
	return &this
}

// NewProductionOperationsManagementApiRecordVariableBOMProductionRequestWithDefaults instantiates a new ProductionOperationsManagementApiRecordVariableBOMProductionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductionOperationsManagementApiRecordVariableBOMProductionRequestWithDefaults() *ProductionOperationsManagementApiRecordVariableBOMProductionRequest {
	this := ProductionOperationsManagementApiRecordVariableBOMProductionRequest{}
	return &this
}

// GetSourceComponentQuantities returns the SourceComponentQuantities field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) GetSourceComponentQuantities() []SourceComponentQuantitiesItem {
	if o == nil || IsNil(o.SourceComponentQuantities) {
		var ret []SourceComponentQuantitiesItem
		return ret
	}
	return o.SourceComponentQuantities
}

// GetSourceComponentQuantitiesOk returns a tuple with the SourceComponentQuantities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) GetSourceComponentQuantitiesOk() ([]SourceComponentQuantitiesItem, bool) {
	if o == nil || IsNil(o.SourceComponentQuantities) {
		return nil, false
	}
	return o.SourceComponentQuantities, true
}

// HasSourceComponentQuantities returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) HasSourceComponentQuantities() bool {
	if o != nil && !IsNil(o.SourceComponentQuantities) {
		return true
	}

	return false
}

// SetSourceComponentQuantities gets a reference to the given []SourceComponentQuantitiesItem and assigns it to the SourceComponentQuantities field.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) SetSourceComponentQuantities(v []SourceComponentQuantitiesItem) {
	o.SourceComponentQuantities = v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) GetQuantity() float64 {
	if o == nil || IsNil(o.Quantity) {
		var ret float64
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) GetQuantityOk() (*float64, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given float64 and assigns it to the Quantity field.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) SetQuantity(v float64) {
	o.Quantity = &v
}

// GetJobOpId returns the JobOpId field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) GetJobOpId() string {
	if o == nil || IsNil(o.JobOpId) {
		var ret string
		return ret
	}
	return *o.JobOpId
}

// GetJobOpIdOk returns a tuple with the JobOpId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) GetJobOpIdOk() (*string, bool) {
	if o == nil || IsNil(o.JobOpId) {
		return nil, false
	}
	return o.JobOpId, true
}

// HasJobOpId returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) HasJobOpId() bool {
	if o != nil && !IsNil(o.JobOpId) {
		return true
	}

	return false
}

// SetJobOpId gets a reference to the given string and assigns it to the JobOpId field.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) SetJobOpId(v string) {
	o.JobOpId = &v
}

// GetCompleteContainer returns the CompleteContainer field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) GetCompleteContainer() bool {
	if o == nil || IsNil(o.CompleteContainer) {
		var ret bool
		return ret
	}
	return *o.CompleteContainer
}

// GetCompleteContainerOk returns a tuple with the CompleteContainer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) GetCompleteContainerOk() (*bool, bool) {
	if o == nil || IsNil(o.CompleteContainer) {
		return nil, false
	}
	return o.CompleteContainer, true
}

// HasCompleteContainer returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) HasCompleteContainer() bool {
	if o != nil && !IsNil(o.CompleteContainer) {
		return true
	}

	return false
}

// SetCompleteContainer gets a reference to the given bool and assigns it to the CompleteContainer field.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) SetCompleteContainer(v bool) {
	o.CompleteContainer = &v
}

// GetPartId returns the PartId field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) GetPartId() string {
	if o == nil || IsNil(o.PartId) {
		var ret string
		return ret
	}
	return *o.PartId
}

// GetPartIdOk returns a tuple with the PartId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) GetPartIdOk() (*string, bool) {
	if o == nil || IsNil(o.PartId) {
		return nil, false
	}
	return o.PartId, true
}

// HasPartId returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) HasPartId() bool {
	if o != nil && !IsNil(o.PartId) {
		return true
	}

	return false
}

// SetPartId gets a reference to the given string and assigns it to the PartId field.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) SetPartId(v string) {
	o.PartId = &v
}

// GetItemId returns the ItemId field value if set, zero value otherwise.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) GetItemId() string {
	if o == nil || IsNil(o.ItemId) {
		var ret string
		return ret
	}
	return *o.ItemId
}

// GetItemIdOk returns a tuple with the ItemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) GetItemIdOk() (*string, bool) {
	if o == nil || IsNil(o.ItemId) {
		return nil, false
	}
	return o.ItemId, true
}

// HasItemId returns a boolean if a field has been set.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) HasItemId() bool {
	if o != nil && !IsNil(o.ItemId) {
		return true
	}

	return false
}

// SetItemId gets a reference to the given string and assigns it to the ItemId field.
func (o *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) SetItemId(v string) {
	o.ItemId = &v
}

func (o ProductionOperationsManagementApiRecordVariableBOMProductionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductionOperationsManagementApiRecordVariableBOMProductionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SourceComponentQuantities) {
		toSerialize["sourceComponentQuantities"] = o.SourceComponentQuantities
	}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	if !IsNil(o.JobOpId) {
		toSerialize["jobOpId"] = o.JobOpId
	}
	if !IsNil(o.CompleteContainer) {
		toSerialize["completeContainer"] = o.CompleteContainer
	}
	if !IsNil(o.PartId) {
		toSerialize["partId"] = o.PartId
	}
	if !IsNil(o.ItemId) {
		toSerialize["itemId"] = o.ItemId
	}
	return toSerialize, nil
}

type NullableProductionOperationsManagementApiRecordVariableBOMProductionRequest struct {
	value *ProductionOperationsManagementApiRecordVariableBOMProductionRequest
	isSet bool
}

func (v NullableProductionOperationsManagementApiRecordVariableBOMProductionRequest) Get() *ProductionOperationsManagementApiRecordVariableBOMProductionRequest {
	return v.value
}

func (v *NullableProductionOperationsManagementApiRecordVariableBOMProductionRequest) Set(val *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProductionOperationsManagementApiRecordVariableBOMProductionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProductionOperationsManagementApiRecordVariableBOMProductionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductionOperationsManagementApiRecordVariableBOMProductionRequest(val *ProductionOperationsManagementApiRecordVariableBOMProductionRequest) *NullableProductionOperationsManagementApiRecordVariableBOMProductionRequest {
	return &NullableProductionOperationsManagementApiRecordVariableBOMProductionRequest{value: val, isSet: true}
}

func (v NullableProductionOperationsManagementApiRecordVariableBOMProductionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductionOperationsManagementApiRecordVariableBOMProductionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


