/*
Plex Developer API

Auto-generated OpenAPI spec from developers.plex.com

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package plex

import (
	"encoding/json"
)

// checks if the CustomObjectsApiListCustomObjectsItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomObjectsApiListCustomObjectsItem{}

// CustomObjectsApiListCustomObjectsItem struct for CustomObjectsApiListCustomObjectsItem
type CustomObjectsApiListCustomObjectsItem struct {
	// The name of the custom object that is used internally by the system.
	CustomObjectName *string `json:"customObjectName,omitempty"`
}

// NewCustomObjectsApiListCustomObjectsItem instantiates a new CustomObjectsApiListCustomObjectsItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomObjectsApiListCustomObjectsItem() *CustomObjectsApiListCustomObjectsItem {
	this := CustomObjectsApiListCustomObjectsItem{}
	return &this
}

// NewCustomObjectsApiListCustomObjectsItemWithDefaults instantiates a new CustomObjectsApiListCustomObjectsItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomObjectsApiListCustomObjectsItemWithDefaults() *CustomObjectsApiListCustomObjectsItem {
	this := CustomObjectsApiListCustomObjectsItem{}
	return &this
}

// GetCustomObjectName returns the CustomObjectName field value if set, zero value otherwise.
func (o *CustomObjectsApiListCustomObjectsItem) GetCustomObjectName() string {
	if o == nil || IsNil(o.CustomObjectName) {
		var ret string
		return ret
	}
	return *o.CustomObjectName
}

// GetCustomObjectNameOk returns a tuple with the CustomObjectName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomObjectsApiListCustomObjectsItem) GetCustomObjectNameOk() (*string, bool) {
	if o == nil || IsNil(o.CustomObjectName) {
		return nil, false
	}
	return o.CustomObjectName, true
}

// HasCustomObjectName returns a boolean if a field has been set.
func (o *CustomObjectsApiListCustomObjectsItem) HasCustomObjectName() bool {
	if o != nil && !IsNil(o.CustomObjectName) {
		return true
	}

	return false
}

// SetCustomObjectName gets a reference to the given string and assigns it to the CustomObjectName field.
func (o *CustomObjectsApiListCustomObjectsItem) SetCustomObjectName(v string) {
	o.CustomObjectName = &v
}

func (o CustomObjectsApiListCustomObjectsItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomObjectsApiListCustomObjectsItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomObjectName) {
		toSerialize["customObjectName"] = o.CustomObjectName
	}
	return toSerialize, nil
}

type NullableCustomObjectsApiListCustomObjectsItem struct {
	value *CustomObjectsApiListCustomObjectsItem
	isSet bool
}

func (v NullableCustomObjectsApiListCustomObjectsItem) Get() *CustomObjectsApiListCustomObjectsItem {
	return v.value
}

func (v *NullableCustomObjectsApiListCustomObjectsItem) Set(val *CustomObjectsApiListCustomObjectsItem) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomObjectsApiListCustomObjectsItem) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomObjectsApiListCustomObjectsItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomObjectsApiListCustomObjectsItem(val *CustomObjectsApiListCustomObjectsItem) *NullableCustomObjectsApiListCustomObjectsItem {
	return &NullableCustomObjectsApiListCustomObjectsItem{value: val, isSet: true}
}

func (v NullableCustomObjectsApiListCustomObjectsItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomObjectsApiListCustomObjectsItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


